'use client'
import {FormEvent,useCallback,useEffect,useMemo,useRef,useState} from 'react'
import Link from 'next/link'
import {CheckCircle2,KeyRound,LockKeyhole,MessageCircle,Plus,RefreshCw,Send,ShieldCheck,Users,X} from 'lucide-react'
import {supabase} from '../../lib/supabase'
import {createConversationKey,createDeviceSupportIdentity,createSupportIdentity,decryptSupportText,encryptSupportText,isDeviceSupportIdentity,PublicRecipient,SupportIdentityRow,unlockDeviceSupportIdentity,unlockSupportIdentity,unwrapConversationKey,validateSupportPin,wrapConversationKey} from '../../lib/support-crypto'

type Conversation={id:string;buyer_id:string;team_id:string;assigned_to:string|null;category:string;priority:string;status:string;subject_ciphertext:string;subject_iv:string;last_message_at:string;created_at:string}
type Message={id:string;conversation_id:string;sender_id:string;ciphertext:string;iv:string;created_at:string;deleted_at:string|null}
type Roster={team_id:string;user_id:string;display_name:string;email:string;team_role:string;is_active:boolean;crypto_ready:boolean}
const SUBJECT_CONTEXT='nis-support:subject:v1',MESSAGE_CONTEXT='nis-support:message:v1'
const categoryOptions=['general','product','order','payment','delivery','technical','warranty']
const priorityOptions=['low','normal','high','urgent']
const statusOptions=['open','pending_buyer','pending_team','resolved','closed']
function title(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function when(value:string){return new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}

export default function SecureSupportWorkspace({mode}:{mode:'buyer'|'admin'}){
 const [userId,setUserId]=useState(''),[identity,setIdentity]=useState<SupportIdentityRow|null>(null),[privateKey,setPrivateKey]=useState<CryptoKey|null>(null),[pin,setPin]=useState(''),[conversations,setConversations]=useState<Conversation[]>([]),[subjects,setSubjects]=useState<Record<string,string>>({}),[keys,setKeys]=useState<Record<string,CryptoKey>>({}),[selectedId,setSelectedId]=useState(''),[messages,setMessages]=useState<(Message&{plain:string})[]>([]),[draft,setDraft]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[deviceIssue,setDeviceIssue]=useState(''),[showCreate,setShowCreate]=useState(false),[showTeam,setShowTeam]=useState(false),[subject,setSubject]=useState(''),[initial,setInitial]=useState(''),[category,setCategory]=useState('general'),[priority,setPriority]=useState('normal'),[roster,setRoster]=useState<Roster[]>([]),[memberEmail,setMemberEmail]=useState(''),[memberRole,setMemberRole]=useState('agent')
 const buyerDeviceStarted=useRef(false)
 const selected=conversations.find(x=>x.id===selectedId)||null
 const loadIdentity=useCallback(async(uid:string)=>{const {data}=await supabase.from('support_crypto_identities').select('*').eq('user_id',uid).maybeSingle();setIdentity((data||null) as SupportIdentityRow|null)},[])
 const loadConversations=useCallback(async()=>{const {data,error}=await supabase.from('support_conversations').select('*').order('last_message_at',{ascending:false});if(error)setNotice(error.message);else setConversations((data||[]) as Conversation[])},[])
 const loadRoster=useCallback(async()=>{if(mode!=='admin')return;const {data}=await supabase.rpc('support_admin_roster');setRoster((data||[]) as Roster[])},[mode])
 useEffect(()=>{let live=true;supabase.auth.getUser().then(async({data})=>{if(!live)return;const uid=data.user?.id||'';setUserId(uid);if(uid){await Promise.all([loadIdentity(uid),loadConversations(),loadRoster()])}setLoading(false)});return()=>{live=false}},[loadIdentity,loadConversations,loadRoster])
 useEffect(()=>{if(!userId)return;const channel=supabase.channel(`secure-support-${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'support_messages'},()=>{loadConversations();if(selectedId)loadMessages(selectedId)}).on('postgres_changes',{event:'*',schema:'public',table:'support_conversations'},()=>loadConversations()).subscribe();return()=>{supabase.removeChannel(channel)}},[userId,selectedId,loadConversations])
 useEffect(()=>{if(privateKey)decryptConversationList(privateKey)},[privateKey,conversations])
 useEffect(()=>{if(selectedId&&keys[selectedId])loadMessages(selectedId)},[selectedId,keys])
 useEffect(()=>{if(mode!=='buyer'||loading||!userId||privateKey||buyerDeviceStarted.current)return;buyerDeviceStarted.current=true;prepareBuyerDevice()},[mode,loading,userId,privateKey])
 async function prepareBuyerDevice(replace=false){setBusy(true);setDeviceIssue('');try{if(!identity||replace){const next=await createDeviceSupportIdentity(userId);const {privateKey:key,...row}=next;const {error}=await supabase.from('support_crypto_identities').upsert({...row,user_id:userId},{onConflict:'user_id'});if(error)throw error;setIdentity({...row,user_id:userId});setPrivateKey(key);setNotice('Secure support is ready on this device.');return}if(!isDeviceSupportIdentity(identity)){setDeviceIssue('This account still uses the earlier buyer PIN system. Activate this browser to switch to automatic secure access.');return}setPrivateKey(await unlockDeviceSupportIdentity(identity))}catch(error:any){setDeviceIssue(error.message||'Secure support could not be prepared on this device.')}finally{setBusy(false)}}
 async function setupIdentity(e:FormEvent){e.preventDefault();const error=validateSupportPin(pin);if(error){setNotice(error);return}setBusy(true);try{const next=await createSupportIdentity(pin,userId);const {privateKey:key,...row}=next;const {error:saveError}=await supabase.from('support_crypto_identities').insert({...row,user_id:userId});if(saveError)throw saveError;setIdentity({...row,user_id:userId});setPrivateKey(key);setPin('');setNotice('Secure Chat encryption is ready. Keep your PIN safe; New India Solar cannot recover it.')}catch(error:any){setNotice(error.message||'Could not create secure identity.')}finally{setBusy(false)}}
 async function unlock(e:FormEvent){e.preventDefault();if(!identity)return;setBusy(true);try{const key=await unlockSupportIdentity(identity,pin);setPrivateKey(key);setPin('');setNotice('Messages unlocked on this device.')}catch(error:any){setNotice(error.message)}finally{setBusy(false)}}
 async function decryptConversationList(key:CryptoKey){const nextKeys:Record<string,CryptoKey>={},nextSubjects:Record<string,string>={};await Promise.all(conversations.map(async c=>{const {data}=await supabase.from('support_conversation_keys').select('wrapped_key').eq('conversation_id',c.id).eq('recipient_id',userId).maybeSingle();if(!data)return;try{const conversationKey=await unwrapConversationKey(data.wrapped_key,key);nextKeys[c.id]=conversationKey;nextSubjects[c.id]=await decryptSupportText(conversationKey,c.subject_ciphertext,c.subject_iv,SUBJECT_CONTEXT)}catch{nextSubjects[c.id]='Encrypted conversation'}}));setKeys(v=>({...v,...nextKeys}));setSubjects(v=>({...v,...nextSubjects}));if(!selectedId&&conversations[0])setSelectedId(conversations[0].id)}
 async function loadMessages(conversationId:string){const key=keys[conversationId];if(!key)return;const {data,error}=await supabase.from('support_messages').select('*').eq('conversation_id',conversationId).order('created_at');if(error){setNotice(error.message);return}const rows=await Promise.all(((data||[]) as Message[]).map(async m=>({...m,plain:m.deleted_at?'Message removed':await decryptSupportText(key,m.ciphertext,m.iv,MESSAGE_CONTEXT)})));setMessages(rows);await supabase.rpc('support_mark_read',{p_conversation_id:conversationId})}
 async function createConversation(e:FormEvent){e.preventDefault();if(!privateKey||!subject.trim()||!initial.trim())return;setBusy(true);try{const {data:teams,error:teamError}=await supabase.from('support_teams').select('id').eq('is_active',true).limit(1).single();if(teamError)throw teamError;const {data:recipients,error:recipientError}=await supabase.rpc('support_public_recipients',{p_team_id:teams.id});if(recipientError)throw recipientError;const support=(recipients||[]) as PublicRecipient[];if(!support.length)throw new Error('No support teammate has activated Secure Chat yet. Please try again shortly.');const conversationKey=await createConversationKey();const own:PublicRecipient={user_id:userId,display_name:'You',public_key_jwk:identity!.public_key_jwk,key_version:identity!.key_version};const envelopes=await Promise.all([own,...support.filter(x=>x.user_id!==userId)].map(x=>wrapConversationKey(conversationKey,x)));const [encryptedSubject,encryptedMessage]=await Promise.all([encryptSupportText(conversationKey,subject.trim(),SUBJECT_CONTEXT),encryptSupportText(conversationKey,initial.trim(),MESSAGE_CONTEXT)]);const {data:id,error}=await supabase.rpc('support_create_conversation',{p_team_id:teams.id,p_category:category,p_priority:priority,p_subject_ciphertext:encryptedSubject.ciphertext,p_subject_iv:encryptedSubject.iv,p_initial_ciphertext:encryptedMessage.ciphertext,p_initial_iv:encryptedMessage.iv,p_envelopes:envelopes});if(error)throw error;setKeys(v=>({...v,[id]:conversationKey}));setSubjects(v=>({...v,[id]:subject.trim()}));setShowCreate(false);setSubject('');setInitial('');await loadConversations();setSelectedId(id);setNotice('Secure conversation created.')}catch(error:any){setNotice(error.message||'Could not start conversation.')}finally{setBusy(false)}}
 async function send(e:FormEvent){e.preventDefault();if(!selected||!draft.trim()||!keys[selected.id])return;setBusy(true);try{const encrypted=await encryptSupportText(keys[selected.id],draft.trim(),MESSAGE_CONTEXT);const {error}=await supabase.from('support_messages').insert({conversation_id:selected.id,sender_id:userId,ciphertext:encrypted.ciphertext,iv:encrypted.iv});if(error)throw error;setDraft('');await loadMessages(selected.id);await loadConversations()}catch(error:any){setNotice(error.message)}finally{setBusy(false)}}
 async function assign(field:'status'|'priority'|'assigned_to',value:string|null){if(!selected)return;const args={p_conversation_id:selected.id,p_assigned_to:field==='assigned_to'?value:selected.assigned_to,p_status:field==='status'?value:selected.status,p_priority:field==='priority'?value:selected.priority};const {error}=await supabase.rpc('support_assign_conversation',args);if(error)setNotice(error.message);else{await loadConversations();setNotice('Conversation updated.')}}
 async function setMemberAccess(email:string,role:string,active:boolean){if(!roster[0]?.team_id){setNotice('Support team not available.');return}setBusy(true);const {error}=await supabase.rpc('support_set_team_member',{p_team_id:roster[0].team_id,p_email:email,p_team_role:role,p_is_active:active});setBusy(false);if(error)setNotice(error.message);else{setMemberEmail('');await loadRoster();setNotice(active?'Support access granted.':'Support access revoked.')}}
 const assignedName=useMemo(()=>roster.find(x=>x.user_id===selected?.assigned_to)?.display_name||'Unassigned',[roster,selected])
 if(loading)return <div className="supportState"><RefreshCw className="spin"/> Loading secure support…</div>
 if(!userId)return <section className="supportState"><LockKeyhole/><h1>Sign in for secure support</h1><p>Your private support conversations are linked to your verified account.</p><Link href="/login?next=/account/support">Sign in securely</Link></section>
 if(mode==='buyer'&&!privateKey)return <section className="supportState"><ShieldCheck/><span>AUTOMATIC DEVICE PROTECTION</span><h1>{busy?'Preparing secure support…':'Secure support on this device'}</h1><p>{deviceIssue||'Your encrypted chat key is protected automatically in this browser. No separate buyer PIN is required.'}</p>{deviceIssue&&conversations.length===0&&<button disabled={busy} onClick={()=>prepareBuyerDevice(true)}><LockKeyhole/> Activate this browser</button>}{deviceIssue&&conversations.length>0&&<small>Open chat on the browser where it was activated, or contact New India Solar to reset secure support.</small>}</section>
 if(mode==='admin'&&!identity)return <section className="supportState"><ShieldCheck/><span>ONE-TIME SECURITY SETUP</span><h1>Create your Secure Chat PIN</h1><p>This PIN encrypts your private key in this browser. It is separate from your login password and cannot be recovered.</p><form onSubmit={setupIdentity}><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="8+ characters, letters and numbers" autoComplete="new-password"/><button disabled={busy}><KeyRound/> Create encrypted identity</button></form>{notice&&<small>{notice}</small>}</section>
 if(mode==='admin'&&!privateKey)return <section className="supportState"><LockKeyhole/><span>END-TO-END ENCRYPTED</span><h1>Unlock secure messages</h1><p>Enter your Secure Chat PIN. Decryption happens only on this device.</p><form onSubmit={unlock}><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Secure Chat PIN" autoComplete="current-password"/><button disabled={busy}><KeyRound/> Unlock</button></form>{notice&&<small>{notice}</small>}</section>
 return <div className={`supportWorkspace ${mode}`}><header className="supportTop"><div><span><LockKeyhole/> END-TO-END ENCRYPTED</span><h1>{mode==='admin'?'Secure Support Desk':'Private Support'}</h1><p>{mode==='admin'?'Assign, reply and manage buyer conversations securely.':'Product, order, payment and technical help from our team.'}</p></div><div className="supportTopActions">{mode==='admin'&&<button onClick={()=>setShowTeam(true)}><Users/> Team access</button>} {mode==='buyer'&&<button onClick={()=>setShowCreate(true)}><Plus/> New conversation</button>}</div></header>{notice&&<div className="supportNotice"><CheckCircle2/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}<div className="supportGrid"><aside className="supportInbox"><b>CONVERSATIONS</b>{conversations.length?conversations.map(c=><button key={c.id} className={selectedId===c.id?'active':''} onClick={()=>setSelectedId(c.id)}><span>{subjects[c.id]||'Unlocking conversation…'}</span><small>{title(c.category)} · {when(c.last_message_at)}</small><em className={`supportStatus ${c.status}`}>{title(c.status)}</em></button>):<div className="supportEmpty"><MessageCircle/><p>No secure conversations yet.</p></div>}</aside><section className="supportThread">{selected?<><div className="supportThreadHead"><div><span>{title(selected.category)} · {selected.priority} priority</span><h2>{subjects[selected.id]||'Encrypted conversation'}</h2>{mode==='admin'&&<small>Assigned: {assignedName}</small>}</div>{mode==='admin'&&<div className="supportControls"><select value={selected.assigned_to||''} onChange={e=>assign('assigned_to',e.target.value||null)}><option value="">Unassigned</option>{roster.filter(x=>x.is_active&&x.crypto_ready).map(x=><option key={x.user_id} value={x.user_id}>{x.display_name}</option>)}</select><select value={selected.priority} onChange={e=>assign('priority',e.target.value)}>{priorityOptions.map(x=><option key={x}>{title(x)}</option>)}</select><select value={selected.status} onChange={e=>assign('status',e.target.value)}>{statusOptions.map(x=><option key={x}>{title(x)}</option>)}</select></div>}</div><div className="supportMessages">{messages.map(m=><article key={m.id} className={m.sender_id===userId?'mine':'theirs'}><b>{m.sender_id===userId?'You':mode==='admin'?(m.sender_id===selected.buyer_id?'Buyer':'Support teammate'):'New India Solar Support'}</b><p>{m.plain}</p><time>{when(m.created_at)}</time></article>)}</div><form className="supportComposer" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Type a secure message…" maxLength={12000}/><button disabled={busy||!draft.trim()}><Send/> Send securely</button></form></>:<div className="supportEmpty large"><LockKeyhole/><h2>Select a conversation</h2><p>Encrypted messages appear here after you select a thread.</p></div>}</section></div>
 {showCreate&&<div className="supportModal"><form onSubmit={createConversation}><button type="button" className="close" onClick={()=>setShowCreate(false)}><X/></button><span>NEW SECURE CONVERSATION</span><h2>How can we help?</h2><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160} required/></label><div className="supportFormRow"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categoryOptions.map(x=><option key={x}>{title(x)}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{priorityOptions.map(x=><option key={x}>{title(x)}</option>)}</select></label></div><label>Message<textarea value={initial} onChange={e=>setInitial(e.target.value)} maxLength={12000} required/></label><button className="primary" disabled={busy}><LockKeyhole/> Start encrypted chat</button></form></div>}
 {showTeam&&<div className="supportModal"><div className="supportTeamPanel"><button className="close" onClick={()=>setShowTeam(false)}><X/></button><span>SUPPORT TEAM ACCESS</span><h2>Agents and supervisors</h2><div className="supportAddMember"><input type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} placeholder="Team member email"/><select value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="agent">Agent</option><option value="supervisor">Supervisor</option></select><button disabled={busy||!memberEmail} onClick={()=>setMemberAccess(memberEmail,memberRole,true)}>Grant access</button></div><div className="supportRoster">{roster.map(r=><div key={r.user_id}><span><b>{r.display_name}</b><small>{r.email} · {title(r.team_role)} · {r.crypto_ready?'Encryption ready':'Setup required'}</small></span><div className="supportMemberActions"><em className={r.is_active?'active':'inactive'}>{r.is_active?'Active':'Revoked'}</em><button onClick={()=>setMemberAccess(r.email,r.team_role,!r.is_active)}>{r.is_active?'Revoke':'Restore'}</button></div></div>)}</div></div></div>}
 </div>
}
