'use client'
import Link from 'next/link'
import {Minus,Plus,ShoppingBag,Trash2} from 'lucide-react'
import {useCart} from '../../components/CartProvider'
import {linePrice,rounded} from '../../lib/buyer-commerce'
import {money} from '../../lib/catalogue'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'
export default function Cart(){
  const {items,total,tax,grandTotal,ready,storageWarning,remove,updateQty}=useCart()
  return <><StoreHeader/><main id="main-content" className="container cartPage"><div className="cartPageHead"><div><span className="eyebrow darkEye">YOUR ORDER</span><h1>Shopping Cart</h1><p>{!ready?'Loading saved cart…':items.length?`${items.length} line items ready for review.`:'Your cart is currently empty.'}</p></div><Link className="nisTextLink" href="/shop">Continue shopping →</Link></div>{storageWarning&&<p role="status">{storageWarning}</p>}{!ready?<p role="status">Loading…</p>:!items.length?<div className="emptyCart premiumEmpty"><ShoppingBag size={38}/><h2>Your cart is empty.</h2><p>Browse solar components or request a custom ACDB/DCDB.</p><div className="btnRow"><Link className="btn btnPrimary" href="/shop">Shop Products</Link><Link className="btn" href="/customize">Custom boxes</Link></div></div>:<div className="cartLayout"><section className="cartItemsPanel">{items.map(i=>{const price=linePrice(i.price,i.gstRate,i.qty),step=i.quantityStep||1,min=i.minQty||1;return <div className="cartRow" key={i.id}><div className="cartThumb">{i.kind==='custom'?'BUILD':'ITEM'}</div><div className="cartInfo"><span className="cartKind">{i.kind==='custom'?'Custom configuration':'Product'}</span><b>{i.name}</b><span>{i.variant}</span><small>Base {money(i.price)}{i.gstRate!=null?` + ${i.gstRate}% GST per unit`:' · Tax needs refresh at checkout'}</small><button onClick={()=>remove(i.id)}><Trash2 size={13}/> Remove</button></div><div className="qty qtyModern"><button aria-label={`Decrease quantity of ${i.name}`} disabled={i.qty-step<min} onClick={()=>updateQty(i.id,rounded(i.qty-step,6))}><Minus size={14}/></button><span>{i.qty}</span><button aria-label={`Increase quantity of ${i.name}`} onClick={()=>updateQty(i.id,rounded(i.qty+step,6))}><Plus size={14}/></button></div><strong>{money(price?.total??i.price*i.qty)}<small>{price?'incl. GST':'before GST'}</small></strong></div>})}</section><aside className="summary"><h2>Order Summary</h2><div><span>Subtotal before GST</span><b>{money(total)}</b></div><div><span>GST</span><b>{tax===null?'Needs confirmation':money(tax)}</b></div><div><span>Shipping</span><span>Confirmed at checkout</span></div><div className="grand"><span>{grandTotal===null?'Before tax':'Total incl. GST'}</span><b>{money(grandTotal??total)}</b></div><p className="summaryNote">These are saved estimates. Final price, quantity and tax require confirmation before ordering.</p><Link className="btn btnPrimary fullBtn" href="/checkout">Proceed to Checkout</Link><Link className="bulkLink" href="/bulk-order">Request project pricing →</Link></aside></div>}</main><StoreFooter/></>
}
