'use client'

import {FormEvent,useEffect,useState} from 'react'
import {Check,Plus,Trash2} from 'lucide-react'
import {supabase} from '../../../../lib/supabase'

export default function ConfiguratorRules(){
 const [templates,setTemplates]=useState<any[]>([]),[enclosures,setEnclosures]=useState<any[]>([]),[components,setComponents]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(''),[form,setForm]=useState<any>({template_id:'',enclosure_id:'',component_id:'',option_key:'',slot_key:'',allowed:true,min_qty:1,max_qty:1})
 useEffect(()=>{Promise.all([supabase.from('configurator_templates').select('id,name,type'),supabase.from('enclosures').select('id,name'),supabase.from('components').select('id,name,category,brands(name)').eq('is_active',true).order('category').order('name')]).then(([t,e,c])=>{setTemplates(t.data||[]);setEnclosures(e.data||[]);setComponents(c.data||[]);if(t.data?.[0])setForm((f:any)=>({...f,template_id:t.data[0].id}));load()})},[])
 async function load(){const {data}=await supabase.from('configurator_component_compatibility').select('*,configurator_templates(name),enclosures(name),components(name,category)').order('created_at',{ascending:false});setRows(data||[])}
 async function save(e:FormEvent){e.preventDefault();const p={template_id:form.template_id,enclosure_id:form.enclosure_id||null,component_id:form.component_id,option_key:form.option_key||null,slot_key:form.slot_key||null,allowed:!!form.allowed,min_qty:Number(form.min_qty||1),max_qty:Number(form.max_qty||1),rule:{source:'admin'}};const r=await supabase.from('configurator_component_compatibility').insert(p);if(r.error){setMsg(r.error.message);return}setMsg('Compatibility rule saved.');setForm((f:any)=>({...f,component_id:'',option_key:'',slot_key:'',min_qty:1,max_qty:1}));load()}
 async function remove(id:string){await supabase.from('configurator_component_compatibility').delete().eq('id',id);load()}
 return <div className="cfgAdmin"><div className="adminPageHead"><div><span className="adminEyebrow">COMPATIBILITY ENGINE</span><h1>Configurator Rules</h1><p>Restrict components by builder, enclosure and option. If no rule exists, the current V2 engine treats linked option values as available.</p></div></div>{msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}<form className="cfgRuleForm" onSubmit={save}><label><span>Builder</span><select required value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span>Enclosure</span><select value={form.enclosure_id} onChange={e=>setForm({...form,enclosure_id:e.target.value})}><option value="">All enclosures</option>{enclosures.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Component</span><select required value={form.component_id} onChange={e=>setForm({...form,component_id:e.target.value})}><option value="">Select component</option>{components.map(c=><option key={c.id} value={c.id}>{c.category} — {c.brands?.name?`${c.brands.name} `:''}{c.name}</option>)}</select></label><label><span>Option Key</span><input value={form.option_key} onChange={e=>setForm({...form,option_key:e.target.value})} placeholder="dc_mcb / spd / terminal"/></label><label><span>Slot Key</span><input value={form.slot_key} onChange={e=>setForm({...form,slot_key:e.target.value})} placeholder="optional"/></label><label><span>Min Qty</span><input type="number" value={form.min_qty} onChange={e=>setForm({...form,min_qty:e.target.value})}/></label><label><span>Max Qty</span><input type="number" value={form.max_qty} onChange={e=>setForm({...form,max_qty:e.target.value})}/></label><label className="cfgCheck"><input type="checkbox" checked={form.allowed} onChange={e=>setForm({...form,allowed:e.target.checked})}/> Allowed</label><button className="adminBtn"><Plus size={15}/>Add Rule</button></form><section className="cfgPanel"><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Builder</th><th>Enclosure</th><th>Component</th><th>Option</th><th>Qty</th><th>Allowed</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.configurator_templates?.name}</td><td>{r.enclosures?.name||'All'}</td><td><b>{r.components?.name}</b><span className="tableSub">{r.components?.category}</span></td><td>{r.option_key||'—'}</td><td>{r.min_qty}–{r.max_qty}</td><td>{r.allowed?'Yes':'No'}</td><td><button className="cfgIconDanger" onClick={()=>remove(r.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></section></div>
}
