import type {Metadata} from 'next'
import Link from 'next/link'
import {ArrowRight,Building2,FileText,MapPin,MessagesSquare,ReceiptText,UserRound} from 'lucide-react'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'
import {COMPANY} from '../../lib/company'

export const metadata:Metadata={title:'Contact New India Solar | Project & Buyer Support',description:'Contact New India Solar Components Pvt Ltd for product selection, ACDB/DCDB requirements, project quantities and order support.',alternates:{canonical:'/contact'}}

export default function ContactPage(){return <><StoreHeader/><main id="main-content" className="contactPage"><section className="contactHero"><div className="container"><span>CONTACT NEW INDIA SOLAR</span><h1>Tell us what your<br/><em>solar project needs.</em></h1><p>Choose the quickest route below for product selection, bulk quantities, custom ACDB/DCDB requirements or an existing order.</p></div></section><section className="container contactRoutes"><article><i><FileText/></i><span>PROJECT & BULK BUYING</span><h2>Send your BOQ or requirement</h2><p>Share ratings, quantities and dispatch location through the structured RFQ form.</p><Link href="/bulk-order">Start project RFQ <ArrowRight size={16}/></Link></article><article><i><UserRound/></i><span>EXISTING BUYER</span><h2>Orders and account support</h2><p>Sign in to view orders, tracking, saved addresses and available documents.</p><Link href="/account">Open buyer account <ArrowRight size={16}/></Link></article><article><i><MessagesSquare/></i><span>PRODUCT SELECTION</span><h2>Browse before you enquire</h2><p>Use focused categories to review published products, variants and prices.</p><Link href="/categories">Explore categories <ArrowRight size={16}/></Link></article></section><section className="container contactDetails"><div><span>REGISTERED COMPANY DETAILS</span><h2>{COMPANY.legalName}</h2><dl><div><dt><Building2/>Company</dt><dd>{COMPANY.legalName}</dd></div><div><dt><ReceiptText/>GSTIN</dt><dd>{COMPANY.gstin}</dd></div><div><dt><MapPin/>Registered office</dt><dd>{COMPANY.addressLine1}<br/>{COMPANY.addressLine2}<br/>{COMPANY.city}, {COMPANY.state} {COMPANY.postalCode}, {COMPANY.country}</dd></div></dl></div><aside><b>For the fastest response</b><p>Include the product name or category, required ratings, quantity, delivery PIN code and your order reference if one already exists.</p><ul><li>Custom ACDB or DCDB: attach the required BOM or use the visual builder.</li><li>Bulk products: submit one RFQ with all line items.</li><li>Order support: sign in so the request stays connected to your buyer record.</li></ul><Link href="/bulk-order">Send complete requirement <ArrowRight size={16}/></Link></aside></section></main><StoreFooter/></>}
