'use client'

import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,Check,ChevronDown,ChevronRight,Clock3,Copy,Download,KeyRound,RefreshCw,RotateCcw,Save,Search,ShieldCheck,Sparkles,UserMinus,UserPlus,Users} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import {adminRoleLabels} from '../../../lib/adminAccess'
import AdminUsersPanel from '../../../components/admin/AdminUsersPanel'

type TeamMember={user_id:string;email:string|null;full_name:string|null;role:string;admin_role:string;staff_status:string;job_title:string|null;last_sign_in_at:string|null;created_at:string}
type RoleDef={role_key:string;name:string;description:string|null;sort_order:number;is_system:boolean}
type ModuleDef={module_key:string;label:string;description:string|null;route:string|null;sort_order:number}
type Permission={role_key:string;module_key:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_delete:boolean;can_approve:boolean;can_export:boolean}
type AuditLog={id:string;actor_user_id:string|null;actor_email:string|null;action:string;module_key:string|null;entity_table:string|null;entity_id:string|null;description:string|null;before_data:any;after_data:any;metadata:any;created_at:string}
const actions=[['can_view','View'],['can_create','Create'],['can_edit','Edit'],['can_delete','Delete'],['can_approve','Approve'],['can_export','Export']] as const

function emptyPermission(roleKey:string,moduleKey:string):Permission{return {role_key:roleKey,module_key:moduleKey,can_view:false,can_create:false,can_edit:false,can_delete:false,can_approve:false,can_export:false}}

function fmtDate(v?:string|null){if(!v)return'—';return new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
function initials(m:TeamMember){return (m.full_name||m.email||'U').trim().slice(0,1).toUpperCase()}
function statusClass(s:string){return s==='active'?'good':s==='suspended'?'warn':'muted'}
function downloadCsv(rows:any[],name:string){if(!rows.length)return;const headers=Object.keys(rows[0]);const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[headers.join(','),...rows.map(r=>headers.map(h=>esc(r[h])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function AccessAdminPage(){
 const [tab,setTab]=useState<'team'|'users'|'roles'|'audit'>('team'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [team,setTeam]=useState<TeamMember[]>([]),[roles,setRoles]=useState<RoleDef[]>([]),[modules,setModules]=useState<ModuleDef[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[savedPermissions,setSavedPermissions]=useState<Permission[]>([]),[audit,setAudit]=useState<AuditLog[]>([])
 const [selectedRole,setSelectedRole]=useState('sales'),[copyRole,setCopyRole]=useState('general'),[roleDirty,setRoleDirty]=useState(false),[roleBusy,setRoleBusy]=useState(false),[auditSearch,setAuditSearch]=useState(''),[auditModule,setAuditModule]=useState('all'),[auditAction,setAuditAction]=useState('all'),[expandedAudit,setExpandedAudit]=useState<string|null>(null)
 const [promote,setPromote]=useState({email:'',admin_role:'sales',job_title:''})
 const [manual,setManual]=useState({full_name:'',email:'',phone:'',admin_role:'sales',job_title:'',temporary_password:''})
 const [createdCredential,setCreatedCredential]=useState<{email:string;password:string}|null>(null)
 const [editing,setEditing]=useState<Record<string,{admin_role:string;staff_status:string;job_title:string}>>({})
 const [customRole,setCustomRole]=useState({name:'',role_key:'',description:'',copy_from:'general'})
 const specialistRoles=roles.filter(role=>role.role_key!=='admin').map(role=>role.role_key)
 const roleName=(key:string)=>roles.find(role=>role.role_key===key)?.name||adminRoleLabels[key]||key
 for(const role of roles)adminRoleLabels[role.role_key]=role.name

 async function load(){setLoading(true);setMessage('');const [teamRes,rolesRes,modulesRes,permRes,auditRes]=await Promise.all([
   supabase.rpc('admin_list_team'),
   supabase.from('admin_role_definitions').select('*').order('sort_order'),
   supabase.from('admin_modules').select('*').order('sort_order'),
   supabase.from('admin_role_permissions').select('role_key,module_key,can_view,can_create,can_edit,can_delete,can_approve,can_export'),
   supabase.from('admin_audit_logs').select('*').order('created_at',{ascending:false}).limit(250)
 ]);setLoading(false)
 const err=teamRes.error||rolesRes.error||modulesRes.error||permRes.error||auditRes.error;if(err){setMessage(err.message);return}
 const loadedPermissions=(permRes.data||[]) as Permission[]
 setTeam((teamRes.data||[]) as TeamMember[]);setRoles((rolesRes.data||[]) as RoleDef[]);setModules((modulesRes.data||[]) as ModuleDef[]);setPermissions(loadedPermissions);setSavedPermissions(loadedPermissions);setRoleDirty(false);setAudit((auditRes.data||[]) as AuditLog[])
 const edit:Record<string,{admin_role:string;staff_status:string;job_title:string}>={};for(const m of (teamRes.data||[]) as TeamMember[])edit[m.user_id]={admin_role:m.admin_role||'general',staff_status:m.staff_status||'active',job_title:m.job_title||''};setEditing(edit)
 }
 useEffect(()=>{load()},[])

 const activeStaff=team.filter(x=>x.role==='staff'&&x.staff_status==='active').length
 const audit24=audit.filter(x=>Date.now()-new Date(x.created_at).getTime()<86400000).length
 const selectedRoleDef=roles.find(r=>r.role_key===selectedRole)
 const matrix=useMemo(()=>modules.map(m=>({module:m,permission:permissions.find(p=>p.role_key===selectedRole&&p.module_key===m.module_key)})),[modules,permissions,selectedRole])
 const roleMetrics=useMemo(()=>{const rows=matrix.filter(row=>row.module.module_key!=='staff_directory');const allowed=(key:(typeof actions)[number][0])=>selectedRole==='admin'?rows.length:rows.filter(row=>Boolean(row.permission?.[key])).length;return {modules:rows.length,view:allowed('can_view'),change:rows.filter(row=>selectedRole==='admin'||Boolean(row.permission?.can_create||row.permission?.can_edit)).length,approve:allowed('can_approve'),delete:allowed('can_delete')}},[matrix,selectedRole])
 const filteredAudit=useMemo(()=>{const q=auditSearch.trim().toLowerCase();return audit.filter(a=>(auditModule==='all'||a.module_key===auditModule)&&(auditAction==='all'||a.action===auditAction)&&(!q||`${a.actor_email||''} ${a.description||''} ${a.entity_table||''} ${a.entity_id||''}`.toLowerCase().includes(q)))},[audit,auditSearch,auditModule,auditAction])

 async function promoteAccount(){if(!promote.email.trim())return;setBusy(true);setMessage('');const {error}=await supabase.rpc('admin_promote_by_email',{p_email:promote.email.trim(),p_admin_role:promote.admin_role,p_job_title:promote.job_title.trim()||null});setBusy(false);if(error){setMessage(error.message);return}setMessage('Staff access granted. Permissions are effective immediately.');setPromote({email:'',admin_role:'sales',job_title:''});await load()}
 function generatePassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789',symbols='!@#$%&*',bytes=crypto.getRandomValues(new Uint8Array(15));const pieces=['A','a','7','#'];for(let i=0;i<10;i++)pieces.push(chars[bytes[i]%chars.length]);pieces.push(symbols[bytes[10]%symbols.length]);for(let i=pieces.length-1;i>0;i--){const j=bytes[(i+1)%bytes.length]%(i+1);[pieces[i],pieces[j]]=[pieces[j],pieces[i]]}setManual(v=>({...v,temporary_password:pieces.join('')}))}
 async function createManualUser(){setBusy(true);setMessage('');setCreatedCredential(null);const {data}=await supabase.auth.getSession();const token=data.session?.access_token||'',password=manual.temporary_password;const r=await fetch('/api/admin/team-users',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(manual)});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMessage(j.error||'Could not create the team user.');return}setCreatedCredential({email:manual.email.trim().toLowerCase(),password});setManual({full_name:'',email:'',phone:'',admin_role:'sales',job_title:'',temporary_password:''});await load();setMessage('Team user created. Copy the one-time login details and share them securely.')}
 async function saveMember(m:TeamMember){const e=editing[m.user_id];if(!e)return;setBusy(true);setMessage('');const {error}=await supabase.rpc('admin_set_staff_access',{p_user_id:m.user_id,p_admin_role:e.admin_role,p_staff_status:e.staff_status,p_job_title:e.job_title||null});setBusy(false);if(error){setMessage(error.message);return}setMessage(`Updated ${m.full_name||m.email||'staff member'}.`);await load()}
 async function removeMember(m:TeamMember){if(!confirm(`Remove admin access for ${m.full_name||m.email}? Their account will return to customer access.`))return;setBusy(true);const {error}=await supabase.rpc('admin_remove_staff_access',{p_user_id:m.user_id});setBusy(false);if(error){setMessage(error.message);return}setMessage('Admin access removed.');await load()}
 function selectRole(roleKey:string){if(roleDirty&&!confirm('Discard unsaved permission changes?'))return;setSelectedRole(roleKey);if(copyRole===roleKey)setCopyRole(specialistRoles.find(role=>role!==roleKey)||'general');setRoleDirty(false);setPermissions(savedPermissions)}
 function togglePermission(p:Permission|undefined,moduleKey:string,key:(typeof actions)[number][0],value:boolean){if(selectedRole==='admin')return;const current=p||emptyPermission(selectedRole,moduleKey);const next={...current,[key]:value};if(key!=='can_view'&&value)next.can_view=true;if(key==='can_view'&&!value)for(const [action] of actions)next[action]=false;setPermissions(prev=>{const found=prev.some(row=>row.role_key===selectedRole&&row.module_key===moduleKey);return found?prev.map(row=>row.role_key===selectedRole&&row.module_key===moduleKey?next:row):[...prev,next]});setRoleDirty(true);setMessage('Unsaved role changes. Review the matrix, then select Save Role Access.')}
 function copyRoleAccess(){if(selectedRole==='admin'||copyRole===selectedRole)return;const source=new Map(permissions.filter(row=>row.role_key===copyRole).map(row=>[row.module_key,row]));setPermissions(prev=>{const untouched=prev.filter(row=>row.role_key!==selectedRole);const copied=modules.map(module=>{const row=source.get(module.module_key)||emptyPermission(copyRole,module.module_key);return {...row,role_key:selectedRole,module_key:module.module_key}});return [...untouched,...copied]});setRoleDirty(true);setMessage(`Copied ${roleName(copyRole)} access. Select Save Role Access to apply it.`)}
 function discardRoleChanges(){setPermissions(savedPermissions);setRoleDirty(false);setMessage('Unsaved role changes discarded.')}
 async function saveRolePermissions(){if(selectedRole==='admin'||!roleDirty)return;setRoleBusy(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();const now=new Date().toISOString();const rows=modules.map(module=>{const row=permissions.find(p=>p.role_key===selectedRole&&p.module_key===module.module_key)||emptyPermission(selectedRole,module.module_key);return {...row,updated_by:user?.id||null,updated_at:now}});const {error}=await supabase.from('admin_role_permissions').upsert(rows,{onConflict:'role_key,module_key'});setRoleBusy(false);if(error){setMessage(error.message);return}await load();setMessage(`${selectedRoleDef?.name||selectedRole} access saved across ${rows.length} modules.`)}
 async function roleRequest(method:'POST'|'PATCH'|'DELETE',body:Record<string,unknown>){setRoleBusy(true);setMessage('');const {data}=await supabase.auth.getSession();const r=await fetch('/api/admin/access-roles',{method,headers:{Authorization:`Bearer ${data.session?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));setRoleBusy(false);if(!r.ok){setMessage(result.error||'Role update failed.');return false}setMessage(result.message||'Role updated.');await load();return result}
 async function createCustomRole(){const result:any=await roleRequest('POST',customRole);if(result){setSelectedRole(result.role_key);setCustomRole({name:'',role_key:'',description:'',copy_from:'general'})}}
 async function deleteCustomRole(){if(!selectedRoleDef||selectedRoleDef.is_system||!confirm(`Delete the ${selectedRoleDef.name} role?`))return;const ok=await roleRequest('DELETE',{role_key:selectedRole});if(ok)setSelectedRole('general')}

 if(loading)return <div className="accessV2"><div className="accessLoading">Loading access control…</div></div>
 return <div className="accessV2">
  <div className="accessHead"><div><span className="adminEyebrow">SECURITY & GOVERNANCE</span><h1>Team, Roles & Audit</h1><p>Create team users, control who can see and change each operating module, and review permanent admin activity history.</p></div><button className="accessRefresh" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  {message&&<div className="accessMessage"><ShieldCheck size={16}/>{message}</div>}

  <div className="accessStats"><article><span><Users/></span><div><small>Admin Team</small><strong>{team.length}</strong><p>{activeStaff} active staff</p></div></article><article><span><KeyRound/></span><div><small>System Roles</small><strong>{roles.length}</strong><p>Action-level matrix</p></div></article><article><span><Activity/></span><div><small>Audit Events · 24h</small><strong>{audit24}</strong><p>{audit.length} loaded</p></div></article><article><span><ShieldCheck/></span><div><small>Security Mode</small><strong>RBAC</strong><p>Database enforced</p></div></article></div>

  <div className="accessTabs"><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}><UserPlus size={16}/> Add Team User</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><Users size={16}/> All Users</button><button className={tab==='roles'?'active':''} onClick={()=>setTab('roles')}><KeyRound size={16}/> Role Matrix</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}><Activity size={16}/> Audit Logs</button></div>

  {tab==='team'&&<div className="accessTeamLayout">
   <div className="accessSetupColumn">
    <section className="accessPanel accessManual"><div className="accessPanelHead"><div><h2>Create New Team User</h2><p>Create the login and assign department access in one secure step. Only the Owner Admin can use this form.</p></div><UserPlus/></div><label>Full Name<input value={manual.full_name} onChange={e=>setManual(v=>({...v,full_name:e.target.value}))} placeholder="Team member name" autoComplete="off"/></label><label>Work Email<input type="email" value={manual.email} onChange={e=>setManual(v=>({...v,email:e.target.value}))} placeholder="team@newindiasolar.com" autoComplete="off"/></label><label>Mobile Number<input type="tel" value={manual.phone} onChange={e=>setManual(v=>({...v,phone:e.target.value}))} placeholder="+919876543210" autoComplete="off"/><small className="accessHelp">Use country code. Mobile is optional; email is used for admin login.</small></label><div className="accessTwo"><label>Department Role<select value={manual.admin_role} onChange={e=>setManual(v=>({...v,admin_role:e.target.value}))}>{specialistRoles.map(r=><option key={r} value={r}>{adminRoleLabels[r]}</option>)}</select></label><label>Job Title<input value={manual.job_title} onChange={e=>setManual(v=>({...v,job_title:e.target.value}))} placeholder="Sales Executive"/></label></div><label>Temporary Password<div className="accessPasswordRow"><input type="text" value={manual.temporary_password} onChange={e=>setManual(v=>({...v,temporary_password:e.target.value}))} placeholder="Minimum 12 characters" autoComplete="new-password"/><button type="button" onClick={generatePassword}><Sparkles size={15}/> Generate</button></div><small className="accessHelp">Must include uppercase, lowercase, number and symbol. Ask the user to change it after first login.</small></label><button className="accessPrimary" onClick={createManualUser} disabled={busy||!manual.full_name.trim()||!manual.email.trim()||!manual.temporary_password}><UserPlus size={16}/>{busy?'Creating…':'Create Team User'}</button>{createdCredential&&<div className="accessCredential" role="status"><div><strong>One-time login details</strong><span>{createdCredential.email}</span></div><code>{createdCredential.password}</code><button type="button" onClick={()=>navigator.clipboard.writeText(`New India Solar admin login\nEmail: ${createdCredential.email}\nTemporary password: ${createdCredential.password}\nLogin: ${location.origin}/admin/login`)}><Copy size={14}/> Copy login details</button></div>}</section>
    <section className="accessPanel accessPromote"><div className="accessPanelHead"><div><h2>Promote Existing Account</h2><p>If the person already registered on the website, grant team access without creating a duplicate account.</p></div><ShieldCheck/></div><label>Existing Account Email<input type="email" value={promote.email} onChange={e=>setPromote(v=>({...v,email:e.target.value}))} placeholder="team@company.com"/></label><div className="accessTwo"><label>Role<select value={promote.admin_role} onChange={e=>setPromote(v=>({...v,admin_role:e.target.value}))}>{specialistRoles.map(r=><option key={r} value={r}>{adminRoleLabels[r]}</option>)}</select></label><label>Job Title<input value={promote.job_title} onChange={e=>setPromote(v=>({...v,job_title:e.target.value}))} placeholder="Sales Executive"/></label></div><button className="accessPrimary" onClick={promoteAccount} disabled={busy||!promote.email.trim()}><ShieldCheck size={16}/>{busy?'Working…':'Grant Team Access'}</button></section>
   </div>

   <section className="accessPanel accessTeam"><div className="accessPanelHead"><div><h2>Admin Team</h2><p>Role and suspension changes take effect on the next request. Suspended users immediately lose internal database permissions.</p></div></div><div className="accessTeamRows">{team.map(m=>{const edit=editing[m.user_id];const isAdmin=m.role==='admin';return <article key={m.user_id} className="accessMember"><div className="accessMemberMain"><span className="accessAvatar">{initials(m)}</span><div><h3>{m.full_name||'Unnamed account'} {isAdmin&&<em>Owner Admin</em>}</h3><p>{m.email||'No email'}</p><div className="accessMemberMeta"><span className={statusClass(m.staff_status)}>{m.staff_status}</span><span>{adminRoleLabels[m.admin_role]||m.admin_role}</span>{m.job_title&&<span>{m.job_title}</span>}<span>Last sign-in {fmtDate(m.last_sign_in_at)}</span></div></div></div>{isAdmin?<div className="accessAdminLock"><ShieldCheck size={16}/> Full access protected</div>:edit&&<div className="accessMemberEdit"><select value={edit.admin_role} onChange={e=>setEditing(v=>({...v,[m.user_id]:{...edit,admin_role:e.target.value}}))}>{specialistRoles.map(r=><option key={r} value={r}>{adminRoleLabels[r]}</option>)}</select><select value={edit.staff_status} onChange={e=>setEditing(v=>({...v,[m.user_id]:{...edit,staff_status:e.target.value}}))}><option value="active">Active</option><option value="suspended">Suspended</option><option value="inactive">Inactive</option></select><input value={edit.job_title} onChange={e=>setEditing(v=>({...v,[m.user_id]:{...edit,job_title:e.target.value}}))} placeholder="Job title"/><button onClick={()=>saveMember(m)} disabled={busy}><Check size={15}/> Save</button><button className="danger" onClick={()=>removeMember(m)} disabled={busy}><UserMinus size={15}/></button></div>}</article>})}</div></section>
  </div>}

  {tab==='users'&&<AdminUsersPanel/>}

  {tab==='roles'&&<section className="accessPanel accessPromote"><div className="accessPanelHead"><div><h2>Create Custom Role</h2><p>Build a reusable job role from an existing permission set, then refine it in the matrix.</p></div><UserPlus/></div><div className="accessTwo"><label>Role Name<input value={customRole.name} onChange={e=>setCustomRole(v=>({...v,name:e.target.value,role_key:v.role_key||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}))} placeholder="Regional Sales"/></label><label>Role Key<input value={customRole.role_key} onChange={e=>setCustomRole(v=>({...v,role_key:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,'')}))} placeholder="regional_sales"/></label><label>Copy Access From<select value={customRole.copy_from} onChange={e=>setCustomRole(v=>({...v,copy_from:e.target.value}))}>{roles.filter(r=>r.role_key!=='admin').map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select></label><label>Description<input value={customRole.description} onChange={e=>setCustomRole(v=>({...v,description:e.target.value}))} placeholder="What this role is responsible for"/></label></div><button className="accessPrimary" onClick={createCustomRole} disabled={roleBusy||!customRole.name.trim()}><UserPlus size={15}/> Create Role</button>{selectedRoleDef&&!selectedRoleDef.is_system&&<button className="danger" onClick={deleteCustomRole} disabled={roleBusy}><UserMinus size={15}/> Delete Selected Custom Role</button>}</section>}

  {tab==='roles'&&<section className="accessPanel accessRoles"><div className="accessPanelHead"><div><h2>Module × Action Permission Matrix</h2><p>Changes are staged locally and applied only when you select Save Role Access. Enabling any action also enables View; removing View removes every action for that module.</p></div></div><div className="accessRoleChips">{roles.map(r=><button key={r.role_key} className={selectedRole===r.role_key?'active':''} onClick={()=>selectRole(r.role_key)}>{r.name}</button>)}</div>{selectedRoleDef&&<div className="accessRoleDesc"><ShieldCheck size={18}/><div><b>{selectedRoleDef.name}</b><span>{selectedRoleDef.description}</span></div></div>}<div className="roleMetricCards"><article><small>Visible Modules</small><b>{roleMetrics.view}/{roleMetrics.modules}</b></article><article><small>Create / Edit</small><b>{roleMetrics.change}</b></article><article><small>Approval Access</small><b>{roleMetrics.approve}</b></article><article><small>Delete Access</small><b>{roleMetrics.delete}</b></article></div>{selectedRole!=='admin'&&<div className="accessRoleToolbar"><div><label>Copy access from<select value={copyRole} onChange={e=>setCopyRole(e.target.value)}>{roles.filter(r=>r.role_key!=='admin'&&r.role_key!==selectedRole).map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select></label><button type="button" onClick={copyRoleAccess} disabled={roleBusy}><Copy size={15}/> Copy</button></div><span className={roleDirty?'dirty':'saved'}>{roleDirty?'Unsaved changes':'All changes saved'}</span><button type="button" onClick={discardRoleChanges} disabled={!roleDirty||roleBusy}><RotateCcw size={15}/> Discard</button><button className="accessPrimary" type="button" onClick={saveRolePermissions} disabled={!roleDirty||roleBusy}><Save size={15}/>{roleBusy?'Saving…':'Save Role Access'}</button></div>}<div className="accessMatrixWrap"><table className="accessMatrix"><thead><tr><th>Module</th>{actions.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{matrix.filter(x=>x.module.module_key!=='staff_directory').map(({module,permission})=><tr key={module.module_key} className={!permission?'missingPermission':''}><td><b>{module.label}</b><small>{module.description}</small></td>{actions.map(([key,label])=><td key={key}><label className={`accessToggle ${selectedRole==='admin'?'locked':''}`} title={`${label} ${module.label}`}><input type="checkbox" checked={selectedRole==='admin'||Boolean(permission?.[key])} disabled={selectedRole==='admin'||roleBusy} onChange={e=>togglePermission(permission,module.module_key,key,e.target.checked)}/><span/></label></td>)}</tr>)}</tbody></table></div><div className="accessSecurityNote"><AlertTriangle size={17}/><span><b>Delete is intentionally off for specialist roles by default.</b> Enable it only where operationally necessary. Approval is separate from Edit so high-risk workflows can be delegated without granting full control.</span></div></section>}

  {tab==='audit'&&<section className="accessPanel accessAudit"><div className="accessPanelHead"><div><h2>Permanent Admin Activity</h2><p>Tracks internal inserts, updates, deletes, access sessions, role changes and critical operational records. Customer storefront activity is not recorded here.</p></div><button onClick={()=>downloadCsv(filteredAudit.map(a=>({date:a.created_at,actor:a.actor_email,action:a.action,module:a.module_key,table:a.entity_table,entity:a.entity_id,description:a.description})),'new-india-solar-admin-audit.csv')}><Download size={15}/> Export CSV</button></div><div className="accessFilters"><label><Search size={16}/><input value={auditSearch} onChange={e=>setAuditSearch(e.target.value)} placeholder="Search actor, table, ID…"/></label><select value={auditModule} onChange={e=>setAuditModule(e.target.value)}><option value="all">All modules</option>{modules.filter(m=>m.module_key!=='staff_directory').map(m=><option key={m.module_key} value={m.module_key}>{m.label}</option>)}</select><select value={auditAction} onChange={e=>setAuditAction(e.target.value)}><option value="all">All actions</option><option value="insert">Insert</option><option value="update">Update</option><option value="delete">Delete</option><option value="session_start">Session start</option></select></div><div className="accessAuditRows">{filteredAudit.length?filteredAudit.map(a=><article key={a.id} className="accessAuditRow"><button onClick={()=>setExpandedAudit(expandedAudit===a.id?null:a.id)}><span className={`accessAction ${a.action}`}>{a.action.replace('_',' ')}</span><div><b>{a.description||`${a.action} ${a.entity_table||''}`}</b><small>{a.actor_email||'System'} · {a.module_key||'system'} {a.entity_id?`· ${a.entity_id.slice(0,12)}`:''}</small></div><time><Clock3 size={14}/>{fmtDate(a.created_at)}</time>{expandedAudit===a.id?<ChevronDown size={16}/>:<ChevronRight size={16}/>}</button>{expandedAudit===a.id&&<div className="accessAuditDetail"><div><b>Before</b><pre>{a.before_data?JSON.stringify(a.before_data,null,2):'—'}</pre></div><div><b>After / Metadata</b><pre>{a.after_data?JSON.stringify(a.after_data,null,2):a.metadata?JSON.stringify(a.metadata,null,2):'—'}</pre></div></div>}</article>):<div className="accessEmpty">No audit events match these filters.</div>}</div></section>}
 </div>
}
