import '../admin-shell-v2.css'
import '../admin-dashboard-v2.css'
import '../orders-v2.css'
import '../admin-catalogue-v2.css'
import '../inventory-v2.css'
import '../production-v2.css'
import '../rfq-v2.css'
import '../customers-v2.css'
import '../procurement-v2.css'
import '../pricing-v2.css'
import '../finance-v2.css'
import '../accounting-v2.css'
import '../reports-v2.css'
import '../cms-v2.css'
import '../access-v2.css'
import '../notifications-v2.css'
import '../workflows-v2.css'
import '../global-search-v2.css'
import '../manufacturing-v2.css'
import '../product-cost-v2.css'
import '../admin-panel-v3.css'
import AdminGuard from '../../components/admin/AdminGuard'
import AdminShell from '../../components/admin/AdminShell'
export default function AdminLayout({children}:{children:React.ReactNode}){return <AdminGuard><AdminShell>{children}</AdminShell></AdminGuard>}
