const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript')
const root=path.resolve(__dirname,'..'),cache={}
function load(name){const file=path.resolve(root,'lib',name.endsWith('.ts')?name:name+'.ts');if(cache[file])return cache[file];const scope={exports:{},URL,Date,Set,Map,Blob,require:p=>p.endsWith('.json')?JSON.parse(fs.readFileSync(path.resolve(path.dirname(file),p),'utf8')):load(path.basename(p))};cache[file]=scope.exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,scope);return scope.exports}

const lib=load('builder-buyer'),catalogue=load('builder-catalogue'),combo=load('combo-catalogue')
function client(tables){return {from(table){let predicates=[];const query={select(){return query},eq(key,value){predicates.push(row=>row[key]===value);return query},in(key,list){predicates.push(row=>list.includes(row[key]));return query},order(){return query},abortSignal(){return query},maybeSingle(){return Promise.resolve({data:(tables[table]||[]).filter(row=>predicates.every(p=>p(row)))[0]||null})},then(resolve){return Promise.resolve({data:(tables[table]||[]).filter(row=>predicates.every(p=>p(row)))}).then(resolve)}};return query}}}
function tables(){const d=lib.uploadedCatalog('ACDB');return {configurator_templates:[{...d.template,slug:'custom-acdb',type:'acdb',is_active:true,preview_settings:{asset_pack:'legacy'}}],configurator_options:d.groups.map(g=>({...g,template_id:d.template.id,configurator_option_values:g.configurator_option_values.map(v=>({...v,is_active:true,metadata:{...v.metadata,asset_pack:undefined}}))})),components:Object.values(d.components).map(c=>({...c,is_active:true})),enclosures:Object.values(d.enclosures).map(e=>({...e,is_active:true,supported_types:['acdb']})),configurator_visual_slots:d.slots.map(s=>({...s,template_id:d.template.id,is_active:true})),configurator_component_compatibility:[]}}
test('unpublished admin template never silently becomes bundled sample catalogue',async()=>{const t=tables();t.configurator_templates[0].is_active=false;await assert.rejects(catalogue.loadBuilderCatalogue(client(t),'custom-acdb',null),/not published/);assert.ok(await catalogue.loadBuilderCatalogue(client(t),'custom-acdb',null,true))})
test('admin-created options without asset-pack metadata appear to buyers',async()=>{const d=await catalogue.loadBuilderCatalogue(client(tables()),'custom-acdb',null);assert.ok(d.groups.find(g=>g.option_key==='spd').configurator_option_values.length>1);assert.equal(lib.selectionIssues(d,lib.defaults(d),'ACDB').length,0)})
test('disabled assets and options are removed and empty required selections are reported',async()=>{const t=tables(),g=t.configurator_options.find(g=>g.option_key==='spd');g.configurator_option_values.forEach(v=>v.is_active=false);const d=await catalogue.loadBuilderCatalogue(client(t),'custom-acdb',null);assert.ok(lib.selectionIssues(d,lib.defaults(d),'ACDB').some(x=>x.includes('Choose')))})
test('refresh retains buyer edits but removes choices withdrawn by admin',()=>{const d=lib.uploadedCatalog('ACDB'),s=lib.defaults(d),group=d.groups.find(g=>g.option_key==='spd');s.spd=[{id:group.configurator_option_values[1].id,qty:1}];assert.equal(catalogue.reconcileSelection(d,s).spd[0].id,s.spd[0].id);group.configurator_option_values=[];assert.equal(catalogue.reconcileSelection(d,s).spd.length,0)})
test('nonvisual rating choices are valid and do not need component images',()=>{const d=lib.uploadedCatalog('ACDB');d.groups.push({id:'rating',option_key:'rating',label:'Rating',required:true,option_type:'single',configurator_option_values:[{id:'rating-value',label:'32 A',metadata:{default:true}}]});assert.equal(lib.selectionIssues(d,lib.defaults(d),'ACDB').length,0)})
test('admin deny and quantity rules block buyer selections including slot-scoped rules',()=>{const d=lib.uploadedCatalog('ACDB'),s=lib.defaults(d),v=lib.indexValues(d)[s.spd[0].id];for(const rule of [{allowed:false},{allowed:true,min_qty:2,max_qty:3},{allowed:false,slot_key:d.slots.find(x=>x.option_key==='spd').slot_key}]){d.rules=[{component_id:v.component_id,option_key:'spd',...rule}];assert.ok(lib.selectionIssues(d,s,'ACDB').some(x=>x.includes('compatibility')))}d.rules=[{component_id:v.component_id,enclosure_id:'another-enclosure',allowed:false}];assert.equal(lib.selectionIssues(d,s,'ACDB').length,0)})
const product={id:'ac',name:'ACDB',slug:'acdb',status:'active',product_type:'standard',specifications:{},min_order_qty:1,gst_rate:18,product_variants:[{id:'v',is_active:true,selling_price:100,stock_qty:5}]}
test('admin combo exclusion and explicit side override are shared with buyer choices',()=>{assert.equal(combo.choices([product],'acdb').length,1);assert.equal(combo.choices([{...product,specifications:{combo_enabled:false}}],'acdb').length,0);assert.equal(combo.choices([{...product,specifications:{combo_side:'dcdb'}}],'dcdb').length,1)})
test('combo respects stock, GST, active variants and standard product type',()=>{for(const p of [{...product,gst_rate:null},{...product,product_type:'custom'},{...product,product_variants:[{...product.product_variants[0],stock_qty:0}]},{...product,product_variants:[{...product.product_variants[0],is_active:false}]}])assert.equal(combo.choices([p],'acdb').length,0)})
