const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript')
const root=path.resolve(__dirname,'..'),cache={}
function load(name){const file=path.resolve(root,'lib',name.endsWith('.ts')?name:name+'.ts');if(cache[file])return cache[file];const scope={exports:{},URL,Date,Set,Map,Blob,require:p=>p.endsWith('.json')?JSON.parse(fs.readFileSync(path.resolve(path.dirname(file),p),'utf8')):load(path.basename(p))};cache[file]=scope.exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,scope);return scope.exports}
const lib=load('builder-buyer'),visual=load('configurator-visuals')
for(const code of ['ACDB','DCDB']){
 const d=lib.uploadedCatalog(code),v=lib.indexValues(d),spd=d.groups.find(g=>g.option_key==='spd'),mcb=d.groups.find(g=>['protection','dc_mcb'].includes(g.option_key))
 for(const s of spd.configurator_option_values)for(const m of mcb.configurator_option_values)test(`${code}: ${s.label} / ${m.label}: complete aligned visual`,()=>{const picks=lib.defaults(d);picks.spd=[{id:s.id,qty:1}];picks[mcb.option_key]=[{id:m.id,qty:1}];assert.equal(lib.selectionIssues(d,picks,code).length,0);const layers=lib.previewLayers(d,picks);assert.equal(layers.length,11);assert.equal(new Set(layers.map(l=>l.slot.id)).size,11);for(const l of layers){for(const n of ['x_pct','y_pct','width_pct','height_pct'])assert.ok(Number.isFinite(l.slot[n]));assert.ok(l.slot.x_pct>=0&&l.slot.y_pct>=0&&l.slot.x_pct+l.slot.width_pct<=100&&l.slot.y_pct+l.slot.height_pct<=100)}const left=layers.find(l=>l.component.visual_role==='spd'),centre=layers.find(l=>l.component.visual_role==='mcb'),right=layers.find(l=>l.component.visual_role==='terminal');assert.ok(left.slot.x_pct+left.slot.width_pct<centre.slot.x_pct);assert.ok(centre.slot.x_pct+centre.slot.width_pct<right.slot.x_pct);assert.equal(centre.slot.settings.fit,'contain-top')})
 for(const ref of lib.references(code))test(`${code} uploaded reference ${ref.id}: exact asset mapping`,()=>{const p=lib.presetSelection(d,code,ref.id);assert.ok(p);assert.equal(lib.selectionIssues(d,p,code).length,0);const ids=lib.previewLayers(d,p).map(l=>l.component.visual_settings.asset_id);assert.ok(ids.includes(ref.spd));assert.ok(ids.includes(ref.mcb))})
 test(`${code}: saved draft and BOM keep all chosen component identifiers`,()=>{const p=lib.defaults(d),raw=JSON.stringify({version:2,code,selection:p,savedAt:Date.now(),reference:'01'});assert.ok(lib.readDraft(raw,d,code));assert.ok(lib.summary(d,p,code).includes('Asset:'));assert.equal(lib.readDraft(raw,d,code==='ACDB'?'DCDB':'ACDB'),null)})
 test(`${code}: over-capacity and unmapped selections fail visibly`,()=>{const p=lib.defaults(d);p.cable_gland[0].qty=3;assert.ok(lib.selectionIssues(d,p,code).length);p.cable_gland[0].qty=2;const broken={...d,slots:d.slots.filter(s=>s.slot_key!=='nis_v1_glandRight')};assert.ok(lib.selectionIssues(broken,p,code).some(x=>x.includes('insufficient mapped')))})
}
test('AC14 uses new AC components and 07/16 retain their existing references',()=>{assert.equal(lib.references('ACDB').length,21);const ref=lib.references('ACDB').find(r=>r.id==='14');assert.equal(ref.spd,'ac-spd-orbit');assert.equal(ref.mcb,'ac-mcb-empower-c20a');const a=lib.references('ACDB').find(x=>x.id==='07'),b=lib.references('ACDB').find(x=>x.id==='16');assert.equal(a.spd,b.spd);assert.equal(a.mcb,b.mcb)})
test('SVG and PNG top alignment uses the same undistorted rectangle',()=>{const r=visual.fitRectangle([0,0,633,1194],[477,487,225,435],'contain-top');assert.equal(r[1],487);assert.ok(Math.abs(r[2]/r[3]-633/1194)<1e-8)})
test('unsafe asset URL schemes and credential URLs are rejected',()=>{for(const s of ['javascript:a','//evil.com','/\\evil.com','https://user:pass@evil.com/image','https://example.com/a b'])assert.equal(visual.safeImageSource(s),false);assert.equal(visual.safeImageSource('/configurator/a.png'),true)})
test('expired and corrupt drafts are not restored',()=>{const d=lib.uploadedCatalog('ACDB');for(const raw of ['{}','bad',JSON.stringify({version:2,code:'ACDB',selection:lib.defaults(d),savedAt:Date.now()-31*86400000})])assert.equal(lib.readDraft(raw,d,'ACDB'),null)})

test('DC21 uses the photographed WinSurge and Siemens DC components',()=>{const ref=lib.references('DCDB').find(r=>r.id==='21');assert.equal(ref.spd,'dc-spd-winsurge');assert.equal(ref.mcb,'dc-mcb-siemens-32a')})

for(const code of ['ACDB','DCDB'])test(`${code}: all 21 catalogue numbers are present exactly once`,()=>{assert.deepEqual(Array.from(lib.references(code),r=>r.id),Array.from({length:21},(_,i)=>String(i+1).padStart(2,'0')))})
for(const [id,spd,mcb] of [['17','finder','lauritz-knudsen-c32'],['18','sighter','empower-c32a'],['19','schutz','lauritz-knudsen-c32'],['20','winsurge','empower-c32a'],['21','winsurge','siemens-32a']])test(`DCDB-${id}: catalogue components survive preview, BOM and saved draft`,()=>{
 const d=lib.uploadedCatalog('DCDB'),p=lib.presetSelection(d,'DCDB',id),layers=lib.previewLayers(d,p),ids=layers.map(l=>l.component.visual_settings.asset_id)
 assert.ok(ids.includes('dc-spd-'+spd));assert.ok(ids.includes('dc-mcb-'+mcb));assert.ok(ids.every(x=>!x.startsWith('ac-')));assert.equal(layers.length,11)
 const bom=lib.summary(d,p,'DCDB',id);assert.ok(bom.includes('DCDB-'+id));assert.ok(bom.includes('dc-spd-'+spd));assert.ok(bom.includes('dc-mcb-'+mcb))
 const restored=lib.readDraft(JSON.stringify({version:2,code:'DCDB',selection:p,reference:id,savedAt:Date.now()}),d,'DCDB');assert.equal(restored.reference,id)
})
test('AC01 and AC11 match the listed ORBIT AC SPD',()=>{for(const id of ['01','11'])assert.equal(lib.references('ACDB').find(r=>r.id===id).spd,'ac-spd-orbit')})
