const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript')
const cache={};function load(name){const file=path.resolve(__dirname,'../lib',name+'.ts');if(cache[file])return cache[file];const scope={exports:{},URL,Date,Set,Map,AbortSignal,require:p=>p.endsWith('.json')?require(path.resolve('lib',p)):p.startsWith('.')?load(path.basename(p)):require(p)};cache[file]=scope.exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,scope);return scope.exports}
const lib=load('pdf-catalogues'),engine=load('catalogue-pdf')
const cats=[{id:'a',slug:'acdb',name:'ACDB',parent_id:null,is_active:true},{id:'b',slug:'single',name:'Single phase',parent_id:'a',is_active:true},{id:'c',slug:'dcdb',name:'DCDB',parent_id:null,is_active:true}]
const product=(id,category='a')=>({id,name:'Product '+id,slug:'product-'+id,status:'active',category_id:category,categories:{name:category,is_active:true},short_description:'Solar product',gst_rate:18,specifications:{voltage:'600V',cost_price:'PRIVATE-COST'},product_images:[],product_variants:[{id:'v'+id,sku:'SKU-'+id,title:'Standard',selling_price:100,is_active:true,unit:'pcs'}]})
test('full catalogue excludes unpublished, hidden category and inactive variants',()=>{const p=[product('1'),{...product('2'),status:'draft'},{...product('3'),categories:{is_active:false}},{...product('4'),product_variants:[{is_active:false}]}];assert.deepEqual(Array.from(lib.catalogueProducts(lib.emptyCatalogue(),p,cats),p=>p.id),['1'])})
test('category catalogue includes descendants and newly listed products',()=>{const c={...lib.emptyCatalogue(),scope:'categories',category_ids:['a']};assert.equal(lib.catalogueProducts(c,[product('1'),product('2','b'),product('3','c')],cats).length,2);assert.equal(lib.catalogueProducts(c,[product('4','b')],cats).length,1)})
test('selected-product catalogue excludes unrelated products',()=>{assert.deepEqual(Array.from(lib.catalogueProducts({...lib.emptyCatalogue(),scope:'products',product_ids:['2']},[product('1'),product('2')],cats),p=>p.id),['2'])})
test('empty category and product scopes are rejected',()=>{for(const scope of ['categories','products'])assert.ok(lib.validateCatalogue({...lib.emptyCatalogue(),title:'Test',scope}));assert.equal(lib.validateCatalogue({...lib.emptyCatalogue(),title:'All'}),'')})
function clientFor(pages,counts){let n=0;return {from:()=>({select(){return this},eq(){return this},order(){return this},range(){return this},abortSignal(){return Promise.resolve({data:pages[n],count:counts[n++],error:null})}})}}
test('pagination reads beyond a single API page',async()=>{const rows=await lib.readCatalogueRows(clientFor([[{id:'1'}],[{id:'2'}]],[2,2]),'products',new AbortController().signal);assert.equal(rows.length,2)})
test('pagination rejects incomplete and duplicate responses',async()=>{await assert.rejects(lib.readCatalogueRows(clientFor([[{id:'1'}],[]],[2,2]),'products',new AbortController().signal),/Incomplete/);await assert.rejects(lib.readCatalogueRows(clientFor([[{id:'1'}],[{id:'1'}]],[2,2]),'products',new AbortController().signal),/changed/)})
test('public projection has no internal costs or wildcard fields',()=>{assert.ok(!lib.PDF_PRODUCT_SELECT.includes('*'));assert.ok(!/cost_price|margin|purchase|supplier/i.test(lib.PDF_PRODUCT_SELECT))})
test('PDF generates multipage document with prices, all variants and safe links',async()=>{const p=product('1');p.product_variants=Array.from({length:60},(_,i)=>({...p.product_variants[0],sku:'SKU-'+i}));const {pdf,missing}=await engine.buildCataloguePdf({...lib.emptyCatalogue(),title:'Solar Catalogue',show_prices:true},[p],async()=>null);const data=pdf.output();assert.ok(data.startsWith('%PDF-'));assert.ok(pdf.getNumberOfPages()>2);assert.equal(missing,1);assert.ok(!data.includes('PRIVATE-COST'));assert.ok(data.includes('/URI (https://newindiasolar.com/product/product-1)'));})
test('empty catalogue cannot generate an empty PDF',async()=>{await assert.rejects(engine.buildCataloguePdf(lib.emptyCatalogue(),[],async()=>null),/No published/)})

test('buyer selection layout fits four products on each page',async()=>{for(const [count,pages]of [[4,1],[5,2],[8,2]]){const items=Array.from({length:count},(_,i)=>product(String(i)));const result=await engine.buildCataloguePdf({...lib.emptyCatalogue(),title:'Buyer Catalogue'},items,async()=>null);assert.equal(result.pdf.getNumberOfPages(),pages)}})
