const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),{PGlite}=require('@electric-sql/pglite')
test('catalogue RLS isolates drafts and enforces content permissions on every write',async()=>{
 const db=new PGlite();await db.exec(`create role anon; create role authenticated; create table categories(id uuid default gen_random_uuid(),name text,slug text,is_active boolean); create function has_admin_permission(text,text) returns boolean language sql as $$select current_setting('test.permission',true) = $2 or current_setting('test.permission',true) = 'all'$$;`)
 await db.exec(fs.readFileSync('supabase/migrations/20260925190722_dynamic_product_catalogues.sql','utf8'))
 await db.exec("insert into product_catalogues(title,is_published) values ('Published',true); set role anon;")
 assert.equal((await db.query('select * from product_catalogues')).rows.length,1)
 await assert.rejects(db.exec("insert into product_catalogues(title) values ('Forbidden')"))
 await db.exec("reset role; set role authenticated; set test.permission='none';")
 assert.equal((await db.query('select * from product_catalogues')).rows.length,1)
 await assert.rejects(db.exec("insert into product_catalogues(title) values ('Forbidden')"))
 assert.equal((await db.query("update product_catalogues set title='No' returning id")).rows.length,0)
 assert.equal((await db.query('delete from product_catalogues returning id')).rows.length,0)
 await db.exec("set test.permission='all';")
 const {rows}=await db.query("insert into product_catalogues(title) values ('New draft') returning id");const id=rows[0].id
 assert.equal((await db.query('select * from product_catalogues')).rows.length,3)
 await db.query('update product_catalogues set is_published=true where id=$1',[id])
 await db.exec("set test.permission='none';")
 assert.equal((await db.query('select * from product_catalogues')).rows.length,2)
 await db.exec("set test.permission='all';")
 await db.query('update product_catalogues set is_published=false where id=$1',[id])
 await db.exec("set test.permission='none';")
 assert.equal((await db.query('select * from product_catalogues')).rows.length,1)
 await db.exec("set test.permission='all';")
 await assert.rejects(db.exec("insert into product_catalogues(title,scope) values ('Empty','products')"))
 await db.query('delete from product_catalogues where id=$1',[id]);await db.close()
})
