import test from 'node:test'
import assert from 'node:assert/strict'
import {checkPurchase,linePrice,quantityError,quantityStep,minimum,specEntries,strings,productEnquiry,mergeCart,readCart,cartAmounts,PUBLIC_PRODUCT_SELECT} from '../lib/buyer-commerce.ts'
const v=(patch={})=>({id:'v1',sku:'MCB32',title:'32A',selling_price:'99.99',stock_qty:10,unit:'pcs',is_active:true,attributes:{},...patch})
const p=(patch={})=>({id:'p1',name:'MCB',slug:'mcb-32',status:'active',product_type:'standard',gst_rate:18,min_order_qty:1,product_variants:[v()],...patch})
const item=(patch={})=>({id:'v1',kind:'standard',name:'MCB',variant:'32A',productVariantId:'v1',price:100,gstRate:18,qty:1,...patch})
test('zero GST survives product and cart calculations',()=>{assert.equal(linePrice(100,0,2).total,200);assert.equal(cartAmounts([item({gstRate:0})]).tax,0)})
test('unknown GST never turns into eighteen',()=>{assert.equal(linePrice(100,null,1),null);assert.equal(cartAmounts([item({gstRate:undefined})]).total,null)})
test('line totals are rounded on the selected quantity',()=>assert.deepEqual(linePrice('99.99',18,3),{unit:99.99,quantity:3,rate:18,base:299.97,tax:53.99,total:353.96}))
test('quote-only and corrupt prices do not allow purchase',()=>{for(const price of [0,-1,null,'',NaN,Infinity])assert.equal(checkPurchase(p({product_variants:[v({selling_price:price})]}),'v1',1).ok,false)})
test('only the requested active variant may be bought',()=>{assert.equal(checkPurchase(p(),'missing',1).ok,false);assert.equal(checkPurchase(p({product_variants:[v({is_active:false})]}),'v1',1).ok,false)})
test('inactive product and custom product cannot be added as standard',()=>{assert.equal(checkPurchase(p({status:'draft'}),'v1',1).ok,false);assert.equal(checkPurchase(p({product_type:'custom'}),'v1',1).ok,false)})
test('MOQ is respected instead of resetting every option to one',()=>{assert.equal(minimum(p({min_order_qty:5})),5);assert.match(quantityError(1,p({min_order_qty:5}),v()),/Minimum/)})
test('MOQ is not falsely treated as a pack multiple',()=>assert.equal(quantityError(6,p({min_order_qty:5}),v()),null))
test('piece products reject fractional quantities',()=>assert.match(quantityError(1.5,p(),v()),/increments/))
test('cable supports a published measured unit',()=>{assert.equal(quantityStep(v({unit:'m'})),.01);assert.equal(quantityError(1.25,p(),v({unit:'m'})),null)})
test('explicit published step overrides unit default',()=>{assert.equal(quantityStep(v({attributes:{quantity_step:.5}})),.5);assert.match(quantityError(1.25,p(),v({attributes:{quantity_step:.5}})),/increments/)})
test('quantity above available stock and existing cart is blocked',()=>assert.match(quantityError(6,p(),v(),5),/stock/))
test('empty, negative, infinite and excessive quantities rejected',()=>{for(const qty of ['',0,-1,NaN,Infinity,1e10])assert.ok(quantityError(qty,p(),v()))})
test('variant attributes override matching product specification keys',()=>assert.deepEqual(specEntries({'Rated_Voltage':'600V','IP':'IP65'},{'rated voltage':'1000V','quantity_step':1}),[['rated voltage','1000V'],['IP','IP65']]))
test('no badges, applications or specifications are invented',()=>{assert.deepEqual(strings(null),[]);assert.deepEqual(strings({foo:'IP65'}),[]);assert.deepEqual(specEntries(null,null),[])})
test('RFQ link carries exact product variant and quantity',()=>{const url=new URL(productEnquiry(p(),v(),3),'https://site.test');assert.equal(url.searchParams.get('product'),'mcb-32');assert.equal(url.searchParams.get('variant'),'v1');assert.equal(url.searchParams.get('quantity'),'3')})
test('public projection never includes internal costs or wildcard selects',()=>{assert.ok(!PUBLIC_PRODUCT_SELECT.includes('*'));assert.ok(!PUBLIC_PRODUCT_SELECT.includes('cost_price'));assert.ok(!PUBLIC_PRODUCT_SELECT.includes('low_stock_threshold'))})
test('verified cart addition refreshes an existing stale price',()=>{const r=mergeCart([item({price:80})],item({price:100,qty:2}),10);assert.equal(r.ok,true);assert.equal(r.items[0].price,100);assert.equal(r.items[0].qty,3)})
test('atomic merge rejects repeated additions exceeding stock',()=>{const first=mergeCart([],item({qty:6}),10);const second=mergeCart(first.items,item({qty:6}),10);assert.equal(second.ok,false)})
test('fractional merge avoids floating point quantities',()=>{const r=mergeCart([item({qty:.1})],item({qty:.2}),1);assert.equal(r.items[0].qty,.3)})
test('storage corruption does not crash hydration',()=>{assert.deepEqual(readCart('not json'),[]);assert.deepEqual(readCart('{}'),[])})
test('valid saved custom selections are preserved on hydration',()=>{const c=item({kind:'custom',templateId:'t',visualSelections:[{value_id:'a',quantity:2}],visualPreview:{version:3,layers:[]}});assert.deepEqual(readCart(JSON.stringify([c])),[c])})
test('malformed storage entries are excluded',()=>assert.equal(readCart(JSON.stringify([item(),{id:7},{...item(),qty:-2}])).length,1))
test('mixed GST cart uses line rates, not a universal eighteen percent',()=>assert.deepEqual(cartAmounts([item({price:100,gstRate:0}),item({id:'2',price:200,gstRate:5,qty:2})]),{subtotal:500,tax:20,total:520}))
