import test from 'node:test'
import assert from 'node:assert/strict'
import {priceFor} from '../lib/catalogue.ts'
import {finite,linePrice,taxRate,minimum,quantityStep,firstQuantity,remainingQuantity,maximumQuantity,quantityError,nextQuantity,resolveVariant,checkPurchase,specEntries} from '../lib/buyer-commerce.ts'
const v=(patch={})=>({id:'a',sku:'SKU-A',title:'Option A',selling_price:'99.99',stock_qty:100,unit:'pcs',is_active:true,attributes:{},...patch})
const p=(patch={})=>({id:'p',name:'Fixture',slug:'fixture',status:'active',product_type:'standard',gst_rate:18,min_order_qty:1,product_variants:[v()],...patch})
test('only a sole active variant defaults; multiple options require a choice',()=>{assert.equal(resolveVariant([v()],'' ).id,'a');assert.equal(resolveVariant([v(),v({id:'b'})],''),null)})
test('invalid or inactive deep links never silently select an alternative',()=>{assert.equal(resolveVariant([v()],'unknown'),null);assert.equal(resolveVariant([v(),v({id:'hidden',is_active:false})],'hidden'),null)})
test('active means exactly true, not truthy text',()=>{assert.equal(resolveVariant([v({is_active:'true'})],''),null);assert.equal(resolveVariant([v({is_active:false}),v({id:'b'})],'' ).id,'b')})
test('variant-specific specifications override only matching keys',()=>assert.deepEqual(specEntries({VOLTAGE:'415V',CURRENT:'32A'},{current:'63A'}),[['VOLTAGE','415V'],['current','63A']]))
test('quantity increment metadata is not a technical product specification',()=>assert.deepEqual(specEntries({Quantity_Step:2},{'quantity step':4}),[]))
test('numeric inputs reject object, array, bool, hex, empty and infinity coercion',()=>{for(const x of [[],[1],{},true,false,null,'','   ','0x20','Infinity',Infinity,NaN])assert.equal(finite(x),null)})
test('ordinary decimal and finite exponent notation remain supported',()=>{assert.equal(finite(' 1.25 '),1.25);assert.equal(linePrice('1e2','18','1e0').total,118)})
test('zero GST and all common published rates retain exact unit totals',()=>{for(const rate of [0,5,12,18,28])assert.equal(linePrice(100,rate,1).total,100+rate)})
test('unknown and over-precision GST cannot become a guessed rate',()=>{for(const r of [null,undefined,'',-1,101,[],[18],18.001])assert.equal(taxRate(r),null)})
test('price is positive and fits numeric(12,2) without silently rounding input',()=>{for(const n of [0,-1,'1.005','1.00000000000000001',1e10,Infinity,[100]])assert.equal(linePrice(n,18,1),null)})
test('GST half-paisa ties round up exactly',()=>assert.deepEqual(linePrice('0.25',18,1),{unit:.25,quantity:1,rate:18,base:.25,tax:.05,total:.3}))
test('base half-paisa ties for measured quantities round up exactly',()=>assert.equal(linePrice('0.29',0,1.5).base,.44))
test('fractional base and tax both round at line level',()=>assert.deepEqual(linePrice('99.99',18,1.235),{unit:99.99,quantity:1.235,rate:18,base:123.49,tax:22.23,total:145.72}))
test('three-place quantities accepted; extra nonzero precision rejected',()=>{assert.equal(linePrice(100,18,'1.235').total,145.73);for(const q of ['1.0001','1.00000000000001','0.00001'])assert.equal(linePrice(100,18,q),null)})
test('trailing zeroes do not create false over-precision errors',()=>assert.equal(linePrice('100.0000','18.0000','1.2350000').total,145.73))
test('zero-value sub-paisa lines are not purchasable',()=>assert.equal(linePrice('.01',18,'.001'),null))
test('quantity and order line limits match numeric database columns',()=>{assert.equal(linePrice('.01',0,'999999999.999').base,10000000);assert.equal(linePrice(1,0,'1000000000'),null);assert.equal(linePrice('9999999999.99',18,1),null)})
test('absent minimum retains legacy one-unit default',()=>{for(const min of [null,undefined,''])assert.equal(minimum(p({min_order_qty:min})),1)})
test('malformed published minimum does not silently become one',()=>{for(const min of [-1,0,'bad',[],1.0001])assert.ok(quantityError(1,p({min_order_qty:min}),v()).includes('confirmation'))})
test('minimum five with increment two starts at six, not five or ten',()=>assert.equal(firstQuantity(p({min_order_qty:5}),v({attributes:{quantity_step:2}})),6))
test('minimum is lower bound rather than a pack multiple',()=>assert.equal(quantityError(6,p({min_order_qty:5}),v()),null))
test('fractional piece MOQ starts at a whole purchasable unit',()=>assert.equal(firstQuantity(p({min_order_qty:.5}),v()),1))
test('measured units and explicit three-place increments are supported',()=>{assert.equal(quantityStep(v({unit:'m'})),.01);assert.equal(quantityError('1.235',p(),v({unit:'m',attributes:{quantity_step:.005}})),null)})
test('invalid explicit increment cannot fall back to a plausible default',()=>{for(const step of [null,0,-1,'bad',[],.0001])assert.ok(quantityError(1,p(),v({attributes:{quantity_step:step}})).includes('confirmation'))})
test('non-multiple quantities fail exact validation with no epsilon loophole',()=>{assert.match(quantityError(3,p(),v({attributes:{quantity_step:2}})),/increments/);assert.ok(quantityError('2.0000001',p(),v()))})
test('positive fractional stock does not imply a purchasable whole piece',()=>assert.equal(maximumQuantity(v({stock_qty:.8})),0))
test('remaining stock subtraction does not suffer decimal float drift',()=>{assert.equal(remainingQuantity(.3,.1),.2);assert.equal(quantityError(.2,p({min_order_qty:.1}),v({unit:'m',stock_qty:.3}),.1),null)})
test('existing cart quantity is counted before another addition',()=>{assert.equal(maximumQuantity(v({stock_qty:6}),5),1);assert.match(quantityError(2,p(),v({stock_qty:6}),5),/stock/)})
test('unknown, negative or corrupt stock is not advertised as zero or available',()=>{for(const s of [null,-1,[],Infinity,'bad']){assert.equal(remainingQuantity(s),null);assert.match(quantityError(1,p(),v({stock_qty:s})),/confirmation/)}})
test('cart quantities with unsupported precision fail closed',()=>assert.match(quantityError(1,p(),v(),.0001),/cart quantity/))
test('quantity plus/minus follows the valid lattice from valid and invalid drafts',()=>{const pp=p({min_order_qty:5}),vv=v({attributes:{quantity_step:2},stock_qty:9});assert.equal(nextQuantity(6,1,pp,vv),8);assert.equal(nextQuantity(7,-1,pp,vv),6);assert.equal(nextQuantity(7,1,pp,vv),8);assert.equal(nextQuantity('',1,pp,vv),6)})
test('quantity buttons stop at minimum and available step-aligned maximum',()=>{const pp=p({min_order_qty:5}),vv=v({attributes:{quantity_step:2},stock_qty:9});assert.equal(nextQuantity(6,-1,pp,vv),6);assert.equal(nextQuantity(8,1,pp,vv),8);assert.equal(nextQuantity(6,1,pp,vv,4),null)})
test('typing invalid quantity is rejected rather than changed by validation',()=>{const q='1.2345';assert.ok(quantityError(q,p(),v({unit:'m'})));assert.equal(q,'1.2345')})
test('fresh purchase checks combine active SKU, MOQ, step, stock and price',()=>{const pp=p({min_order_qty:5,product_variants:[v({attributes:{quantity_step:2},stock_qty:8})]});assert.equal(checkPurchase(pp,'a',6,2).ok,true);assert.equal(checkPurchase(pp,'a',6,3).ok,false);assert.equal(checkPurchase(pp,'a',5).ok,false)})
test('decimal pricing matches an independent integer reference over 3000 cases',()=>{
 for(let i=1;i<=3000;i++){const cents=(i*79)%100000+1,rate=[0,500,1200,1800,2800][i%5],m=(i*31)%9000+1
  const base=Math.floor((cents*m+500)/1000),tax=Math.floor((base*rate+5000)/10000),got=linePrice((cents/100).toFixed(2),(rate/100).toFixed(2),(m/1000).toFixed(3))
  if(base===0)assert.equal(got,null);else assert.deepEqual([got.base,got.tax,got.total],[base/100,tax/100,(base+tax)/100])
 }
})
test('product unit prices match catalogue over 19999 supported price/rate cases',()=>{for(let i=1;i<20000;i++){const rate=[0,5,12,18,28][i%5],base=i/100;assert.equal(linePrice(base,rate,1).total,priceFor({gst_rate:rate},{selling_price:base}).total)}})
