'use client'

import {useEffect,useState} from 'react'
import {Check,Download,Eye,PackageSearch,X} from 'lucide-react'
import {supabase} from '../../../../lib/supabase'

const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN')}`
export default function SavedConfigurations(){
 const [rows,setRows]=useState<any[]>([]),[view,setView]=useState<any>(null),[msg,setMsg]=useState('')
 useEffect(()=>{load()},[])
 async function load(){const {data,error}=await supabase.from('custom_configurations').select('*,configurator_templates(name,type),profiles(full_name,company_name,phone)').order('created_at',{ascending:false}).limit(300);if(error){setMsg(error.message);return}setRows(data||[])}
 function downloadBom(r:any){const blob=new Blob([JSON.stringify({configuration_code:r.configuration_code,config_name:r.config_name,bom:r.bom_snapshot,selected_options:r.selected_options,pricing:{subtotal:r.subtotal,assembly_charge:r.assembly_charge,gst_amount:r.gst_amount,final_price:r.final_price}},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${r.configuration_code||'configuration'}-bom.json`;a.click();URL.revokeObjectURL(a.href)}
 return <div className="cfgAdmin"><div className="adminPageHead"><div><span className="adminEyebrow">SAVED CUSTOMER BUILDS</span><h1>Configurations</h1><p>Every saved ACDB/DCDB visual build keeps a permanent BOM, component quantity and pricing snapshot for order and production use.</p></div></div>{msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}<section className="cfgPanel"><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Configuration</th><th>Type</th><th>Customer</th><th>Items</th><th>Subtotal</th><th>GST</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.configuration_code||'—'}</b><span className="tableSub">{r.config_name||'Custom build'} • {new Date(r.created_at).toLocaleString()}</span></td><td>{String(r.configurator_templates?.type||'').toUpperCase()}</td><td>{r.profiles?.full_name||r.profiles?.company_name||r.profiles?.phone||r.user_id||'—'}</td><td>{Array.isArray(r.bom_snapshot)?r.bom_snapshot.length:0}</td><td>{money(r.subtotal)}</td><td>{money(r.gst_amount)}</td><td><b>{money(r.final_price)}</b></td><td>{r.status}</td><td><div className="rowActions"><button onClick={()=>setView(r)} title="View"><Eye size={14}/></button><button onClick={()=>downloadBom(r)} title="Download BOM JSON"><Download size={14}/></button></div></td></tr>):<tr><td colSpan={9} className="emptyCell">No saved visual configurations yet.</td></tr>}</tbody></table></div></section>{view&&<div className="cfgModalWrap" onClick={()=>setView(null)}><div className="cfgModal" onClick={e=>e.stopPropagation()}><button className="cfgModalClose" onClick={()=>setView(null)}><X/></button><div className="cfgModalHead"><PackageSearch/><div><span>CONFIGURATION DETAIL</span><h2>{view.configuration_code}</h2><p>{view.config_name}</p></div></div><div className="cfgModalPrice"><div><span>Subtotal</span><b>{money(view.subtotal)}</b></div><div><span>Assembly</span><b>{money(view.assembly_charge)}</b></div><div><span>GST</span><b>{money(view.gst_amount)}</b></div><div><span>Total</span><b>{money(view.final_price)}</b></div></div><h3>BOM Snapshot</h3><div className="cfgBomTable">{(view.bom_snapshot||[]).map((x:any,i:number)=><div key={i}><span>{x.category||x.option_label}</span><b>{x.component_name||x.selected_label}</b><em>Qty {x.quantity||1}</em><strong>{money(Number(x.selling_price||0)*(x.quantity||1))}</strong></div>)}</div><button className="adminBtn" onClick={()=>downloadBom(view)}><Download size={15}/>Download BOM JSON</button></div></div>}</div>
}
