'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import {Check,Link2,Plus,Trash2} from 'lucide-react'
import {supabase} from '../../../../lib/supabase'

export default function ConfiguratorOptions(){
 const [templates,setTemplates]=useState<any[]>([]),[options,setOptions]=useState<any[]>([]),[components,setComponents]=useState<any[]>([]),[enclosures,setEnclosures]=useState<any[]>([]),[values,setValues]=useState<any[]>([]),[templateId,setTemplateId]=useState(''),[optionId,setOptionId]=useState(''),[msg,setMsg]=useState(''),[form,setForm]=useState<any>({label:'',value:'',component_id:'',enclosure_id:'',price_adjustment:0,sort_order:0,is_active:true})
 useEffect(()=>{Promise.all([supabase.from('configurator_templates').select('id,name,type').order('name'),supabase.from('configurator_options').select('id,template_id,option_key,label,sort_order').order('sort_order'),supabase.from('components').select('id,name,category,brands(name)').eq('is_active',true).order('category').order('name'),supabase.from('enclosures').select('id,name').eq('is_active',true).order('name')]).then(([t,o,c,e])=>{setTemplates(t.data||[]);setOptions(o.data||[]);setComponents(c.data||[]);setEnclosures(e.data||[]);if(t.data?.[0])setTemplateId(t.data[0].id)})},[])
 const filteredOptions=useMemo(()=>options.filter(o=>o.template_id===templateId),[options,templateId])
 useEffect(()=>{if(filteredOptions.length&&!filteredOptions.some(o=>o.id===optionId))setOptionId(filteredOptions[0].id)},[filteredOptions,optionId])
 useEffect(()=>{if(optionId)loadValues()},[optionId])
 async function loadValues(){const {data}=await supabase.from('configurator_option_values').select('*,components(name,category,brands(name)),enclosures(name)').eq('option_id',optionId).order('sort_order');setValues(data||[])}
 async function save(e:FormEvent){e.preventDefault();if(!optionId)return;const linkedComponent=form.component_id||null;const linkedEnclosure=form.enclosure_id||null;if(linkedComponent&&linkedEnclosure){setMsg('Choose either component or enclosure, not both.');return}const p={option_id:optionId,label:form.label,value:form.value||form.label.toLowerCase().replace(/[^a-z0-9]+/g,'-'),component_id:linkedComponent,enclosure_id:linkedEnclosure,price_adjustment:Number(form.price_adjustment||0),metadata:{source:'configurator_admin'},sort_order:Number(form.sort_order||0),is_active:!!form.is_active};const r=await supabase.from('configurator_option_values').insert(p);if(r.error){setMsg(r.error.message);return}setMsg('Option value linked. Buyer builder updates immediately.');setForm({label:'',value:'',component_id:'',enclosure_id:'',price_adjustment:0,sort_order:values.length,is_active:true});loadValues()}
 async function remove(id:string){await supabase.from('configurator_option_values').delete().eq('id',id);loadValues()}
 return <div className="cfgAdmin"><div className="adminPageHead"><div><span className="adminEyebrow">BUYER OPTION LIBRARY</span><h1>Link Components to Builder</h1><p>Connect uploaded component PNGs and enclosure templates to ACDB/DCDB option groups so buyers can actually select them.</p></div></div>{msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}<div className="cfgSelectors"><label>Builder<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Option Group<select value={optionId} onChange={e=>setOptionId(e.target.value)}>{filteredOptions.map(o=><option key={o.id} value={o.id}>{o.label} ({o.option_key})</option>)}</select></label></div><form className="cfgRuleForm" onSubmit={save}><label><span>Buyer Label</span><input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder="Siemens 2P C32"/></label><label><span>Component</span><select value={form.component_id} onChange={e=>setForm({...form,component_id:e.target.value,enclosure_id:e.target.value?'':form.enclosure_id})}><option value="">No component</option>{components.map(c=><option key={c.id} value={c.id}>{c.category} — {c.brands?.name?`${c.brands.name} `:''}{c.name}</option>)}</select></label><label><span>Enclosure</span><select value={form.enclosure_id} onChange={e=>setForm({...form,enclosure_id:e.target.value,component_id:e.target.value?'':form.component_id})}><option value="">No enclosure</option>{enclosures.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Extra Price</span><input type="number" value={form.price_adjustment} onChange={e=>setForm({...form,price_adjustment:e.target.value})}/></label><label><span>Sort</span><input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><button className="adminBtn"><Plus size={15}/>Add Option</button></form><section className="cfgPanel"><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Buyer Label</th><th>Linked Asset</th><th>Price Adjustment</th><th>Active</th><th></th></tr></thead><tbody>{values.map(v=><tr key={v.id}><td><b>{v.label}</b><span className="tableSub">{v.value}</span></td><td>{v.components?<><Link2 size={13}/> {v.components.brands?.name?`${v.components.brands.name} `:''}{v.components.name}</>:v.enclosures?<><Link2 size={13}/> {v.enclosures.name}</>:'Rule / text option'}</td><td>₹{Number(v.price_adjustment||0).toLocaleString('en-IN')}</td><td>{v.is_active?'Yes':'No'}</td><td><button className="cfgIconDanger" onClick={()=>remove(v.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></section></div>
}
