'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {supabase} from '../../../../lib/supabase'
import {canAdmin} from '../../../../lib/adminAccess'
const blank={id:'',label:'',value:'',component_id:'',enclosure_id:'',price_adjustment:0,sort_order:0,is_active:true,metadata:{} as any}
export default function ConfiguratorOptions(){
 const [templates,setTemplates]=useState<any[]>([]),[options,setOptions]=useState<any[]>([]),[components,setComponents]=useState<any[]>([]),[enclosures,setEnclosures]=useState<any[]>([]),[values,setValues]=useState<any[]>([])
 const [templateId,setTemplateId]=useState(''),[optionId,setOptionId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<any>(blank),[access,setAccess]=useState<any>(null)
 async function load(){const results=await Promise.all([supabase.from('configurator_templates').select('id,name,type').order('name'),supabase.from('configurator_options').select('*').order('sort_order'),supabase.from('components').select('id,name,category,brands(name)').eq('is_active',true).order('category').order('name'),supabase.from('enclosures').select('id,name').eq('is_active',true).order('name')]);const error=results.find(r=>r.error)?.error;if(error){setMessage(error.message);return}const [t,o,c,e]=results;setTemplates(t.data||[]);setOptions(o.data||[]);setComponents(c.data||[]);setEnclosures(e.data||[]);setTemplateId(previous=>previous||t.data?.[0]?.id||'')}
 useEffect(()=>{void load();void supabase.rpc('get_my_admin_access').then(({data})=>setAccess(data))},[])
 const groups=useMemo(()=>options.filter(o=>o.template_id===templateId),[options,templateId]),group=groups.find(g=>g.id===optionId)
 useEffect(()=>{if(!groups.some(g=>g.id===optionId))setOptionId(groups[0]?.id||'')},[groups,optionId])
 useEffect(()=>{setForm(blank);setValues([]);if(!optionId)return;const controller=new AbortController();void supabase.from('configurator_option_values').select('*').eq('option_id',optionId).order('sort_order').abortSignal(controller.signal).then(({data,error})=>{if(controller.signal.aborted)return;if(error)setMessage(error.message);else setValues(data||[])});return()=>controller.abort()},[optionId])
 async function refreshValues(){const r=await supabase.from('configurator_option_values').select('*').eq('option_id',optionId).order('sort_order');if(r.error)throw r.error;setValues(r.data||[])}
 async function save(e:FormEvent){e.preventDefault();if(!group||busy)return;setBusy(true);setMessage('');try{
  if(form.component_id&&form.enclosure_id)throw new Error('Choose one linked asset.')
  if(group.option_key==='enclosure'&&!form.enclosure_id)throw new Error('The enclosure group requires an enclosure.')
  const payload={option_id:group.id,label:form.label.trim(),value:form.value||form.label.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),component_id:form.component_id||null,enclosure_id:form.enclosure_id||null,price_adjustment:Number(form.price_adjustment),sort_order:Number(form.sort_order),is_active:form.is_active,metadata:{...form.metadata,source:'configurator_admin'}}
  // Single-choice defaults must be unambiguous; do not silently alter other records.
  if(payload.is_active&&payload.metadata.default&&group.option_type!=='multi'&&values.some(v=>v.id!==form.id&&v.is_active&&v.metadata?.default))throw new Error('Edit the existing default and clear its Default checkbox first.')
  const r=form.id?await supabase.from('configurator_option_values').update(payload).eq('id',form.id).select('id').single():await supabase.from('configurator_option_values').insert(payload).select('id').single();if(r.error)throw r.error;await refreshValues();setForm(blank);setMessage('Option saved. Published buyers receive it on catalogue refresh.')
 }catch(e){setMessage(String((e as any)?.message||e))}finally{setBusy(false)}}
 async function saveGroup(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!group||busy)return;const f=new FormData(e.currentTarget),min=Number(f.get('min')),max=Number(f.get('max'));if(!Number.isInteger(min)||min<1||!Number.isInteger(max)||max<min){setMessage('Quantities must be positive whole numbers; maximum must be at least minimum.');return}setBusy(true);try{const r=await supabase.from('configurator_options').update({label:String(f.get('label')).trim(),required:f.get('required')==='on',allow_quantity:f.get('quantity')==='on',min_quantity:min,max_quantity:max,settings:{...group.settings,buyer_visible:f.get('visible')==='on'}}).eq('id',group.id).select('id').single();if(r.error)throw r.error;await load();setMessage('Group settings saved. Run the template catalogue check before publishing.')}catch(e){setMessage(String((e as any)?.message||e))}finally{setBusy(false)}}
 const edit=canAdmin(access,'configurator','edit'),create=canAdmin(access,'configurator','create')
 return <div className="cfgAdmin"><div className="adminPageHead"><div><h1>Builder Options & Defaults</h1><p>These choices come directly from the admin catalogue. Disable retired options to preserve historical quotation requests.</p></div></div>{message&&<p className="themeMessage" role="status">{message}</p>}<div className="cfgSelectors"><label>Builder<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Group<select value={optionId} onChange={e=>setOptionId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.label} ({g.option_key})</option>)}</select></label></div>
 {group&&<form key={group.id+JSON.stringify(group.settings)+group.label+group.min_quantity+group.max_quantity+group.required+group.allow_quantity} className="cfgRuleForm" onSubmit={saveGroup}><label>Group label<input name="label" required defaultValue={group.label}/></label><label>Minimum quantity<input name="min" type="number" min="1" step="1" defaultValue={group.min_quantity||1}/></label><label>Maximum quantity<input name="max" type="number" min="1" step="1" defaultValue={group.max_quantity||1}/></label><label><input name="required" type="checkbox" defaultChecked={group.required}/> Required</label><label><input name="quantity" type="checkbox" defaultChecked={group.allow_quantity}/> Allow quantity</label><label><input name="visible" type="checkbox" defaultChecked={group.settings?.buyer_visible!==false}/> Show to buyers</label><button disabled={busy||!edit} className="adminBtn">Save group</button></form>}
 <form className="cfgRuleForm" onSubmit={save}><label>Buyer label<input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label>Component<select value={form.component_id||''} onChange={e=>setForm({...form,component_id:e.target.value,enclosure_id:''})}><option value="">No component / text choice</option>{components.map(c=><option key={c.id} value={c.id}>{c.category} — {c.name}</option>)}</select></label><label>Enclosure<select value={form.enclosure_id||''} onChange={e=>setForm({...form,enclosure_id:e.target.value,component_id:''})}><option value="">No enclosure</option>{enclosures.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Price adjustment<input type="number" step="0.01" value={form.price_adjustment} onChange={e=>setForm({...form,price_adjustment:e.target.value})}/></label><label>Sort order<input type="number" step="1" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label><label><input type="checkbox" checked={!!form.metadata?.default} onChange={e=>setForm({...form,metadata:{...form.metadata,default:e.target.checked}})}/> Default</label><button className="adminBtn" disabled={busy||!group||!(form.id?edit:create)}>{form.id?'Save option':'Add option'}</button>{form.id&&<button type="button" onClick={()=>setForm(blank)}>Cancel edit</button>}</form>
 <section className="cfgPanel"><table className="adminTable"><thead><tr><th>Choice</th><th>Linked item</th><th>Status</th><th>Default</th><th>Action</th></tr></thead><tbody>{values.map(v=><tr key={v.id}><td>{v.label}</td><td>{components.find(c=>c.id===v.component_id)?.name||enclosures.find(c=>c.id===v.enclosure_id)?.name||(v.component_id||v.enclosure_id?'Inactive or unavailable asset':'Text choice')}</td><td>{v.is_active?'Active':'Disabled'}</td><td>{v.metadata?.default?'Yes':'No'}</td><td><button disabled={!edit||busy} onClick={()=>setForm({...blank,...v,metadata:v.metadata||{}})}>Edit / disable</button></td></tr>)}</tbody></table></section></div>
}
