import type {Metadata} from 'next'
import Link from 'next/link'
import {ArrowRight,Boxes,CheckCircle2,ClipboardCheck,Factory,PackageCheck,ShieldCheck,Truck} from 'lucide-react'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'

export const metadata:Metadata={title:'Why New India Solar | Solar Components for EPCs',description:'Discover how New India Solar supports EPCs, installers and project buyers with ACDB, DCDB and solar BOS procurement.',alternates:{canonical:'/why-new-india'}}

const pillars=[
 {icon:Boxes,title:'One focused solar range',body:'Protection boxes, switchgear, wiring, connectors, earthing and BOS essentials in one product system.'},
 {icon:ClipboardCheck,title:'Clear product information',body:'Published variants, ratings, GST, minimum quantities and availability are presented before checkout.'},
 {icon:PackageCheck,title:'Project-ready procurement',body:'Direct purchase for standard products, saved buyer details and a separate RFQ path for bulk or custom requirements.'},
 {icon:Factory,title:'Custom ACDB / DCDB workflow',body:'Visual requirement builders help buyers define components before engineering, BOM and commercial confirmation.'},
 {icon:Truck,title:'Built for Indian project supply',body:'A Surat-based company serving installers, dealers, EPC teams and project buyers across India.'},
 {icon:ShieldCheck,title:'Verification before commitment',body:'Current price, tax, minimum quantity and stock are checked again during the ordering flow.'},
]

export default function WhyNewIndiaPage(){return <><StoreHeader/><main id="main-content" className="companyPage"><section className="companyHero"><div className="container companyHeroGrid"><div><span>WHY NEW INDIA SOLAR</span><h1>Solar component buying,<br/><em>designed around the project.</em></h1><p>New India Solar brings ACDB, DCDB and balance-of-system procurement into one clear buyer experience for EPCs, installers, dealers and project teams.</p><div><Link className="nisBtn nisBtnPrimary" href="/categories">Explore categories <ArrowRight size={17}/></Link><Link className="nisBtn nisBtnOutline" href="/bulk-order">Submit project RFQ</Link></div></div><aside><b>OUR PURPOSE</b><blockquote>Build a dependable solar-components infrastructure company that makes product selection, custom requirements and project procurement easier across India.</blockquote><span>Powering India’s Solar Installations.</span></aside></div></section><section className="container companyIntro"><div><span>BUILT FOR THE PEOPLE WHO BUILD SOLAR</span><h2>From a single component to a complete requirement.</h2></div><p>Standard products can move through the catalogue and cart. Larger quantities and custom protection boxes move through a reviewed RFQ and BOM workflow, keeping direct purchase separate from engineering approval.</p></section><section className="container companyPillars">{pillars.map(({icon:Icon,title,body},index)=><article key={title}><div><span>0{index+1}</span><Icon size={22}/></div><h3>{title}</h3><p>{body}</p></article>)}</section><section className="companyJourney"><div className="container"><header><span>ONE CONNECTED BUYER JOURNEY</span><h2>Choose the right path for every requirement.</h2></header><div><article><b>01</b><h3>Browse</h3><p>Discover products through focused category collections.</p></article><article><b>02</b><h3>Compare</h3><p>Review published options, specifications and GST-inclusive prices.</p></article><article><b>03</b><h3>Buy or configure</h3><p>Purchase standard products or define a custom ACDB/DCDB requirement.</p></article><article><b>04</b><h3>Track</h3><p>Keep buyer details, addresses and order information connected to one account.</p></article></div></div></section><section className="container companyCta"><div><CheckCircle2/><div><span>START YOUR NEXT REQUIREMENT</span><h2>Ready products, custom boxes and project quantities—one New India Solar workflow.</h2></div></div><div><Link href="/shop">Shop products <ArrowRight size={16}/></Link><Link href="/contact">Contact us</Link></div></section></main><StoreFooter/></>}
