'use client'

import {ChangeEvent,FormEvent,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {Check,Edit3,Eye,ImagePlus,PackagePlus,RefreshCw,Save,Search,Trash2,Upload,X} from 'lucide-react'
import {supabase} from '../../../lib/supabase'

type Variant={id?:string;sku:string;title:string;mrp:any;selling_price:any;cost_price:any;stock_qty:any;low_stock_threshold:any;unit:string;weight_kg:any;is_active:boolean;attributes:any}
type Img={id?:string;image_url:string;alt_text:string;sort_order:number}
const blankVariant:Variant={sku:'',title:'Standard',mrp:'',selling_price:'',cost_price:'',stock_qty:'',low_stock_threshold:5,unit:'pcs',weight_kg:'',is_active:true,attributes:{}}
const blank={id:'',name:'',slug:'',short_description:'',description:'',product_type:'standard',status:'draft',hsn_code:'',gst_rate:18,warranty_months:12,datasheet_url:'',installation_guide_url:'',featured:false,category_id:'',brand_id:'',specifications:'{}',inclusions:'',applications:'',product_badges:'',lead_time_days:3,min_order_qty:1,sort_order:0,variants:[blankVariant] as Variant[],images:[] as Img[]}
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const lines=(s:string)=>s.split('\n').map(x=>x.trim()).filter(Boolean)
const safeName=(f:File)=>f.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/-+/g,'-')
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN')}`
const gstIncl=(n:any,g:any=18)=>Math.round(Number(n||0)*(1+Number(g||18)/100))
function jsonValue(s:string){try{return s.trim()?JSON.parse(s):{}}catch{return {raw:s}}}

export default function Products(){
 const [rows,setRows]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[brands,setBrands]=useState<any[]>([]),[form,setForm]=useState<any>(blank),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[status,setStatus]=useState('all'),[tab,setTab]=useState<'basic'|'images'|'variants'|'content'>('basic')
 useEffect(()=>{load()},[])
 async function load(){setLoading(true);const [p,c,b]=await Promise.all([supabase.from('products').select('*,categories(name,slug),product_variants(*),product_images(*)').order('sort_order').limit(500),supabase.from('categories').select('id,name,slug').eq('is_active',true).order('sort_order'),supabase.from('brands').select('id,name,slug').eq('is_active',true).order('name')]);setRows(p.data||[]);setCats(c.data||[]);setBrands(b.data||[]);setLoading(false)}
 const filtered=useMemo(()=>rows.filter(r=>(cat==='all'||r.categories?.slug===cat)&&(status==='all'||r.status===status)&&`${r.name} ${r.slug} ${r.short_description||''} ${r.categories?.name||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q,cat,status])
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.status==='active').length,draft:rows.filter(x=>x.status==='draft').length,withImg:rows.filter(x=>(x.product_images||[]).length).length}),[rows])
 function set(k:string,v:any){setForm((f:any)=>({...f,[k]:v,slug:k==='name'&&!f.slug?slugify(v):f.slug}))}
 function setV(i:number,k:string,v:any){setForm((f:any)=>({...f,variants:f.variants.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}))}
 function setI(i:number,k:string,v:any){setForm((f:any)=>({...f,images:f.images.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}))}
 function firstImg(p:any){return [...(p.product_images||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)[0]?.image_url}
 function firstVar(p:any){return p.product_variants?.[0]||{}}
 function addNew(){setForm({...blank,slug:'',variants:[{...blankVariant}],images:[]});setShow(true);setTab('basic');setMsg('')}
 function edit(p:any){setForm({id:p.id,name:p.name||'',slug:p.slug||'',short_description:p.short_description||'',description:p.description||'',product_type:p.product_type||'standard',status:p.status||'draft',hsn_code:p.hsn_code||'',gst_rate:Number(p.gst_rate||18),warranty_months:p.warranty_months||12,datasheet_url:p.datasheet_url||'',installation_guide_url:p.installation_guide_url||'',featured:!!p.featured,category_id:p.category_id||'',brand_id:p.brand_id||'',specifications:JSON.stringify(p.specifications||{},null,2),inclusions:(p.inclusions||[]).join('\n'),applications:(p.applications||[]).join('\n'),product_badges:(p.product_badges||[]).join('\n'),lead_time_days:p.lead_time_days||3,min_order_qty:p.min_order_qty||1,sort_order:p.sort_order||0,variants:p.product_variants?.length?p.product_variants.map((v:any)=>({...v,attributes:v.attributes||{}})):[{...blankVariant,sku:`NIS-${(p.slug||'SKU').toUpperCase()}`}],images:[...(p.product_images||[])].sort((a:any,b:any)=>a.sort_order-b.sort_order)});setShow(true);setTab('basic');setMsg('');window.scrollTo({top:0,behavior:'smooth'})}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/')){setMsg('Only image files are allowed.');return}setUploading(true);setMsg('Uploading image…');const path=`products/${slugify(form.slug||form.name||'product')}/${Date.now()}-${safeName(file)}`;const up=await supabase.storage.from('product-assets').upload(path,file,{upsert:false,cacheControl:'3600'});if(up.error){setMsg(up.error.message);setUploading(false);return}const {data}=supabase.storage.from('product-assets').getPublicUrl(path);let img:Img={image_url:data.publicUrl,alt_text:form.name||'Product image',sort_order:form.images.length};if(form.id){const saved=await supabase.from('product_images').insert({product_id:form.id,...img}).select('*').single();if(saved.error){setMsg(saved.error.message);setUploading(false);return}img=saved.data as Img;load()}setForm((f:any)=>({...f,images:[...f.images,img]}));setMsg(form.id?'Image uploaded and live on buyer page.':'Image uploaded. Save product to publish.');setUploading(false)}
 async function removeImage(i:number,img:Img){if(img.id)await supabase.from('product_images').delete().eq('id',img.id);setForm((f:any)=>({...f,images:f.images.filter((_:any,n:number)=>n!==i)}));setMsg('Image removed.')}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');const payload={name:form.name,slug:form.slug||slugify(form.name),short_description:form.short_description||null,description:form.description||null,product_type:form.product_type,status:form.status,hsn_code:form.hsn_code||null,gst_rate:Number(form.gst_rate||18),warranty_months:form.warranty_months?Number(form.warranty_months):null,datasheet_url:form.datasheet_url||null,installation_guide_url:form.installation_guide_url||null,featured:!!form.featured,category_id:form.category_id||null,brand_id:form.brand_id||null,specifications:jsonValue(form.specifications),inclusions:lines(form.inclusions),applications:lines(form.applications),product_badges:lines(form.product_badges),lead_time_days:Number(form.lead_time_days||3),min_order_qty:Number(form.min_order_qty||1),sort_order:Number(form.sort_order||0)};let productId=form.id;let err:any=null;if(productId){err=(await supabase.from('products').update(payload).eq('id',productId)).error}else{const res=await supabase.from('products').insert(payload).select('id').single();err=res.error;productId=res.data?.id}if(err){setMsg(err.message);setSaving(false);return}
 await supabase.from('product_variants').delete().eq('product_id',productId);await supabase.from('product_images').delete().eq('product_id',productId)
 const variants=form.variants.filter((v:Variant)=>v.sku&&v.title).map((v:Variant)=>({product_id:productId,sku:v.sku,title:v.title,attributes:v.attributes||{},mrp:Number(v.mrp||0),selling_price:Number(v.selling_price||0),cost_price:Number(v.cost_price||0),stock_qty:Number(v.stock_qty||0),low_stock_threshold:Number(v.low_stock_threshold||5),unit:v.unit||'pcs',weight_kg:v.weight_kg?Number(v.weight_kg):null,is_active:!!v.is_active}));if(variants.length){err=(await supabase.from('product_variants').insert(variants)).error;if(err){setMsg(err.message);setSaving(false);return}}
 const images=form.images.filter((img:Img)=>img.image_url).map((img:Img,i:number)=>({product_id:productId,image_url:img.image_url,alt_text:img.alt_text||form.name,sort_order:i}));if(images.length){err=(await supabase.from('product_images').insert(images)).error;if(err){setMsg(err.message);setSaving(false);return}}
 setSaving(false);setShow(false);setForm({...blank,variants:[{...blankVariant}],images:[]});setMsg('Product saved and buyer listing updated.');load()}
 async function remove(p:any){if(!confirm(`Delete ${p.name}?`))return;await supabase.from('product_variants').delete().eq('product_id',p.id);await supabase.from('product_images').delete().eq('product_id',p.id);const {error}=await supabase.from('products').delete().eq('id',p.id);setMsg(error?error.message:'Product deleted.');load()}
 return <>
 <div className="productAdminPro">
  <div className="productAdminHero"><div><span className="adminEyebrow">CATALOGUE CONTROL CENTER</span><h1>Products</h1><p>Clean product listing, fast editing, instant image upload and complete buyer publishing flow.</p></div><div className="productHeroActions"><button className="adminBtn ghost" onClick={load}><RefreshCw size={16}/>Refresh</button><button className="adminBtn" onClick={addNew}><PackagePlus size={16}/>Add Product</button></div></div>
  {msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}
  <div className="productStats"><b>{stats.total}<span>Total</span></b><b>{stats.active}<span>Active</span></b><b>{stats.draft}<span>Draft</span></b><b>{stats.withImg}<span>With images</span></b></div>
  {show&&<form onSubmit={save} className="productDrawerPro"><div className="drawerTop"><div><h2>{form.id?'Edit Product':'Add New Product'}</h2><p>{form.id?'Image upload is now saved instantly for this product.':'Add details first, then save product to publish.'}</p></div><div><button type="button" className="adminBtn ghost" onClick={()=>setShow(false)}><X size={16}/>Close</button><button className="adminBtn" disabled={saving}><Save size={16}/>{saving?'Saving…':'Save Product'}</button></div></div><div className="drawerTabs">{(['basic','images','variants','content'] as const).map(t=><button type="button" className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
   {tab==='basic'&&<div className="proGrid"><label className="wide"><span>Product Name</span><input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="ACDB 3kW Single Phase"/></label><label><span>Slug</span><input required value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></label><label><span>Category</span><select required value={form.category_id} onChange={e=>set('category_id',e.target.value)}><option value="">Select category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Brand</span><select value={form.brand_id} onChange={e=>set('brand_id',e.target.value)}><option value="">New India Solar</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label><span>GST %</span><input type="number" value={form.gst_rate} onChange={e=>set('gst_rate',e.target.value)}/></label><label><span>HSN</span><input value={form.hsn_code} onChange={e=>set('hsn_code',e.target.value)}/></label><label><span>Warranty Months</span><input type="number" value={form.warranty_months} onChange={e=>set('warranty_months',e.target.value)}/></label><label><span>Lead Days</span><input type="number" value={form.lead_time_days} onChange={e=>set('lead_time_days',e.target.value)}/></label><label><span>MOQ</span><input type="number" value={form.min_order_qty} onChange={e=>set('min_order_qty',e.target.value)}/></label><label><span>Sort</span><input type="number" value={form.sort_order} onChange={e=>set('sort_order',e.target.value)}/></label><label className="switchLine"><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/><span>Featured Product</span></label><label className="full"><span>Short Description</span><input value={form.short_description} onChange={e=>set('short_description',e.target.value)} placeholder="Buyer card short copy"/></label></div>}
   {tab==='images'&&<div className="imageStudio"><div className="uploadZone"><ImagePlus size={34}/><h3>Product Images</h3><p>Upload JPG, PNG, WEBP or SVG. Existing product images go live immediately after upload.</p><label className="adminBtn"><Upload size={16}/>{uploading?'Uploading…':'Upload Image'}<input hidden type="file" accept="image/*" onChange={upload} disabled={uploading}/></label></div><div className="imageStudioGrid">{form.images.map((img:Img,i:number)=><div className="imageCardPro" key={img.id||img.image_url||i}><div>{img.image_url?<img src={img.image_url} alt={img.alt_text}/>:<ImagePlus/>}</div><input value={img.image_url} onChange={e=>setI(i,'image_url',e.target.value)} placeholder="Image URL"/><input value={img.alt_text} onChange={e=>setI(i,'alt_text',e.target.value)} placeholder="Alt text"/><button type="button" onClick={()=>removeImage(i,img)}><Trash2 size={14}/>Remove</button></div>)}<button type="button" className="addImagePro" onClick={()=>setForm((f:any)=>({...f,images:[...f.images,{image_url:'',alt_text:f.name,sort_order:f.images.length}]}))}><ImagePlus/>Add URL</button>}</div></div>}
   {tab==='variants'&&<div className="variantStudio"><div className="variantTop"><h3>Variants, Price & Stock</h3><button type="button" className="adminBtn ghost" onClick={()=>setForm((f:any)=>({...f,variants:[...f.variants,{...blankVariant,sku:`NIS-${(f.slug||'SKU').toUpperCase()}-${f.variants.length+1}` }]}))}>Add Variant</button></div>{form.variants.map((v:Variant,i:number)=><div className="variantCardPro" key={i}><label><span>SKU</span><input required value={v.sku} onChange={e=>setV(i,'sku',e.target.value)}/></label><label><span>Title</span><input required value={v.title} onChange={e=>setV(i,'title',e.target.value)}/></label><label><span>Selling Price</span><input required type="number" value={v.selling_price} onChange={e=>setV(i,'selling_price',e.target.value)}/><small>Incl. GST: {money(gstIncl(v.selling_price,form.gst_rate))}</small></label><label><span>MRP</span><input type="number" value={v.mrp} onChange={e=>setV(i,'mrp',e.target.value)}/></label><label><span>Cost</span><input type="number" value={v.cost_price} onChange={e=>setV(i,'cost_price',e.target.value)}/></label><label><span>Stock</span><input type="number" value={v.stock_qty} onChange={e=>setV(i,'stock_qty',e.target.value)}/></label><label><span>Unit</span><input value={v.unit} onChange={e=>setV(i,'unit',e.target.value)}/></label><label><span>Weight KG</span><input type="number" value={v.weight_kg||''} onChange={e=>setV(i,'weight_kg',e.target.value)}/></label><button type="button" className="dangerMini" onClick={()=>setForm((f:any)=>({...f,variants:f.variants.filter((_:any,n:number)=>n!==i)}))}><Trash2 size={14}/></button></div>)}</div>}
   {tab==='content'&&<div className="proGrid"><label className="full"><span>Full Description</span><textarea rows={5} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label className="full"><span>Specifications JSON</span><textarea rows={6} value={form.specifications} onChange={e=>set('specifications',e.target.value)} placeholder={'{"Voltage":"1000V DC","Current":"32A"}'}/></label><label className="full"><span>Inclusions — one per line</span><textarea rows={4} value={form.inclusions} onChange={e=>set('inclusions',e.target.value)}/></label><label className="full"><span>Applications — one per line</span><textarea rows={4} value={form.applications} onChange={e=>set('applications',e.target.value)}/></label><label className="full"><span>Badges — one per line</span><textarea rows={3} value={form.product_badges} onChange={e=>set('product_badges',e.target.value)}/></label><label><span>Datasheet URL</span><input value={form.datasheet_url} onChange={e=>set('datasheet_url',e.target.value)}/></label><label><span>Installation Guide URL</span><input value={form.installation_guide_url} onChange={e=>set('installation_guide_url',e.target.value)}/></label></div>}
  </form>}
  <section className="productListPanel"><div className="listToolbar"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, SKU, category..."/></label><select value={cat} onChange={e=>setCat(e.target.value)}><option value="all">All categories</option>{cats.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option value="active">Active</option><option value="draft">Draft</option><option value="inactive">Inactive</option></select><button onClick={()=>setQ('')}>Clear</button></div>
   {loading?<div className="adminEmpty">Loading products…</div>:<div className="cleanProductTable"><table><thead><tr><th>Product</th><th>Category</th><th>Status</th><th>Price + GST</th><th>Stock</th><th>Images</th><th>Buyer</th><th></th></tr></thead><tbody>{filtered.map(p=>{const v=firstVar(p);const img=firstImg(p);return <tr key={p.id}><td><div className="productCell">{img?<img src={img} alt={p.name}/>:<span><ImagePlus size={18}/></span>}<div><b>{p.name}</b><small>{v.sku||p.slug}</small></div></div></td><td>{p.categories?.name||'—'}</td><td><em className={`statusPill ${p.status}`}>{p.status}</em></td><td><strong>{money(gstIncl(v.selling_price,p.gst_rate))}</strong><small>Base {money(v.selling_price)} + {p.gst_rate||18}%</small></td><td>{Number(v.stock_qty||0)} {v.unit||'pcs'}</td><td>{(p.product_images||[]).length}</td><td><Link href={`/product/${p.slug}`} target="_blank"><Eye size={15}/> View</Link></td><td><div className="rowActions"><button onClick={()=>edit(p)}><Edit3 size={15}/></button><button onClick={()=>remove(p)}><Trash2 size={15}/></button></div></td></tr>})}</tbody></table></div>}
  </section>
 </div>
 </>
}
