import './globals.css'
import './buyer-account.css'
import './brand.css'
import './upgrade.css'
import './upgrade2.css'
import './upgrade3.css'
import './upgrade4.css'
import './upgrade5.css'
import './theme-admin.css'
import './upgrade6.css'
import './product-admin.css'
import './product-detail-flow.css'
import './upgrade7.css'
import './product-admin-pro.css'
import './homepage-v2.css'
import './header-v2.css'
import './product-page-v3.css'
import './product-image-fit.css'
import './configurator-v2.css'
import './configurator-admin.css'
import './configurator-editor-v2.css'
import './production-fixes.css'
import './responsive-final.css'
import './responsive-hotfix.css'
import './buyer-design-system-v2.css'
import './admin-shell-v2.css'
import './admin-dashboard-v2.css'
import './orders-v2.css'
import './admin-catalogue-v2.css'
import './inventory-v2.css'
import './production-v2.css'
import './rfq-v2.css'
import './customers-v2.css'
import './procurement-v2.css'
import './pricing-v2.css'
import './finance-v2.css'
import './accounting-v2.css'
import './reports-v2.css'
import './cms-v2.css'
import './access-v2.css'
import './notifications-v2.css'
import './workflows-v2.css'
import './global-search-v2.css'
import './configurator-assets-v3.css'
import './manufacturing-v2.css'
import './product-cost-v2.css'
import './storefront-v3.css'
import './storefront-polish-v4.css'
import './admin-login-v2.css'
import type {Metadata} from 'next'
import {CartProvider} from '../components/CartProvider'
import ThemeProvider from '../components/ThemeProvider'
import {SiteContentProvider} from '../components/SiteContentProvider'

export const metadata:Metadata={
 title:'New India Solar | ACDB, DCDB & Solar Components',
 description:'Shop ACDB, DCDB, MCB, SPD, solar cable, earthing kits and customize ACDB/DCDB boxes for solar installations.'
}

export default function RootLayout({children}:{children:React.ReactNode}){
 return <html lang="en"><body><ThemeProvider><SiteContentProvider><CartProvider>{children}</CartProvider></SiteContentProvider></ThemeProvider></body></html>
}
