'use client'

import Link from 'next/link'
import { ArrowRight, Boxes, Cable, CheckCircle2, FileText, PackageCheck, Settings2, ShieldCheck, ShoppingBag, Truck, Wrench } from 'lucide-react'
import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import StoreHeader from '../components/StoreHeader'
import StoreFooter from '../components/StoreFooter'

const categories=[
  ['ACDB','AC protection and distribution boxes','ACDB'],['DCDB','DC combiner and protection boxes','DCDB'],['MCB / MCCB','Protection devices for AC systems','MCB'],['SPD','AC and DC surge protection','SPD'],['Solar Cable','Solar DC cable and internal wiring','Solar Cable'],['Earthing Kit','Complete solar earthing solutions','Earthing'],['MC4','Solar connectors and accessories','MC4'],['Fuse System','DC fuse and fuse holders','Fuse'],['Enclosures','IP-rated PC and industrial boxes','Enclosure'],['Terminal Blocks','Internal connection systems','Terminal'],['Cable Glands','Sealed cable entry accessories','Cable Gland'],['BOS Accessories','Balance-of-system project components','BOS']
]

export default function Home(){
  const [featured,setFeatured]=useState<any[]>([])
  useEffect(()=>{supabase.from('products').select('id,name,slug,short_description,categories(name),product_variants(id,title,selling_price,stock_qty,unit)').eq('status','active').limit(4).then(({data})=>setFeatured(data||[]))},[])
  return <>
    <StoreHeader/>
    <main>
      <section className="nisHero"><div className="container nisHeroGrid"><div><span className="nisKicker"><i/>SOLAR BOS • ACDB • DCDB • PROTECTION</span><h1>Reliable solar components. <span>Built for installation.</span></h1><p className="nisHeroLead">Source ready products, configure ACDB and DCDB boxes, or submit a complete project requirement — all from one industrial solar components platform.</p><div className="nisHeroActions"><Link className="nisPrimaryBtn" href="/shop">Shop Components <ArrowRight size={18}/></Link><Link className="nisSecondaryBtn" href="/customize/dcdb">Build ACDB / DCDB</Link><Link className="nisGhostBtn" href="/bulk-order">Project RFQ</Link></div><div className="nisHeroMeta"><span><CheckCircle2 size={16}/> GST-ready ordering</span><span><CheckCircle2 size={16}/> Configurable ACDB/DCDB</span><span><CheckCircle2 size={16}/> EPC & dealer supply</span></div></div><div className="nisHeroPanel"><div className="nisPanelTop"><div><small>CONFIGURE & ORDER</small><h3>Your distribution box, your BOM.</h3></div><span className="nisLiveBadge">Live Builder</span></div><div className="nisBoxStage"><div className="nisBoxCard"><div className="nisBoxCardHead"><b>ACDB</b><span>AC Protection</span></div><div className="nisMiniRail"><i>MCB</i><i>SPD</i><i>RYB</i><i>N/E</i></div></div><div className="nisBoxCard"><div className="nisBoxCardHead"><b>DCDB</b><span>DC Protection</span></div><div className="nisMiniRail"><i>DC MCB</i><i>SPD</i><i>FUSE</i><i>TERM</i></div></div></div><div className="nisPanelBottom"><div className="nisPanelStat"><b>Component-based</b><span>Dynamic pricing structure</span></div><div className="nisPanelStat"><b>BOM snapshot</b><span>Frozen with every order</span></div><div className="nisPanelStat"><b>Project ready</b><span>Direct or bulk buying</span></div></div></div></div></section>

      <section className="nisTrustBand"><div className="container nisTrustGrid"><div className="nisTrustCard"><ShieldCheck size={22}/><b>Protection Focused</b><span>AC & DC protection components</span></div><div className="nisTrustCard"><Wrench size={22}/><b>Custom Assembly</b><span>Project-wise box configuration</span></div><div className="nisTrustCard"><PackageCheck size={22}/><b>Bulk Supply</b><span>For EPCs, dealers and installers</span></div><div className="nisTrustCard"><Truck size={22}/><b>Pan-India Dispatch</b><span>Business ordering and billing</span></div></div></section>

      <section className="nisSection"><div className="container"><div className="nisSectionHead"><div><span>PRODUCT RANGE</span><h2>Everything around solar AC/DC protection.</h2><p>Browse the component families used across residential, commercial and industrial solar installations.</p></div><Link className="nisTextLink" href="/shop">Explore all products →</Link></div><div className="nisCategoryGrid">{categories.map(([name,desc,q],i)=><Link key={name} href={`/shop?q=${encodeURIComponent(q)}`} className="nisCategoryCard"><div><div className="nisCategoryIcon">{String(i+1).padStart(2,'0')}</div><h3>{name}</h3><p>{desc}</p></div><strong>Explore →</strong></Link>)}</div></div></section>

      <section className="nisSection nisSectionSoft"><div className="container"><div className="nisSectionHead"><div><span>CUSTOM CONFIGURATION</span><h2>Build the box your site actually needs.</h2><p>Select protection, enclosure and accessories instead of being restricted to a fixed catalogue box.</p></div></div><div className="nisBuilderGrid"><article className="nisBuilderCard dark"><small>CUSTOM ACDB</small><h3>Build Your ACDB</h3><p>Configure system size, phase, enclosure, MCB/MCCB, SPD, indicators, busbar, terminals, wire and glands.</p><div className="nisBuilderSteps"><span>01 System</span><span>02 Protection</span><span>03 Accessories</span><span>04 Price</span></div><Link className="nisPrimaryBtn" href="/customize/acdb">Start ACDB Builder <ArrowRight size={17}/></Link></article><article className="nisBuilderCard green"><small>CUSTOM DCDB</small><h3>Build Your DCDB</h3><p>Configure string count, voltage, enclosure, DC MCB, SPD, fuse system, terminal blocks, cable and accessories.</p><div className="nisBuilderSteps"><span>01 Strings</span><span>02 Protection</span><span>03 Wiring</span><span>04 Price</span></div><Link className="nisPrimaryBtn" href="/customize/dcdb">Start DCDB Builder <ArrowRight size={17}/></Link></article></div></div></section>

      <section className="nisSection"><div className="container"><div className="nisSectionHead"><div><span>HOW IT WORKS</span><h2>From requirement to order in four steps.</h2></div></div><div className="nisHowGrid"><div className="nisHowCard"><span>01</span><h3>Choose</h3><p>Shop a ready product or start with the ACDB/DCDB configurator.</p></div><div className="nisHowCard"><span>02</span><h3>Configure</h3><p>Select protection devices, enclosure and project-specific accessories.</p></div><div className="nisHowCard"><span>03</span><h3>Review</h3><p>See the configured price, product variant or BOM before checkout.</p></div><div className="nisHowCard"><span>04</span><h3>Order / RFQ</h3><p>Buy online for standard quantities or submit a bulk project requirement.</p></div></div></div></section>

      {featured.length>0&&<section className="nisSection nisSectionSoft"><div className="container"><div className="nisSectionHead"><div><span>LIVE CATALOGUE</span><h2>Popular solar component options.</h2><p>Current prices are demo/reference values for system testing until the approved rate card is loaded.</p></div><Link className="nisTextLink" href="/shop">Shop all →</Link></div><div className="nisProductGrid">{featured.map(p=>{const v=p.product_variants?.[0];const price=Number(v?.selling_price||0);return <article className="nisProductCard" key={p.id}><Link href={`/product/${p.slug}`} className="nisProductVisual"/><div className="nisProductInfo"><small>{p.categories?.name||'Solar Component'}</small><h3>{p.name}</h3><p>{p.short_description||'New India Solar component for solar installation projects.'}</p><div className="nisProductPrice">{price?`₹${price.toLocaleString('en-IN')}`:'Price on request'} <span>{v?.unit||''}</span></div>{v?.stock_qty>0&&<div className="nisStock"><CheckCircle2 size={13}/> Demo stock available</div>}<Link className="nisPrimaryBtn" href={`/product/${p.slug}`}>View Product</Link></div></article>})}</div></div></section>}

      <section className="nisSection" id="why-us"><div className="container nisWhy"><div className="nisWhyVisual"><div><span className="nisKicker"><i/>NEW INDIA SOLAR</span><h3>Built around the installer’s actual workflow.</h3><p>Direct products, configurable boxes, bulk RFQs and production-ready order data are designed to work together instead of as separate systems.</p></div><div className="nisWhyMatrix"><div>ACDB / DCDB</div><div>Solar BOS</div><div>GST Billing</div><div>Project RFQ</div></div></div><div className="nisWhyList"><div className="nisWhyItem"><i><Settings2 size={20}/></i><div><h4>Dynamic component configuration</h4><p>ACDB/DCDB selections are linked to component and enclosure masters, making the system ready for real commercial pricing.</p></div></div><div className="nisWhyItem"><i><FileText size={20}/></i><div><h4>Permanent BOM snapshots</h4><p>Purchased custom configurations can retain the selected BOM and prices for historical production records.</p></div></div><div className="nisWhyItem"><i><ShoppingBag size={20}/></i><div><h4>Direct + bulk buying</h4><p>Use checkout for standard purchasing and the RFQ pipeline for large project requirements.</p></div></div><div className="nisWhyItem"><i><Boxes size={20}/></i><div><h4>One operational backend</h4><p>Products, stock, components, orders, RFQs and production views are managed from the same Supabase-backed system.</p></div></div></div></div></section>
    </main>
    <StoreFooter/>
  </>
}
