'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2, Loader2, PackagePlus, Settings2} from 'lucide-react'
import {supabase} from '../lib/supabase'
import {useCart} from './CartProvider'
import StoreHeader from './StoreHeader'
import StoreFooter from './StoreFooter'

export default function ConfiguratorBuilder({slug,title,code}:{slug:'custom-acdb'|'custom-dcdb';title:string;code:'ACDB'|'DCDB'}){
  const {add}=useCart();const [template,setTemplate]=useState<any>(null);const [groups,setGroups]=useState<any[]>([]);const [sel,setSel]=useState<Record<string,string[]>>({});const [componentPrices,setComponentPrices]=useState<Record<string,number>>({});const [enclosurePrices,setEnclosurePrices]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const {data:t}=await supabase.from('configurator_templates').select('*').eq('slug',slug).single();if(!t){setLoading(false);return}setTemplate(t);const {data:o}=await supabase.from('configurator_options').select('id,option_key,label,option_type,sort_order,required,configurator_option_values(id,label,value,price_adjustment,component_id,enclosure_id,sort_order,is_active)').eq('template_id',t.id).order('sort_order');const gs=(o||[]).map((g:any)=>({...g,configurator_option_values:(g.configurator_option_values||[]).filter((v:any)=>v.is_active).sort((a:any,b:any)=>(a.sort_order||0)-(b.sort_order||0))}));setGroups(gs);const cids=[...new Set(gs.flatMap((g:any)=>g.configurator_option_values.map((v:any)=>v.component_id).filter(Boolean)))];const eids=[...new Set(gs.flatMap((g:any)=>g.configurator_option_values.map((v:any)=>v.enclosure_id).filter(Boolean)))];if(cids.length){const {data:c}=await supabase.from('components').select('id,selling_price').in('id',cids as string[]);setComponentPrices(Object.fromEntries((c||[]).map((x:any)=>[x.id,Number(x.selling_price||0)])))}if(eids.length){const {data:e}=await supabase.from('enclosures').select('id,selling_price').in('id',eids as string[]);setEnclosurePrices(Object.fromEntries((e||[]).map((x:any)=>[x.id,Number(x.selling_price||0)])))}setLoading(false)})()},[slug])
  const selectedIds=Object.values(sel).flat();const price=useMemo(()=>{let subtotal=Number(template?.base_assembly_charge||0);for(const g of groups){for(const v of g.configurator_option_values||[]){if(selectedIds.includes(v.id))subtotal+=Number(v.price_adjustment||0)+Number(componentPrices[v.component_id]||0)+Number(enclosurePrices[v.enclosure_id]||0)}}return Math.round(subtotal*1.18)},[template,groups,sel,componentPrices,enclosurePrices]);const requiredGroups=groups.filter(g=>g.required);const completedRequired=requiredGroups.filter(g=>(sel[g.option_key]||[]).length>0).length;const ready=requiredGroups.length>0&&completedRequired===requiredGroups.length
  function choose(g:any,v:any){const multi=g.option_type==='multi'||g.option_key==='extras'||g.option_key==='indicator'||g.option_key==='busbar';setSel(s=>{const current=s[g.option_key]||[];return {...s,[g.option_key]:multi?(current.includes(v.id)?current.filter(x=>x!==v.id):[...current,v.id]):[v.id]}})}
  function addBuild(){if(!ready||!template)return;const labels:string[]=[];for(const g of groups){const ids=sel[g.option_key]||[];const vals=(g.configurator_option_values||[]).filter((v:any)=>ids.includes(v.id));if(vals.length)labels.push(`${g.label}: ${vals.map((v:any)=>v.label).join(', ')}`)}add({id:`${code.toLowerCase()}-${Date.now()}`,kind:'custom',name:`Custom ${code}`,variant:labels.join(' • '),price,qty:1,customType:code.toLowerCase() as any,templateId:template.id,selectedValueIds:selectedIds})}
  if(loading)return <><StoreHeader/><main className="container builderLoading"><Loader2 className="spin"/><h2>Loading {code} builder…</h2></main></>
  if(!template)return <><StoreHeader/><main className="container emptyCatalogue"><h1>Configurator unavailable.</h1><Link className="btn btnPrimary" href="/shop">Browse Products</Link></main></>
  return <><StoreHeader/><main className="container builderPage premiumBuilder"><section className="builderForm"><div className="builderIntro"><span className="eyebrow darkEye">BUILD YOUR OWN {code}</span><h1>{title}</h1><p>Select the enclosure, protection and accessories required by your site. Demo pricing is calculated from the current Supabase component master.</p><div className="builderProgress"><div><span>Required selections</span><b>{completedRequired}/{requiredGroups.length}</b></div><div className="builderProgressBar"><i style={{width:`${requiredGroups.length?completedRequired/requiredGroups.length*100:0}%`}}/></div></div></div>{groups.map((g:any,index:number)=><div className="optionGroup premiumOptionGroup" key={g.id}><div className="optionTitle"><span>{String(index+1).padStart(2,'0')}</span><div><h3>{g.label}{g.required?' *':''}</h3><p>{g.required?'Required selection':'Optional — add if needed'}</p></div>{(sel[g.option_key]||[]).length>0&&<CheckCircle2 size={18}/>}</div><div className="chips">{(g.configurator_option_values||[]).map((v:any)=>{const active=(sel[g.option_key]||[]).includes(v.id);const addon=Number(v.price_adjustment||0)+Number(componentPrices[v.component_id]||0)+Number(enclosurePrices[v.enclosure_id]||0);return <button type="button" key={v.id} className={active?'active':''} onClick={()=>choose(g,v)}><b>{v.label}</b>{addon>0&&<small>₹{addon.toLocaleString('en-IN')}</small>}</button>})}</div></div>)}</section><aside className="configSummary premiumConfigSummary"><div className="configTop"><span><Settings2 size={16}/> LIVE CONFIGURATION</span><b>{code}</b></div><div className="visualBox"><b>NEW INDIA SOLAR {code}</b><span>Dynamic component layout preview</span><div className="rail"><i>MCB</i><i>SPD</i><i>{code==='DCDB'?'FUSE':'RYB'}</i><i>TERM</i></div></div><h2>Your Configuration</h2>{selectedIds.length?groups.map((g:any)=>{const ids=sel[g.option_key]||[];const names=(g.configurator_option_values||[]).filter((v:any)=>ids.includes(v.id)).map((v:any)=>v.label);return names.length?<div className="sumRow" key={g.id}><span>{g.label}</span><b>{names.join(', ')}</b></div>:null}):<p className="emptyText">Start selecting options to build your BOM.</p>}<div className="livePrice"><span>Demo Price incl. GST</span><b>₹{price.toLocaleString('en-IN')}</b><small>Reference price for website testing</small></div><button className="nisPrimaryBtn configAddBtn" disabled={!ready} onClick={addBuild}><PackagePlus size={18}/>{ready?'Add Configuration to Cart':'Complete Required Options'}</button><Link className="bulkLink" href="/bulk-order">Need multiple boxes? Get project price →</Link></aside></main><StoreFooter/></>
}
