'use client'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {useEffect,useMemo,useRef,useState} from 'react'
import {CheckCircle2,Download,Expand,Minus,Plus,RotateCcw,Save,X} from 'lucide-react'
import {supabase} from '../lib/supabase'
import {imageSource,spriteFor} from '../lib/configurator-visuals'
import {exportBuilder} from '../lib/export-builder'
import {Catalog,Selection,BuilderCode,defaults,fileDownload,indexValues,presetSelection,previewLayers,readDraft,references,selectionIssues,summary,uploadedCatalog} from '../lib/builder-buyer'
import {loadBuilderCatalogue,reconcileSelection} from '../lib/builder-catalogue'
import ComponentSprite from './ComponentSprite'
import QuantityControl from './buyer/QuantityControl'
import StoreHeader from './StoreHeader'
import StoreFooter from './StoreFooter'
import '../app/builder-buyer.css'

export default function ConfiguratorBuilder({slug,title,code,assetPreview=false}:{slug:'custom-acdb'|'custom-dcdb';title:string;code:BuilderCode;assetPreview?:boolean}){
 const base=useMemo(()=>assetPreview?uploadedCatalog(code):{template:null,groups:[],components:{},enclosures:{},slots:[]} as Catalog,[code,assetPreview]),router=useRouter()
 const [data,setData]=useState<Catalog>(base),[selection,setSelection]=useState<Selection>(()=>defaults(base)),[reference,setReference]=useState('')
 const [source,setSource]=useState(assetPreview?'Visual sample — not the published catalogue':'Loading catalogue'),[checking,setChecking]=useState(!assetPreview),[attempt,setAttempt]=useState(0)
 const [catalogueError,setCatalogueError]=useState(''),[catalogueLoaded,setCatalogueLoaded]=useState(assetPreview)
 const [notice,setNotice]=useState(''),[exporting,setExporting]=useState(false),[draftAvailable,setDraftAvailable]=useState(false),[imageVersion,setImageVersion]=useState(0)
 const [expanded,setExpanded]=useState(false),[zoom,setZoom]=useState(1)
 const dirty=useRef(false),dialog=useRef<HTMLDialogElement>(null),expandButton=useRef<HTMLButtonElement>(null),mobileBar=useRef<HTMLDivElement>(null)
 const storageKey=`nis-builder-draft-v2-${code}`
 useEffect(()=>{try{setDraftAvailable(!!readDraft(localStorage.getItem(storageKey),data,code))}catch{}},[data,code,storageKey])
 useEffect(()=>{
  if(assetPreview){setChecking(false);return}
  let disposed=false;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000)
  setChecking(true)
  ;(async()=>{
   const catalog=await loadBuilderCatalogue(supabase,slug,controller.signal)
   if(!disposed){setData(catalog);setSelection(previous=>dirty.current?reconcileSelection(catalog,previous):defaults(catalog));setReference('');setCatalogueLoaded(true);setCatalogueError('');setSource('Published component catalogue')}
  })().catch((error)=>{if(!disposed){setCatalogueLoaded(false);setCatalogueError(error instanceof Error?error.message:'Could not load the published catalogue. Please retry.');setSource('Catalogue unavailable')}}).finally(()=>{clearTimeout(timer);if(!disposed)setChecking(false)})
  return()=>{disposed=true;controller.abort();clearTimeout(timer)}
 },[slug,code,assetPreview,attempt])
 useEffect(()=>{
  const body=document.body,html=document.documentElement,oldPadding=body.style.paddingBottom,oldScroll=html.style.scrollPaddingBottom
  const update=()=>{const h=mobileBar.current?.getBoundingClientRect().height||0;body.style.paddingBottom=h?`${h}px`:oldPadding;html.style.scrollPaddingBottom=h?`${h+12}px`:oldScroll}
  const observer=new ResizeObserver(update);if(mobileBar.current)observer.observe(mobileBar.current);update()
  return()=>{observer.disconnect();body.style.paddingBottom=oldPadding;html.style.scrollPaddingBottom=oldScroll}
 },[])
 useEffect(()=>{if(!expanded)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[expanded])
 const values=useMemo(()=>indexValues(data),[data]),layers=useMemo(()=>previewLayers(data,selection),[data,selection])
 const enclosure=data.enclosures[values[selection.enclosure?.[0]?.id]?.enclosure_id]
 const issues=useMemo(()=>selectionIssues(data,selection,code),[data,selection,code]),ready=catalogueLoaded&&!checking&&issues.length===0
 const required=data.groups.filter(g=>g.required),complete=required.filter(g=>selection[g.option_key]?.length).length
 function change(g:any,v:any){if(checking||!catalogueLoaded)return;dirty.current=true;setReference('');setNotice('');setSelection(s=>{const current=s[g.option_key]||[],exists=current.some(p=>p.id===v.id),qty=Math.min(Number(g.max_quantity)||1,Math.max(Number(g.min_quantity)||1,Number(v.metadata?.default_quantity)||1));return {...s,[g.option_key]:g.option_type==='multi'?(exists?current.filter(p=>p.id!==v.id):[...current,{id:v.id,qty}]):exists&&!g.required?[]:[{id:v.id,qty}]}})}
 function quantity(g:any,id:string,next:number){dirty.current=true;setReference('');setSelection(s=>({...s,[g.option_key]:(s[g.option_key]||[]).map(p=>p.id===id?{...p,qty:Math.max(Number(g.min_quantity)||1,Math.min(Number(g.max_quantity)||1,next))}:p)}))}
 function applyReference(id:string){const next=presetSelection(data,code,id);if(!next){setNotice('That reference is not available in this component catalogue.');return}dirty.current=true;setSelection(next);setReference(id);setNotice(`Reference ${code}-${id} loaded. This is a visual draft, not electrical approval.`)}
 function reset(){dirty.current=true;setSelection(defaults(data));setReference('');setZoom(1);setNotice('Default component arrangement restored. Your saved draft is unchanged.')}
 function save(){if(!ready)return;try{localStorage.setItem(storageKey,JSON.stringify({version:2,code,selection,reference,savedAt:Date.now()}));setDraftAvailable(true);setNotice('Draft saved on this device. Submit Request quotation with your contact details to send it to our admin team.')}catch{setNotice('This browser could not save the draft. Download the component list instead.')}}
 function restore(){try{const draft=readDraft(localStorage.getItem(storageKey),data,code);if(!draft){setNotice('The saved draft is expired or no longer matches the available components.');return}dirty.current=true;setSelection(draft.selection);setReference(draft.reference);setNotice('Saved draft restored.')}catch{setNotice('Browser storage is unavailable.')}}
 function enquire(){if(!ready)return;try{const id=crypto.randomUUID(),text=summary(data,selection,code,reference),draft={version:1,product:code,summary:text,selections:selection,templateId:data.template?.id,catalogueSource:assetPreview?'sample':'published',createdAt:Date.now()};sessionStorage.setItem(`nis-builder-rfq-${id}`,JSON.stringify(draft));router.push(`/bulk-order?source=builder&draft=${id}`)}catch{setNotice('Could not carry your selection to the enquiry form. Download the component list and paste it into your requirement.')}}
 function downloadBom(){fileDownload(summary(data,selection,code,reference),`New-India-Solar-${code}-BOM.txt`)}
 async function download(){if(!ready||!enclosure||exporting)return;setExporting(true);setNotice('');try{await exportBuilder(enclosure,layers,code);setNotice('PNG prepared from your selected components. It is a visual preview, not a wiring drawing.')}catch(e){setNotice(e instanceof Error?e.message:'Preview export failed. Please retry.')}finally{setExporting(false)}}
 function openPreview(){setZoom(1);dialog.current?.showModal();setExpanded(true)}
 function stage(modal=false){return <div className="bbStage" data-testid={modal?'expanded-stage':'builder-stage'} style={modal?{width:`calc(min(100%, (94dvh - 144px) * .75) * ${zoom})`,maxWidth:'none'}:undefined}><div className="bbEnclosure">{enclosure&&<ComponentSprite key={`${imageVersion}-${enclosure.id}`} src={imageSource(enclosure)} alt={enclosure.name} sprite={spriteFor(enclosure.visual_settings)}/>}</div>{layers.map(l=><div key={`${imageVersion}-${l.key}`} className="bbLayer" data-asset={l.component.visual_settings?.asset_id} data-slot={l.slot.option_key} style={{left:`${l.slot.x_pct}%`,top:`${l.slot.y_pct}%`,width:`${l.slot.width_pct}%`,height:`${l.slot.height_pct}%`,zIndex:l.slot.z_index,transform:`rotate(${l.slot.rotation_deg||0}deg)`}}><ComponentSprite src={imageSource(l.component)} alt={l.component.name} sprite={spriteFor(l.component.visual_settings)} fit={l.slot.settings?.fit}/></div>)}</div>}
 return <><StoreHeader/><main id="main-content" className="bbPage container" data-builder-code={code}>
  <nav className="bbBreadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/customize">Custom boxes</Link><span>› {code}</span></nav>
  <header className="bbHeading"><div><span className="nisEyebrow">VISUAL QUOTATION BUILDER</span><h1>{title}</h1><p>Choose components, review the assembled preview and send your exact selection for a quotation.</p></div><div className="bbActions"><button onClick={reset}><RotateCcw size={16}/>Reset</button><button onClick={save} disabled={!ready}><Save size={16}/>Save draft</button>{draftAvailable&&<button onClick={restore}>Restore draft</button>}</div></header>
  <div className="bbStatus"><span>{checking?'Checking published catalogue…':source}</span><button onClick={()=>{setAttempt(n=>n+1);setImageVersion(n=>n+1)}} disabled={checking}>Refresh catalogue / images</button></div>
  {notice&&<p className="bbNotice" role="status">{notice}</p>}
  {catalogueError&&<p className="bbNotice" role="alert">{catalogueError} <Link href="/bulk-order">Request a quotation</Link></p>}
  <div className="bbLayout"><aside className="bbPreview"><div className="bbPreviewHead"><div><b>Your {code} preview</b><small>SPD left · breaker centre · terminals right</small></div><button ref={expandButton} onClick={openPreview} aria-label="Enlarge box preview"><Expand size={20}/></button></div><div className="bbPreviewImage">{stage()}</div><div className="bbPreviewFoot"><span>1 in / 1 out visual layout</span><button onClick={download} disabled={!ready||exporting}><Download size={16}/>{exporting?'Preparing…':'Download PNG'}</button></div><p className="bbDisclaimer">Visual assembly only. Markings, wiring, physical fit and electrical suitability must be reviewed before manufacture or installation.</p></aside>
  <section className="bbOptions" aria-label="Component selections">{assetPreview&&<div className="bbReference"><label htmlFor="builder-reference">Start from an uploaded reference</label><select id="builder-reference" value={reference} onChange={e=>e.target.value?applyReference(e.target.value):setReference('')}><option value="">Custom / default arrangement</option>{references(code).map(r=><option key={r.id} value={r.id}>{code}-{r.id} · {r.spd.split('-spd-')[1]} + {r.mcb.split('-mcb-')[1]}</option>)}{code==='ACDB'&&<option disabled value="14">ACDB-14 excluded — source contains DC components</option>}</select><small>{code==='ACDB'?'20 AC visual references. Reference 14 is excluded; 07 and 16 intentionally repeat the source combination.':'16 complete DC reference images recovered. References 17–20 await the complete ZIP.'}</small></div>}
   <div className="bbProgress" role="status">Required selections: {complete} / {required.length}</div>
   {data.groups.map((g,index)=><details className="bbGroup" key={g.id} open data-group={g.option_key}><summary><span>{String(index+1).padStart(2,'0')}</span><b>{g.label}{g.required?' *':''}</b><small>{selection[g.option_key]?.length||0} selected</small></summary><p>{g.option_type==='multi'?'Select any visual layers to include.':'Select one component assembly.'}{!g.required?' Optional: select again to remove.':''}</p><div className="bbChoices">{g.configurator_option_values.map((v:any)=>{const item=data.components[v.component_id]||data.enclosures[v.enclosure_id],pick=selection[g.option_key]?.find(s=>s.id===v.id);return <article className={`bbChoice ${pick?'selected':''}`} key={v.id}><button className="bbSelect" aria-pressed={!!pick} disabled={checking||!catalogueLoaded} onClick={()=>change(g,v)} data-value={v.id} data-asset={item?.visual_settings?.asset_id}><span className="bbThumbnail">{item&&<ComponentSprite key={`${imageVersion}-${item.id}`} src={imageSource(item)} alt={v.label} sprite={spriteFor(item.visual_settings)}/>}</span><span><b>{v.label}</b><small>Price and availability on quotation</small></span>{pick&&<CheckCircle2 size={18}/>}</button>{pick&&g.allow_quantity&&<QuantityControl value={pick.qty} min={Math.max(1,Number(g.min_quantity)||1)} max={Number(g.max_quantity)||1} label={`${v.label} quantity`} onChange={q=>quantity(g,v.id,q)}/>}</article>})}</div></details>)}
  </section>
  <aside className="bbSummary"><h2>Your component list</h2><dl>{data.groups.flatMap(g=>(selection[g.option_key]||[]).map(s=><div key={s.id}><dt>{g.label}</dt><dd>{values[s.id]?.label} <b>× {s.qty}</b></dd></div>))}</dl><p className="bbQuote">Price on quotation</p><p>Component images are available; selling prices and engineering approval are not yet confirmed. This flow creates a requirement, not a purchase.</p>{issues.length>0&&<div className="bbIssues" role="alert">{issues.map(i=><p key={i}>{i}</p>)}</div>}<button className="bbPrimary" disabled={!ready} onClick={enquire}>Request quotation</button><button onClick={downloadBom} disabled={!ready}><Download size={16}/>Download component list</button><small>Wire images represent illustrative routes, not cable lengths. A complete manufacturing BOM is confirmed with your quotation.</small></aside></div>
  <div className="bbMobileBar" ref={mobileBar}><button className="bbMobileView" onClick={openPreview}><Expand size={17}/><span>View {code}<small>Price on quotation</small></span></button><button className="bbPrimary" disabled={!ready} onClick={enquire}>Request quotation</button></div>
  <dialog className="bbDialog" ref={dialog} aria-label={`${code} enlarged preview`} aria-modal="true" onClose={()=>{setExpanded(false);expandButton.current?.focus({preventScroll:true})}} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}} onKeyDown={e=>{if(e.key!=='Tab')return;const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}><header><b>Your {code} preview</b><button autoFocus onClick={()=>dialog.current?.close()} aria-label="Close preview"><X size={21}/></button></header><div className="bbDialogViewport">{stage(true)}</div><footer><button onClick={()=>setZoom(z=>Math.max(1,Math.round((z-.25)*100)/100))} disabled={zoom<=1} aria-label="Zoom out"><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2,Math.round((z+.25)*100)/100))} disabled={zoom>=2} aria-label="Zoom in"><Plus size={18}/></button><button onClick={download} disabled={!ready||exporting}><Download size={17}/>{exporting?'Preparing…':'Download PNG'}</button></footer></dialog>
 </main><StoreFooter/></>
}
