'use client'

import Link from 'next/link'
import {ArrowRight,Boxes,Cable,CheckCircle2,CircleGauge,FileText,Gauge,Layers3,PackageCheck,PlugZap,SearchCheck,Settings2,ShieldCheck,ShoppingCart,Sparkles,Truck,Wrench,Zap} from 'lucide-react'
import StoreHeader from './StoreHeader'
import StoreFooter from './StoreFooter'
import {useSiteContent} from './SiteContentProvider'

const iconMap:any={zap:Zap,shield:ShieldCheck,gauge:CircleGauge,plug:PlugZap,cable:Cable,layers:Layers3,settings:Settings2,boxes:Boxes,wrench:Wrench,package:PackageCheck,sparkles:Sparkles,file:FileText,truck:Truck}
const fallbackCollections=[
{name:'ACDB',desc:'AC protection & distribution',href:'/shop?q=ACDB',icon:'zap'},{name:'DCDB',desc:'DC combiner & protection',href:'/shop?q=DCDB',icon:'shield'},{name:'MCB / MCCB',desc:'AC & DC circuit protection',href:'/shop?q=MCB',icon:'gauge'},{name:'SPD',desc:'Surge protection devices',href:'/shop?q=SPD',icon:'plug'},{name:'Solar Cable',desc:'DC cable & internal wiring',href:'/shop?q=Solar%20Cable',icon:'cable'},{name:'Earthing Kit',desc:'Solar earthing solutions',href:'/shop?q=Earthing',icon:'layers'},{name:'MC4',desc:'PV connectors & accessories',href:'/shop?q=MC4',icon:'settings'},{name:'DC Fuse',desc:'Fuse links & fuse holders',href:'/shop?q=Fuse',icon:'gauge'},{name:'Enclosures',desc:'IP-rated industrial boxes',href:'/shop?q=Enclosure',icon:'boxes'},{name:'Terminal Blocks',desc:'Internal connection systems',href:'/shop?q=Terminal',icon:'wrench'},{name:'Cable Glands',desc:'Sealed cable entry systems',href:'/shop?q=Cable%20Gland',icon:'package'},{name:'BOS Accessories',desc:'Project-ready solar BOS',href:'/shop?q=BOS',icon:'sparkles'}]

export default function HomePageContent(){
 const {home}=useSiteContent();const hero=home?.hero||{};const collections=(home?.featured_collections?.length?home.featured_collections:fallbackCollections);const visibility=home?.visibility||{};const order=home?.section_order||['trust','collections','builder','buyways','why','final']
 const sections:any={
 trust:<section className="hvTrust" aria-label="Business capabilities"><div className="container hvTrustGrid"><div><ShieldCheck/><span><b>Protection Focused</b><small>AC & DC solar components</small></span></div><div><Settings2/><span><b>Custom Configuration</b><small>Component-based box builder</small></span></div><div><PackageCheck/><span><b>Project Supply</b><small>Direct and bulk requirements</small></span></div><div><Truck/><span><b>Pan-India Dispatch</b><small>Business ordering workflow</small></span></div></div></section>,
 collections:<section className="hvSection hvCategories" aria-labelledby="categories-title"><div className="container"><div className="hvSectionHead"><div><span>FEATURED COLLECTIONS</span><h2 id="categories-title">{home.collections_heading}</h2><p>{home.collections_body}</p></div><Link href="/shop">View all products <ArrowRight size={17}/></Link></div><div className="hvCategoryGrid">{collections.map((c:any,i:number)=>{const Icon=iconMap[c.icon]||Sparkles;return <Link key={`${c.name}-${i}`} prefetch={false} href={c.href||'/shop'} className="hvCategoryCard"><span className="hvCategoryIcon"><Icon/></span><div><h3>{c.name}</h3><p>{c.desc}</p></div><ArrowRight className="hvCategoryArrow"/></Link>})}</div></div></section>,
 builder:<section className="hvSection hvBuildSection" aria-labelledby="builder-title"><div className="container"><div className="hvSectionHead compact"><div><span>CUSTOM CONFIGURATION</span><h2 id="builder-title">{home.builder_heading}</h2><p>{home.builder_body}</p></div></div><div className="hvBuilderGrid"><article className="hvBuilderCard hvBuilderDark"><div className="hvBuilderTop"><span>ACDB BUILDER</span><i>AC</i></div><h3>Configure your ACDB.</h3><p>Choose system size, phase, MCB/MCCB, SPD, indicators, busbar, terminals, internal wiring and enclosure.</p><div className="hvStepRow"><span>01 System</span><span>02 Protection</span><span>03 Accessories</span><span>04 Review</span></div><Link className="hvBtn hvBtnPrimary" href="/customize/acdb">Start ACDB Builder <ArrowRight size={17}/></Link></article><article className="hvBuilderCard hvBuilderGreen"><div className="hvBuilderTop"><span>DCDB BUILDER</span><i>DC</i></div><h3>Configure your DCDB.</h3><p>Choose string count, voltage, DC MCB, SPD, fuse system, terminals, solar cable, glands and enclosure.</p><div className="hvStepRow"><span>01 Strings</span><span>02 Protection</span><span>03 Wiring</span><span>04 Review</span></div><Link className="hvBtn hvBtnPrimary" href="/customize/dcdb">Start DCDB Builder <ArrowRight size={17}/></Link></article></div></div></section>,
 buyways:<section className="hvSection hvBuyWays" aria-labelledby="buyways-title"><div className="container"><div className="hvSectionHead"><div><span>BUY THE WAY YOUR PROJECT NEEDS</span><h2 id="buyways-title">{home.buyways_heading}</h2><p>{home.buyways_body}</p></div></div><div className="hvBuyGrid"><article><span>01</span><ShoppingCart/><h3>Direct Purchase</h3><p>Choose ready catalogue products, select quantity and place a GST-ready order.</p><Link href="/shop">Shop products <ArrowRight/></Link></article><article><span>02</span><Settings2/><h3>Custom Build</h3><p>Configure ACDB/DCDB component by component and save the final BOM with your order.</p><Link href="/customize/dcdb">Open builder <ArrowRight/></Link></article><article><span>03</span><FileText/><h3>Bulk / Project RFQ</h3><p>Share quantity, location and project requirement for volume and project-specific pricing.</p><Link href="/bulk-order">Send requirement <ArrowRight/></Link></article></div></div></section>,
 why:<section className="hvSection hvWhy" id="why-us" aria-labelledby="why-title"><div className="container hvWhyGrid"><div className="hvWhyIntro"><span>WHY NEW INDIA SOLAR</span><h2 id="why-title">{home.why_heading}</h2><p>{home.why_body}</p><Link className="hvBtn hvBtnDark" href="/shop">Explore the catalogue <ArrowRight size={17}/></Link></div><div className="hvWhyCards"><article className="wide"><SearchCheck/><div><h3>Clear component selection</h3><p>Choose protection and BOS components with structured specifications instead of relying on unstructured messages.</p></div></article><article><Settings2/><div><h3>Dynamic configuration</h3><p>Build ACDB/DCDB from enclosure and component options.</p></div></article><article><FileText/><div><h3>BOM snapshots</h3><p>Custom orders retain selected component and pricing data.</p></div></article><article><ShieldCheck/><div><h3>Business-ready ordering</h3><p>GST details, project buying and bulk enquiry flows in one place.</p></div></article><article><Truck/><div><h3>Operations connected</h3><p>Orders, RFQs, stock and production views use the same backend.</p></div></article></div></div></section>,
 final:<section className="hvFinal"><div className="container hvFinalInner"><div><span>{home.final_eyebrow}</span><h2>{home.final_heading}</h2></div><div><Link className="hvBtn hvBtnLight" href="/shop">Shop Components</Link><Link className="hvBtn hvBtnPrimary" href="/bulk-order">Request Project Pricing <ArrowRight size={17}/></Link></div></div></section>
 }
 return <><StoreHeader/><main id="main-content" className="homeV2"><section className="hvHero" aria-labelledby="home-hero-title"><div className="container hvHeroGrid"><div className="hvHeroCopy"><span className="hvEyebrow"><i/> {hero.eyebrow}</span><h1 id="home-hero-title">{String(hero.title||'').replace(hero.highlight||'','')} {hero.highlight&&<em>{hero.highlight}</em>}</h1><p>{hero.body}</p><div className="hvActions"><Link className="hvBtn hvBtnPrimary" href={hero.primary_href||'/shop'}>{hero.primary_label||'Shop Components'} <ArrowRight size={18}/></Link><Link className="hvBtn hvBtnLight" href={hero.secondary_href||'/customize/dcdb'}>{hero.secondary_label||'Build ACDB / DCDB'}</Link><Link className="hvBtn hvBtnGhost" href={hero.tertiary_href||'/bulk-order'}>{hero.tertiary_label||'Project RFQ'}</Link></div><div className="hvProof" aria-label="Ordering benefits">{(hero.proof||[]).map((x:string)=><span key={x}><CheckCircle2/> {x}</span>)}</div></div><div className="hvHeroVisual" aria-label="New India Solar procurement workflow preview">{hero.banner_image_url&&<img className="hvCmsBanner" src={hero.banner_image_url} alt="New India Solar"/>}<div className="hvVisualHead"><div><small>NEW INDIA SOLAR</small><b>Project Procurement</b></div><span>LIVE</span></div><div className="hvVisualMetric"><div><small>Choose your flow</small><strong>Product → Configure → Order</strong></div><CircleGauge/></div><div className="hvVisualCards"><Link href="/shop?q=ACDB"><span><Zap/></span><div><b>ACDB</b><small>Ready products</small></div><ArrowRight/></Link><Link href="/customize/dcdb"><span><Settings2/></span><div><b>Custom DCDB</b><small>Build your BOM</small></div><ArrowRight/></Link><Link href="/bulk-order"><span><FileText/></span><div><b>Bulk RFQ</b><small>Project pricing</small></div><ArrowRight/></Link></div><div className="hvVisualBottom"><span><ShieldCheck/> Tested. Packed. Guaranteed.</span><span>newindiasolar.com</span></div></div></div></section>{order.map((key:string)=>visibility[key]===false?null:<div key={key}>{sections[key]}</div>)}</main><StoreFooter/></>
}
