'use client'

import Link from 'next/link'
import {
  ArrowRight, Boxes, Cable, Check, CheckCircle2, CircleGauge, Download,
  FileText, Headphones, Layers3, PackageCheck, PlugZap, SearchCheck,
  Settings2, ShieldCheck, ShoppingCart, Sparkles, Truck, Wrench, Zap,
} from 'lucide-react'
import StoreHeader from './StoreHeader'
import StoreFooter from './StoreFooter'
import {useSiteContent} from './SiteContentProvider'
import {HomeFeaturedProducts, HomeResources, HomeProductImage} from './HomeHighlights'
import {normalizeHomeSections, publicAssetUrl, type HomeProduct, type HomeDownload} from '../lib/homepage-sections'

const iconMap:any={zap:Zap,shield:ShieldCheck,gauge:CircleGauge,plug:PlugZap,cable:Cable,layers:Layers3,settings:Settings2,boxes:Boxes,wrench:Wrench,package:PackageCheck,sparkles:Sparkles,file:FileText,truck:Truck}
const fallbackCollections=[
 {name:'ACDB',desc:'Single and three-phase AC protection',href:'/shop?q=ACDB',icon:'zap',image:'/acdb-demo.svg',tag:'AC PROTECTION'},
 {name:'DCDB',desc:'String protection and DC combining',href:'/shop?q=DCDB',icon:'shield',image:'/dcdb-demo.svg',tag:'DC PROTECTION'},
 {name:'MCB / MCCB',desc:'AC and DC circuit protection',href:'/shop?q=MCB',icon:'gauge',image:'/mcb-demo.svg',tag:'SWITCHGEAR'},
 {name:'SPD',desc:'Type 1, Type 2 and DC surge protection',href:'/shop?q=SPD',icon:'plug',image:'/spd-demo.svg',tag:'SURGE PROTECTION'},
 {name:'Solar Cable',desc:'DC solar cable and internal wiring',href:'/shop?q=Solar%20Cable',icon:'cable',image:'/cable-demo.svg',tag:'CABLE & WIRE'},
 {name:'Earthing Kit',desc:'Rods, lugs, clamps and accessories',href:'/shop?q=Earthing',icon:'layers',image:'/earthing-demo.svg',tag:'EARTHING'},
 {name:'MC4',desc:'PV connectors, tools and accessories',href:'/shop?q=MC4',icon:'settings',image:'/mc4-demo.svg',tag:'CONNECTORS'},
 {name:'DC Fuse',desc:'Fuse links and fuse holders',href:'/shop?q=Fuse',icon:'gauge',image:'/fuse-demo.svg',tag:'FUSE SYSTEMS'},
 {name:'Enclosures',desc:'IP-rated industrial enclosures',href:'/shop?q=Enclosure',icon:'boxes',tag:'ENCLOSURES'},
 {name:'Terminal Blocks',desc:'Internal connection systems',href:'/shop?q=Terminal',icon:'wrench',tag:'INTERNAL PARTS'},
 {name:'Cable Glands',desc:'Sealed cable-entry systems',href:'/shop?q=Cable%20Gland',icon:'package',image:'/gland-demo.svg',tag:'ACCESSORIES'},
 {name:'BOS Accessories',desc:'Project-ready balance of system range',href:'/shop?q=BOS',icon:'sparkles',tag:'COMPLETE BOS'},
]

const imageByName:Record<string,string>={acdb:'/acdb-demo.svg',dcdb:'/dcdb-demo.svg',mcb:'/mcb-demo.svg',mccb:'/mcb-demo.svg',spd:'/spd-demo.svg',cable:'/cable-demo.svg',earthing:'/earthing-demo.svg',mc4:'/mc4-demo.svg',fuse:'/fuse-demo.svg'}
const getCollectionImage=(item:any)=>publicAssetUrl(item.image)||(/gland/i.test(item.name||'')?'/gland-demo.svg':undefined)||Object.entries(imageByName).find(([key])=>String(item.name||'').toLowerCase().includes(key))?.[1]

function HeroTitle({title,highlight}:{title:string;highlight:string}){
 if(!highlight||!title.includes(highlight))return <>{title}</>
 const index=title.indexOf(highlight)
 return <>{title.slice(0,index)}<em>{highlight}</em>{title.slice(index+highlight.length)}</>
}


export default function HomePageContent({products=[], downloads=[], productsUnavailable=false}: {products?: HomeProduct[]; downloads?: HomeDownload[]; productsUnavailable?: boolean}){
 const {home}=useSiteContent()
 const hero=home?.hero||{}
 const collections=(home?.featured_collections?.length?home.featured_collections:fallbackCollections)
 const visibility=home?.visibility||{}
 const order=normalizeHomeSections(home?.section_order)
 const title=String(hero.title||'Solar components built to move projects faster.')
 const highlight=String(hero.highlight||'move projects faster.')

 const sections:any={
  products:<HomeFeaturedProducts products={products} unavailable={productsUnavailable}/>,
  downloads:<HomeResources downloads={downloads}/>,
  project:<section className="hvSection hvProject" aria-labelledby="home-project-title"><div className="container hvProjectGrid"><div><span className="hvResourceEyebrow">FOR EPCs, DEALERS & INSTALLERS</span><h2 id="home-project-title">One requirement. A clearer project quotation.</h2><p>Share the protection boxes and BOS components your installation needs, with quantities, preferred ratings and the project location.</p><Link className="hvBtn hvBtnPrimary" href="/bulk-order">Get a project quote <ArrowRight size={17}/></Link></div><ol className="hvProjectChecklist"><li><b>01 · Product & ratings</b><span>ACDB, DCDB, switchgear, cable or a complete BOS requirement.</span></li><li><b>02 · Quantities & location</b><span>Tell us the required quantity and delivery city.</span></li><li><b>03 · Purchase timeline</b><span>Include the expected purchase date and any preferred brands.</span></li></ol></div></section>,
  trust:<section className="hvTrust" aria-label="Procurement advantages"><div className="container hvTrustGrid"><div><ShieldCheck/><span><b>Protection focused</b><small>AC and DC solar components</small></span></div><div><Settings2/><span><b>Built to requirement</b><small>Configurable ACDB and DCDB</small></span></div><div><PackageCheck/><span><b>Project procurement</b><small>Direct order and bulk RFQ</small></span></div><div><Headphones/><span><b>Technical buying support</b><small>Structured component selection</small></span></div></div></section>,
  collections:<section className="hvSection hvCategories" aria-labelledby="categories-title"><div className="container"><div className="hvSectionHead"><div><span>COMPLETE SOLAR BOS RANGE</span><h2 id="categories-title">{home.collections_heading}</h2><p>{home.collections_body}</p></div><Link href="/shop">Explore full catalogue <ArrowRight size={17}/></Link></div><div className="hvCategoryGrid">{collections.map((c:any,i:number)=>{const Icon=iconMap[c.icon]||Sparkles;return <Link key={`${c.name}-${i}`} prefetch={false} href={c.href||'/shop'} className="hvCategoryCard"><div className="hvCategoryMedia"><HomeProductImage src={getCollectionImage(c)} alt={`${c.name} category illustration`}/><span>{c.tag||'SOLAR BOS'}</span></div><div className="hvCategoryCopy"><span className="hvCategoryIcon"><Icon/></span><div><h3>{c.name}</h3><p>{c.desc}</p></div><ArrowRight className="hvCategoryArrow"/></div></Link>})}</div></div></section>,
  builder:<section className="hvSection hvBuildSection" aria-labelledby="builder-title"><div className="container"><div className="hvSectionHead hvBuildHead"><div><span>CONFIGURE. REVIEW. ORDER.</span><h2 id="builder-title">{home.builder_heading}</h2><p>{home.builder_body}</p></div><div className="hvBuildAssurance"><CheckCircle2/><span><b>Component-level control</b><small>Final configuration keeps its selected BOM.</small></span></div></div><div className="hvBuilderGrid"><article className="hvBuilderCard hvBuilderDark"><div className="hvBuilderContent"><div className="hvBuilderTop"><span>AC DISTRIBUTION BOX</span><i>ACDB</i></div><h3>Build your AC protection box.</h3><p>Select phase, system capacity, MCB or MCCB, SPD, indicators, terminals, internal wiring and enclosure.</p><div className="hvSpecPills"><span>Single / Three Phase</span><span>MCB / MCCB</span><span>SPD selection</span></div><Link className="hvBtn hvBtnPrimary" href="/customize/acdb">Configure ACDB <ArrowRight size={17}/></Link></div><div className="hvBuilderProduct"><HomeProductImage src="/acdb-demo.svg" alt="Illustrative ACDB box"/></div></article><article className="hvBuilderCard hvBuilderLight"><div className="hvBuilderContent"><div className="hvBuilderTop"><span>DC COMBINER BOX</span><i>DCDB</i></div><h3>Build your DC string protection.</h3><p>Select string count, system voltage, DC MCB, SPD, fuse system, terminals, solar cable, glands and enclosure.</p><div className="hvSpecPills"><span>String count</span><span>System voltage</span><span>Fuse / MCB</span></div><Link className="hvBtn hvBtnDark" href="/customize/dcdb">Configure DCDB <ArrowRight size={17}/></Link></div><div className="hvBuilderProduct"><HomeProductImage src="/dcdb-demo.svg" alt="Illustrative DCDB box"/></div></article></div><div className="hvBuildSteps" aria-label="Configuration workflow"><span><b>01</b>Choose system</span><i aria-hidden="true"/><span><b>02</b>Select components</span><i aria-hidden="true"/><span><b>03</b>Review BOM</span><i aria-hidden="true"/><span><b>04</b>Review and order</span></div></div></section>,
  buyways:<section className="hvSection hvBuyWays" aria-labelledby="buyways-title"><div className="container"><div className="hvSectionHead"><div><span>START WITH YOUR REQUIREMENT</span><h2 id="buyways-title">{home.buyways_heading}</h2><p>{home.buyways_body}</p></div></div><div className="hvBuyGrid"><Link href="/shop" className="hvBuyCard"><span className="hvBuyNumber">01</span><ShoppingCart/><div><small>READY PRODUCTS</small><h3>Buy Components</h3><p>Browse technical categories, review specifications and place a GST-ready direct order.</p><strong>Open product catalogue <ArrowRight/></strong></div></Link><Link href="/customize" className="hvBuyCard featured"><span className="hvBuyNumber">02</span><Settings2/><div><small>CUSTOM ASSEMBLY</small><h3>Build ACDB / DCDB</h3><p>Create the required box component by component, review the BOM and continue to order.</p><strong>Start configuration <ArrowRight/></strong></div></Link><Link href="/bulk-order" className="hvBuyCard"><span className="hvBuyNumber">03</span><FileText/><div><small>PROJECT PROCUREMENT</small><h3>Send Project RFQ</h3><p>Share quantities, ratings, location and delivery requirements for project pricing.</p><strong>Submit requirement <ArrowRight/></strong></div></Link></div></div></section>,
  why:<section className="hvSection hvWhy" id="why-us" aria-labelledby="why-title"><div className="container hvWhyGrid"><div className="hvWhyIntro"><span>WHY NEW INDIA SOLAR</span><h2 id="why-title">{home.why_heading}</h2><p>{home.why_body}</p><div className="hvPromise"><ShieldCheck/><div><small>OUR BRAND PROMISE</small><b>Tested. Packed. Guaranteed.</b></div></div><div className="hvWhyActions"><Link className="hvBtn hvBtnDark" href="/shop">Explore products <ArrowRight size={17}/></Link><Link className="hvTextLink" href="/downloads"><Download size={16}/> Technical downloads</Link></div></div><div className="hvWhyPanel"><div className="hvWhyPanelTop"><span>BUILT AROUND YOUR INSTALLATION</span><CircleGauge/></div><div className="hvWhyCards"><article><SearchCheck/><div><h3>Clear specifications</h3><p>Buy using ratings and structured attributes rather than unstructured messages.</p></div></article><article><Settings2/><div><h3>Dynamic configurations</h3><p>Choose enclosure, protection and internal accessories for each box.</p></div></article><article><FileText/><div><h3>Component list included</h3><p>Review the selected components together before placing your custom order.</p></div></article><article><Truck/><div><h3>Project buying support</h3><p>Share quantities, delivery location and purchase timing in your project enquiry.</p></div></article></div></div></div></section>,
  final:<section className="hvFinal"><div className="container"><div className="hvFinalInner"><div className="hvFinalCopy"><span>{home.final_eyebrow}</span><h2>{home.final_heading}</h2><p>Choose the fastest path for your next residential, commercial or industrial installation.</p></div><div className="hvFinalActions"><Link className="hvBtn hvBtnLight" href="/shop">Shop Components</Link><Link className="hvBtn hvBtnPrimary" href="/bulk-order">Request Project Pricing <ArrowRight size={17}/></Link></div></div></div></section>,
 }

 return <><StoreHeader/><main id="main-content" className="homeV3"><section className="hvHero" aria-labelledby="home-hero-title"><div className="container hvHeroGrid"><div className="hvHeroCopy"><span className="hvEyebrow"><i/> {hero.eyebrow||'Solar BOS infrastructure for EPCs & installers'}</span><h1 id="home-hero-title"><HeroTitle title={title} highlight={highlight}/></h1><p>{hero.body}</p><div className="hvActions"><Link className="hvBtn hvBtnPrimary" href={hero.primary_href||'/shop'}>{hero.primary_label||'Shop Components'} <ArrowRight size={18}/></Link><Link className="hvBtn hvBtnLight" href={hero.secondary_href==='/customize/dcdb'?'/customize':hero.secondary_href||'/customize'}>{hero.secondary_label||'Build ACDB / DCDB'}</Link><Link className="hvBtn hvBtnGhost" href={hero.tertiary_href||'/bulk-order'}>{hero.tertiary_label||'Project RFQ'}</Link></div><div className="hvProof" aria-label="Ordering benefits">{(hero.proof||[]).map((x:string)=><span key={x}><CheckCircle2/> {x}</span>)}</div></div><div className="hvHeroVisual" aria-label="New India Solar product and procurement preview">{publicAssetUrl(hero.banner_image_url)?<div className="hvCmsBanner"><HomeProductImage src={hero.banner_image_url} alt="New India Solar" priority/></div>:<><div className="hvHeroGlow"/><div className="hvHeroBoard"><div className="hvHeroBoardHead"><span>PROTECTION & BOS</span><b>Complete solar component range</b></div><div className="hvHeroProducts"><Link href="/shop?q=DCDB" className="hvHeroProduct hvProductMain"><HomeProductImage src="/dcdb-demo.svg" alt="Illustration of a DCDB box" priority/><span><small>DC PROTECTION</small><b>DCDB Boxes</b></span></Link><Link href="/shop?q=ACDB" className="hvHeroProduct"><HomeProductImage src="/acdb-demo.svg" alt="Illustration of an ACDB box" priority/><span><small>AC PROTECTION</small><b>ACDB Boxes</b></span></Link><Link href="/shop?q=SPD" className="hvHeroProduct"><HomeProductImage src="/spd-demo.svg" alt="Illustration of surge protection devices" priority/><span><small>COMPONENTS</small><b>Surge Protection</b></span></Link></div><div className="hvHeroBoardFoot"><span><Check/> Residential</span><span><Check/> Commercial</span><span><Check/> Industrial</span></div><small className="hvIllustrationNote">Category illustrations · configurations vary</small></div><Link className="hvHeroRfQ" href="/bulk-order"><FileText/><span><small>HAVE A BOQ?</small><b>Get project pricing</b></span><ArrowRight/></Link></>}</div></div></section>{order.map((key:string)=>visibility[key]===false?null:<div key={key}>{sections[key]}</div>)}</main><StoreFooter/></>
}
