const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const money=(value:unknown)=>`INR ${Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const address=(a:any)=>[a?.full_name||a?.contact_name,a?.address_line1,a?.address_line2,[a?.city,a?.state,a?.postal_code||a?.pincode].filter(Boolean).join(', '),a?.phone].filter(Boolean).map(escape).join('<br>')
export function buyerDocument(data:any,invoice?:any){
 const order=data.order,seller=data.seller||{},doc=invoice||order,rows=invoice?invoice.items:data.items,title=invoice?`${String(invoice.document_type||'Invoice').replaceAll('_',' ')} ${invoice.invoice_number}`:`Order ${order.order_number}`
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font:14px Arial,sans-serif;color:#172a25;max-width:960px;margin:32px auto;padding:20px}h1{font-size:24px}h2{font-size:18px}.columns{display:flex;gap:32px;flex-wrap:wrap}.columns>div{flex:1;min-width:240px}table{border-collapse:collapse;width:100%;margin:24px 0}td,th{padding:10px;border:1px solid #ddd;text-align:left}p{line-height:1.6}.total{font-size:18px;font-weight:bold}@media print{body{margin:0;padding:8mm}tr{break-inside:avoid}thead{display:table-header-group}}</style></head><body><h1>${escape(seller.legal_name||'New India Solar')}</h1><p>${[seller.address_line1,seller.address_line2,seller.city,seller.state,seller.pincode].filter(Boolean).map(escape).join(', ')}<br>${seller.gstin?`GSTIN: ${escape(seller.gstin)}`:''}</p><h2>${escape(title)}</h2><p>Date: ${escape(invoice?.invoice_date||String(order.created_at).slice(0,10))}<br>Order: ${escape(order.order_number)}<br>Status: ${escape(doc.status)}${invoice?`<br>Place of supply: ${escape(invoice.place_of_supply||'')}`:''}</p><div class="columns"><div><h2>Bill to</h2>${address(doc.billing_address)}<p>${escape(invoice?.customer_snapshot?.company_name||order.company_name||'')}<br>${escape(invoice?.customer_snapshot?.gstin||order.gstin||'')}</p></div><div><h2>Ship to</h2>${address(doc.shipping_address)}</div></div><table><thead><tr><th>Item / SKU${invoice?' / HSN':''}</th><th>Qty</th><th>Unit price</th><th>GST</th><th>Total</th></tr></thead><tbody>${(rows||[]).map((r:any)=>`<tr><td>${escape(r.description||r.name_snapshot)}<br>${escape(r.sku||r.sku_snapshot)}${invoice?`<br>${escape(r.hsn_code)}`:''}</td><td>${escape(r.quantity)} ${escape(r.unit||'')}</td><td>${money(r.unit_price)}</td><td>${escape(r.gst_rate)}%<br>${money(invoice?r.tax_total:r.tax_amount)}</td><td>${money(r.line_total)}</td></tr>`).join('')}</tbody></table><p>Subtotal: ${money(doc.subtotal)}<br>Discount: ${money(doc.discount_amount)}<br>Shipping: ${money(doc.shipping_amount)}<br>${invoice?`CGST: ${money(doc.cgst_amount)}<br>SGST: ${money(doc.sgst_amount)}<br>IGST: ${money(doc.igst_amount)}`:`GST: ${money(doc.tax_amount)}`}</p><p class="total">Total: ${money(doc.grand_total)}</p>${invoice?`<p>Amount paid: ${money(invoice.amount_paid)}<br>Balance: ${money(invoice.balance_due)}</p><p>${escape(seller.invoice_terms||'')}</p>`:'<p>This is an order summary, not a tax invoice. Issued invoices are available separately in your account.</p>'}</body></html>`
}
export function downloadDocument(html:string,name:string){const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${name.replace(/[^a-zA-Z0-9_-]/g,'-')}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function printDocument(html:string){const w=window.open('','_blank');if(!w)throw Error('Allow pop-ups to print or save a PDF.');w.opener=null;w.document.open();w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
