export type SupportIdentityRow={user_id:string;public_key_jwk:JsonWebKey;encrypted_private_key:string;private_key_iv:string;private_key_salt:string;key_version:number}
export type PublicRecipient={user_id:string;display_name:string;public_key_jwk:JsonWebKey;key_version:number}
const encoder=new TextEncoder(),decoder=new TextDecoder()
function bytesToBase64(bytes:Uint8Array){let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(out)}
function base64ToBytes(value:string){const raw=atob(value),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
function random(size:number){return crypto.getRandomValues(new Uint8Array(size))}
function buffer(bytes:Uint8Array){return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer}
async function pinKey(pin:string,salt:Uint8Array){const material=await crypto.subtle.importKey('raw',encoder.encode(pin.normalize('NFKC')),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:buffer(salt),iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
export function validateSupportPin(pin:string){if(pin.length<8)return'Use at least 8 characters for your Secure Chat PIN.';if(!/[a-zA-Z]/.test(pin)||!/[0-9]/.test(pin))return'Include at least one letter and one number.';return''}
export async function createSupportIdentity(pin:string,userId:string){const error=validateSupportPin(pin);if(error)throw new Error(error);const pair=await crypto.subtle.generateKey({name:'RSA-OAEP',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['encrypt','decrypt']);const [publicJwk,privateJwk]=await Promise.all([crypto.subtle.exportKey('jwk',pair.publicKey),crypto.subtle.exportKey('jwk',pair.privateKey)]);const salt=random(16),iv=random(12),key=await pinKey(pin,salt);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv:buffer(iv),additionalData:encoder.encode(`nis-support:${userId}:v1`)},key,encoder.encode(JSON.stringify(privateJwk)));return{public_key_jwk:publicJwk,encrypted_private_key:bytesToBase64(new Uint8Array(encrypted)),private_key_iv:bytesToBase64(iv),private_key_salt:bytesToBase64(salt),key_version:1,privateKey:pair.privateKey}}
export async function unlockSupportIdentity(identity:SupportIdentityRow,pin:string){try{const key=await pinKey(pin,base64ToBytes(identity.private_key_salt));const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:buffer(base64ToBytes(identity.private_key_iv)),additionalData:encoder.encode(`nis-support:${identity.user_id}:v${identity.key_version}`)},key,buffer(base64ToBytes(identity.encrypted_private_key)));return crypto.subtle.importKey('jwk',JSON.parse(decoder.decode(clear)),{name:'RSA-OAEP',hash:'SHA-256'},false,['decrypt'])}catch{throw new Error('Incorrect Secure Chat PIN. Your encrypted messages were not unlocked.')}}
export async function createConversationKey(){return crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt'])}
export async function wrapConversationKey(key:CryptoKey,recipient:PublicRecipient){const publicKey=await crypto.subtle.importKey('jwk',recipient.public_key_jwk,{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']);const raw=await crypto.subtle.exportKey('raw',key),wrapped=await crypto.subtle.encrypt({name:'RSA-OAEP'},publicKey,raw);return{recipient_id:recipient.user_id,wrapped_key:bytesToBase64(new Uint8Array(wrapped)),identity_version:recipient.key_version}}
export async function unwrapConversationKey(wrapped:string,privateKey:CryptoKey){const raw=await crypto.subtle.decrypt({name:'RSA-OAEP'},privateKey,buffer(base64ToBytes(wrapped)));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encryptSupportText(key:CryptoKey,text:string,context:string){const iv=random(12),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv:buffer(iv),additionalData:encoder.encode(context)},key,encoder.encode(text));return{ciphertext:bytesToBase64(new Uint8Array(cipher)),iv:bytesToBase64(iv)}}
export async function decryptSupportText(key:CryptoKey,ciphertext:string,iv:string,context:string){try{const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:buffer(base64ToBytes(iv)),additionalData:encoder.encode(context)},key,buffer(base64ToBytes(ciphertext)));return decoder.decode(clear)}catch{return'Encrypted content could not be verified.'}}
