'use client'

import {DragEvent,FormEvent,PointerEvent,useEffect,useMemo,useRef,useState} from 'react'
import {Check,ChevronDown,ChevronLeft,ChevronRight,ChevronUp,Copy,Grid2X2,Image as ImageIcon,Layers3,MousePointer2,Plus,RotateCcw,Save,Search,Trash2} from 'lucide-react'
import {supabase} from '../../../../lib/supabase'

type ComponentItem={id:string;name:string;category:string;image_url?:string;model?:string;sku?:string;brands?:{name?:string}}
type Layer={id?:string;slot_key:string;option_key:string;slot_index:number;component_category?:string|null;x_pct:number;y_pct:number;width_pct:number;height_pct:number;rotation_deg:number;z_index:number;is_active:boolean;settings:any}

const blank:Layer={slot_key:'component_1',option_key:'dc_mcb',slot_index:1,component_category:'',x_pct:40,y_pct:30,width_pct:22,height_pct:40,rotation_deg:0,z_index:20,is_active:true,settings:{}}
const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n))
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d
const optionLabel=(k:string)=>({dc_mcb:'DC MCB',protection:'MCB / MCCB',spd:'SPD',terminal:'Terminal Block',solar_cable:'Wire',wire:'Wire',fuse_holder:'Fuse Holder',fuse:'Fuse',cable_gland:'Cable Gland',earthing:'Earth Terminal',busbar:'Busbar',indicator:'Indicator',extras:'Accessory'} as any)[k]||k
function componentOption(category:string,type:string){const c=(category||'').toLowerCase();if(c.includes('mccb')||c.includes('mcb'))return type==='acdb'?'protection':'dc_mcb';if(c.includes('spd'))return 'spd';if(c.includes('terminal'))return 'terminal';if(c.includes('fuse holder'))return 'fuse_holder';if(c.includes('fuse'))return 'fuse';if(c.includes('cable gland'))return 'cable_gland';if(c.includes('busbar'))return 'busbar';if(c.includes('indicator'))return 'indicator';if(c.includes('earth'))return 'earthing';if(c.includes('wire')||c.includes('solar cable'))return type==='acdb'?'wire':'solar_cable';return 'extras'}
function defaults(option:string,index=1){const offset=Math.max(0,index-1)*5;const map:any={spd:{x:18+offset,y:38,w:25,h:44,z:20},dc_mcb:{x:45+offset,y:38,w:22,h:42,z:21},protection:{x:45+offset,y:38,w:22,h:42,z:21},terminal:{x:70+offset,y:44,w:14,h:24,z:22},solar_cable:{x:22,y:18+offset,w:58,h:25,z:30},wire:{x:22,y:18+offset,w:58,h:25,z:30},fuse_holder:{x:18+offset,y:58,w:17,h:28,z:23},fuse:{x:18+offset,y:58,w:17,h:28,z:24},cable_gland:{x:28+offset*2,y:84,w:12,h:12,z:26},earthing:{x:70,y:72,w:16,h:12,z:24},busbar:{x:20,y:58,w:55,h:10,z:24},indicator:{x:72,y:26,w:12,h:18,z:24},extras:{x:72,y:66,w:14,h:18,z:24}};return map[option]||map.extras}

export default function SlotMapping(){
 const stageRef=useRef<HTMLDivElement|null>(null)
 const layerDrag=useRef<any>(null)
 const paletteDrag=useRef<any>(null)
 const [templates,setTemplates]=useState<any[]>([]),[enclosures,setEnclosures]=useState<any[]>([]),[components,setComponents]=useState<ComponentItem[]>([]),[slots,setSlots]=useState<Layer[]>([])
 const [templateId,setTemplateId]=useState(''),[enclosureId,setEnclosureId]=useState(''),[selectedId,setSelectedId]=useState(''),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[saving,setSaving]=useState(false)
 const [pending,setPending]=useState<ComponentItem|null>(null),[floating,setFloating]=useState<any>(null)
 useEffect(()=>{Promise.all([supabase.from('configurator_templates').select('id,name,slug,type').order('name'),supabase.from('enclosures').select('id,name,inside_image_url,image_url,dimensions_mm').order('name'),supabase.from('components').select('id,name,category,image_url,model,sku,brands(name)').eq('is_active',true).order('category').order('name')]).then(([t,e,c])=>{setTemplates(t.data||[]);setEnclosures(e.data||[]);setComponents((c.data||[]) as any);if(t.data?.[0])setTemplateId(t.data[0].id);if(e.data?.[0])setEnclosureId(e.data[0].id)})},[])
 useEffect(()=>{if(templateId&&enclosureId)loadSlots()},[templateId,enclosureId])
 async function loadSlots(){const {data}=await supabase.from('configurator_visual_slots').select('*').eq('template_id',templateId).eq('enclosure_id',enclosureId).order('z_index').order('slot_index');setSlots((data||[]).map((x:any)=>({...x,x_pct:num(x.x_pct),y_pct:num(x.y_pct),width_pct:num(x.width_pct),height_pct:num(x.height_pct),rotation_deg:num(x.rotation_deg),settings:x.settings||{}})))}
 const tpl=templates.find(x=>x.id===templateId),enc=enclosures.find(x=>x.id===enclosureId)
 const categories=useMemo(()=>Array.from(new Set(components.map(x=>x.category))).filter(Boolean).sort(),[components])
 const filtered=useMemo(()=>components.filter(c=>(cat==='all'||c.category===cat)&&`${c.name} ${c.model||''} ${c.sku||''} ${c.brands?.name||''}`.toLowerCase().includes(q.toLowerCase())),[components,cat,q])
 const selected=slots.find(s=>s.id===selectedId)||null
 function stagePct(x:number,y:number){const r=stageRef.current?.getBoundingClientRect();if(!r)return{x:50,y:50,inside:false};return{x:clamp(((x-r.left)/r.width)*100,0,100),y:clamp(((y-r.top)/r.height)*100,0,100),inside:x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}}
 async function persist(layer:Layer){setSaving(true);const p={template_id:templateId,enclosure_id:enclosureId,slot_key:layer.slot_key,option_key:layer.option_key,slot_index:Number(layer.slot_index||1),component_category:layer.component_category||null,x_pct:Number(layer.x_pct),y_pct:Number(layer.y_pct),width_pct:Number(layer.width_pct),height_pct:Number(layer.height_pct),rotation_deg:Number(layer.rotation_deg||0),z_index:Number(layer.z_index||10),is_active:!!layer.is_active,settings:layer.settings||{}};let r:any;if(layer.id)r=await supabase.from('configurator_visual_slots').update(p).eq('id',layer.id).select('*').single();else r=await supabase.from('configurator_visual_slots').insert(p).select('*').single();setSaving(false);if(r.error){setMsg(r.error.message);return null}return {...r.data,x_pct:num(r.data.x_pct),y_pct:num(r.data.y_pct),width_pct:num(r.data.width_pct),height_pct:num(r.data.height_pct),rotation_deg:num(r.data.rotation_deg),settings:r.data.settings||{}} as Layer}
 async function addAt(c:ComponentItem,x?:number,y?:number,forceNew=true){const option=componentOption(c.category,tpl?.type||'dcdb');const existing=!forceNew?slots.find(s=>s.option_key===option):null;if(existing){const next={...existing,component_category:c.category,settings:{...(existing.settings||{}),preview_component_id:c.id,preview_image_url:c.image_url||null,preview_name:c.name}};const saved=await persist(next);if(saved){setSlots(v=>v.map(s=>s.id===saved.id?saved:s));setSelectedId(saved.id||'');setMsg(`${c.name} set on ${optionLabel(option)} preview.`)}return}
 const index=slots.filter(s=>s.option_key===option).length+1,d=defaults(option,index),p=x!=null&&y!=null?stagePct(x,y):null;const layer:Layer={...blank,slot_key:`${option}_${index}`,option_key:option,slot_index:index,component_category:c.category,x_pct:p?clamp(p.x-d.w/2,0,100-d.w):d.x,y_pct:p?clamp(p.y-d.h/2,0,100-d.h):d.y,width_pct:d.w,height_pct:d.h,z_index:d.z,settings:{preview_component_id:c.id,preview_image_url:c.image_url||null,preview_name:c.name}}
 const saved=await persist(layer);if(saved){setSlots(v=>[...v,saved]);setSelectedId(saved.id||'');setPending(null);setMsg(`${c.name} added. Drag it directly on the box to fine-tune.`)}}
 async function useComponent(c:ComponentItem){setPending(c);await addAt(c,undefined,undefined,false)}
 async function addAnother(c:ComponentItem){setPending(c);await addAt(c)}
 function nativeDrag(e:DragEvent,c:ComponentItem){e.dataTransfer.setData('application/x-nis-component',c.id);e.dataTransfer.effectAllowed='copy'}
 async function nativeDrop(e:DragEvent){e.preventDefault();const id=e.dataTransfer.getData('application/x-nis-component');const c=components.find(x=>x.id===id);if(c)await addAt(c,e.clientX,e.clientY,true)}
 function startPaletteTouch(e:PointerEvent,c:ComponentItem){if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);paletteDrag.current={c,pointerId:e.pointerId};setFloating({c,x:e.clientX,y:e.clientY})}
 function movePaletteTouch(e:PointerEvent){if(!paletteDrag.current)return;e.preventDefault();setFloating((f:any)=>f?{...f,x:e.clientX,y:e.clientY}:f)}
 async function endPaletteTouch(e:PointerEvent){const d=paletteDrag.current;if(!d)return;paletteDrag.current=null;setFloating(null);const p=stagePct(e.clientX,e.clientY);if(p.inside)await addAt(d.c,e.clientX,e.clientY,true);else{setPending(d.c);setMsg(`Selected ${d.c.name}. Tap anywhere on the preview to place it.`)}}
 async function placePending(e:PointerEvent){if(!pending||layerDrag.current)return;const p=stagePct(e.clientX,e.clientY);if(p.inside)await addAt(pending,e.clientX,e.clientY,true)}
 function startLayer(e:PointerEvent,s:Layer,mode:'move'|'resize'){e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);setSelectedId(s.id||'');layerDrag.current={id:s.id,mode,start:stagePct(e.clientX,e.clientY),orig:{x:s.x_pct,y:s.y_pct,w:s.width_pct,h:s.height_pct},latest:s}}
 function moveLayer(e:PointerEvent){const d=layerDrag.current;if(!d)return;e.preventDefault();const p=stagePct(e.clientX,e.clientY),dx=p.x-d.start.x,dy=p.y-d.start.y;setSlots(old=>old.map(s=>{if(s.id!==d.id)return s;let next:Layer;if(d.mode==='move')next={...s,x_pct:+clamp(d.orig.x+dx,0,100-d.orig.w).toFixed(2),y_pct:+clamp(d.orig.y+dy,0,100-d.orig.h).toFixed(2)};else next={...s,width_pct:+clamp(d.orig.w+dx,4,100-d.orig.x).toFixed(2),height_pct:+clamp(d.orig.h+dy,4,100-d.orig.y).toFixed(2)};d.latest=next;return next}))}
 async function endLayer(){const d=layerDrag.current;if(!d)return;layerDrag.current=null;if(d.latest){const saved=await persist(d.latest);if(saved){setSlots(v=>v.map(s=>s.id===saved.id?saved:s));setMsg('Position saved. This exact percentage layout will scale on buyer mobile and desktop preview.')}}}
 async function patchSelected(patch:Partial<Layer>){if(!selected)return;const next={...selected,...patch};setSlots(v=>v.map(s=>s.id===selected.id?next:s));const saved=await persist(next);if(saved)setSlots(v=>v.map(s=>s.id===saved.id?saved:s))}
 async function nudge(dx:number,dy:number){if(!selected)return;await patchSelected({x_pct:+clamp(selected.x_pct+dx,0,100-selected.width_pct).toFixed(2),y_pct:+clamp(selected.y_pct+dy,0,100-selected.height_pct).toFixed(2)})}
 async function duplicate(){if(!selected)return;const copy={...selected,id:undefined,slot_key:`${selected.option_key}_${slots.filter(s=>s.option_key===selected.option_key).length+1}`,slot_index:slots.filter(s=>s.option_key===selected.option_key).length+1,x_pct:clamp(selected.x_pct+4,0,100-selected.width_pct),y_pct:clamp(selected.y_pct+4,0,100-selected.height_pct)};const saved=await persist(copy);if(saved){setSlots(v=>[...v,saved]);setSelectedId(saved.id||'')}}
 async function remove(id?:string){if(!id)return;await supabase.from('configurator_visual_slots').delete().eq('id',id);setSlots(v=>v.filter(s=>s.id!==id));if(selectedId===id)setSelectedId('');setMsg('Layer removed.')}
 async function saveForm(e:FormEvent){e.preventDefault();if(!selected)return;const saved=await persist(selected);if(saved){setSlots(v=>v.map(s=>s.id===saved.id?saved:s));setMsg('Layer saved.')}}
 async function clearPreview(){if(!confirm('Remove all preview slots for this enclosure?'))return;await supabase.from('configurator_visual_slots').delete().eq('template_id',templateId).eq('enclosure_id',enclosureId);setSlots([]);setSelectedId('');setMsg('Preview cleared. Start by selecting or dragging components.')}
 return <div className="cfgAdmin cfgEasyEditor">
  <div className="adminPageHead"><div><span className="adminEyebrow">EASY VISUAL PREVIEW BUILDER</span><h1>Set Components on Box</h1><p>Pick a category and product, then place it visually. Desktop supports mouse drag & drop; mobile supports touch-drag from the handle and direct finger movement on placed components.</p></div></div>
  {msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}
  <div className="cfgEasyTop"><label><span>Builder</span><select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span>Enclosure Preview</span><select value={enclosureId} onChange={e=>setEnclosureId(e.target.value)}>{enclosures.map(x=><option key={x.id} value={x.id}>{x.name}{x.dimensions_mm?` • ${x.dimensions_mm}`:''}</option>)}</select></label><button className="cfgClearBtn" onClick={clearPreview}><RotateCcw size={15}/>Clear Preview</button></div>
  <div className="cfgEasyLayout">
   <aside className="cfgEasyLibrary"><div className="cfgEasyLibHead"><Grid2X2/><div><b>1. Choose Product</b><small>Tap “Use” or drag it onto the box.</small></div></div><label className="cfgPaletteSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search brand, model..."/></label><div className="cfgCatChips cfgBigChips"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="cfgEasyProducts">{filtered.map(c=><article key={c.id} draggable onDragStart={e=>nativeDrag(e,c)} className={pending?.id===c.id?'selected':''}><div className="cfgProductPic">{c.image_url?<img src={c.image_url} alt={c.name}/>:<ImageIcon/>}</div><div className="cfgProductInfo"><span>{c.category}</span><b>{c.name}</b><small>{[c.brands?.name,c.model].filter(Boolean).join(' • ')||c.sku||'Component'}</small></div><div className="cfgProductActions"><button onClick={()=>useComponent(c)}>Use</button><button onClick={()=>addAnother(c)} title="Add another"><Plus size={14}/></button><button className="cfgTouchHandle" aria-label="Touch and drag to preview" onPointerDown={e=>startPaletteTouch(e,c)} onPointerMove={movePaletteTouch} onPointerUp={endPaletteTouch} onPointerCancel={()=>{paletteDrag.current=null;setFloating(null)}}><MousePointer2 size={15}/></button></div></article>)}</div></aside>
   <main className="cfgEasyCanvas"><div className="cfgCanvasHeadV2"><div><span>2. PLACE & ADJUST</span><b>{enc?.name||'Enclosure preview'}</b><small>{enc?.dimensions_mm||'Responsive percentage canvas'}</small></div><div className="cfgCanvasStatus"><i>{slots.length}</i> layers</div></div>{pending&&<div className="cfgPendingBar"><div>{pending.image_url?<img src={pending.image_url} alt=""/>:<ImageIcon/>}<span><small>Ready to place</small><b>{pending.name}</b></span></div><strong>Tap on box or drag the touch handle</strong><button onClick={()=>setPending(null)}>Cancel</button></div>}<div ref={stageRef} className={`cfgSlotStage cfgDropStage cfgEasyStage ${pending?'placing':''}`} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDrop={nativeDrop} onPointerUp={placePending} onPointerMove={moveLayer} onPointerCancel={endLayer}>{enc?.inside_image_url||enc?.image_url?<img className="cfgEnclosureBase" src={enc.inside_image_url||enc.image_url} alt={enc?.name||'Enclosure'}/>:<div className="cfgNoAsset"><Layers3/><b>No enclosure preview</b><span>Upload inside-view PNG in Templates & Enclosures.</span></div>}{slots.map(s=><div key={s.id} className={`cfgVisualSlot cfgEasyLayer ${selectedId===s.id?'active':''}`} onPointerDown={e=>startLayer(e,s,'move')} onPointerUp={endLayer} style={{left:`${s.x_pct}%`,top:`${s.y_pct}%`,width:`${s.width_pct}%`,height:`${s.height_pct}%`,zIndex:s.z_index,transform:`rotate(${s.rotation_deg||0}deg)`}}>{s.settings?.preview_image_url?<img src={s.settings.preview_image_url} alt={s.settings?.preview_name||s.option_key}/>:<div className="cfgSlotGhost"><span>{optionLabel(s.option_key)}</span><small>#{s.slot_index}</small></div>}<button className="cfgResizeHandle" type="button" aria-label="Resize" onPointerDown={e=>startLayer(e,s,'resize')} onPointerUp={endLayer}/>{selectedId===s.id&&<em>{s.settings?.preview_name||optionLabel(s.option_key)}</em>}</div>)}</div><div className="cfgEasyHelp"><span><b>Desktop</b> Drag product → box → drag layer to move.</span><span><b>Mobile</b> Touch the hand icon → drag to box → drag placed part with finger.</span><span><b>Responsive</b> X/Y/size are saved as %, so buyer preview scales automatically.</span></div></main>
   <aside className="cfgEasyInspector"><div className="cfgInspectorHead"><b>3. Fine Tune</b><small>{selected?'Selected component':'Tap any component on preview'}</small></div>{selected?<form onSubmit={saveForm}><div className="cfgSelectedCard">{selected.settings?.preview_image_url?<img src={selected.settings.preview_image_url} alt=""/>:<Layers3/>}<div><span>{optionLabel(selected.option_key)}</span><b>{selected.settings?.preview_name||selected.slot_key}</b><small>{selected.component_category||'Visual layer'}</small></div></div><div className="cfgNudge"><button type="button" onClick={()=>nudge(0,-.5)}><ChevronUp/></button><button type="button" onClick={()=>nudge(-.5,0)}><ChevronLeft/></button><span>Move<br/><b>0.5%</b></span><button type="button" onClick={()=>nudge(.5,0)}><ChevronRight/></button><button type="button" onClick={()=>nudge(0,.5)}><ChevronDown/></button></div><div className="cfgInspectorGrid"><label><span>X %</span><input type="number" step="0.1" value={selected.x_pct} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,x_pct:num(e.target.value)}:s))}/></label><label><span>Y %</span><input type="number" step="0.1" value={selected.y_pct} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,y_pct:num(e.target.value)}:s))}/></label><label><span>Width %</span><input type="number" step="0.1" value={selected.width_pct} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,width_pct:num(e.target.value)}:s))}/></label><label><span>Height %</span><input type="number" step="0.1" value={selected.height_pct} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,height_pct:num(e.target.value)}:s))}/></label><label><span>Rotation</span><input type="number" step="1" value={selected.rotation_deg} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,rotation_deg:num(e.target.value)}:s))}/></label><label><span>Layer Z</span><input type="number" value={selected.z_index} onChange={e=>setSlots(v=>v.map(s=>s.id===selected.id?{...s,z_index:num(e.target.value)}:s))}/></label></div><button className="adminBtn" disabled={saving}><Save size={15}/>{saving?'Saving…':'Save Fine Tune'}</button><div className="cfgInspectorActions"><button type="button" onClick={duplicate}><Copy size={14}/>Duplicate</button><button type="button" className="danger" onClick={()=>remove(selected.id)}><Trash2 size={14}/>Remove</button></div></form>:<div className="cfgInspectorEmpty"><MousePointer2/><b>Select a placed product</b><p>Then drag it directly or use the fine-position controls.</p></div>}<div className="cfgPlacedList"><h3>Placed Products</h3>{slots.length?slots.map(s=><button key={s.id} className={selectedId===s.id?'active':''} onClick={()=>setSelectedId(s.id||'')}><span>{s.settings?.preview_image_url?<img src={s.settings.preview_image_url} alt=""/>:<Layers3/>}</span><div><b>{s.settings?.preview_name||optionLabel(s.option_key)}</b><small>{optionLabel(s.option_key)} #{s.slot_index}</small></div></button>):<p>No components placed yet.</p>}</div></aside>
  </div>
  {floating&&<div className="cfgFingerGhost" style={{left:floating.x,top:floating.y}}>{floating.c.image_url?<img src={floating.c.image_url} alt=""/>:<ImageIcon/>}<span>{floating.c.name}</span></div>}
 </div>
}
