'use client'

import {DragEvent,FormEvent,PointerEvent,useEffect,useMemo,useRef,useState} from 'react'
import {Check,Grid2X2,Image as ImageIcon,Layers3,MousePointer2,Plus,RotateCcw,Save,Search,Trash2} from 'lucide-react'
import {supabase} from '../../../../lib/supabase'

const blank={id:'',slot_key:'component_1',option_key:'dc_mcb',slot_index:1,component_category:'',x_pct:10,y_pct:30,width_pct:25,height_pct:45,rotation_deg:0,z_index:20,is_active:true,settings:{}}
const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n))
const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d
const componentOption=(category:string,type:string)=>{
 const c=(category||'').toLowerCase()
 if(c.includes('mccb'))return type==='acdb'?'protection':'dc_mcb'
 if(c.includes('mcb'))return type==='acdb'?'protection':'dc_mcb'
 if(c.includes('spd'))return 'spd'
 if(c.includes('terminal'))return 'terminal'
 if(c.includes('fuse holder'))return 'fuse_holder'
 if(c.includes('fuse'))return 'fuse'
 if(c.includes('cable gland'))return 'cable_gland'
 if(c.includes('busbar'))return 'busbar'
 if(c.includes('indicator'))return 'indicator'
 if(c.includes('earth'))return 'earthing'
 if(c.includes('wire')||c.includes('solar cable'))return type==='acdb'?'wire':'solar_cable'
 return 'extras'
}
const optionLabel=(k:string)=>({dc_mcb:'DC MCB',protection:'Protection',spd:'SPD',terminal:'Terminal',solar_cable:'Wire',wire:'Wire',fuse_holder:'Fuse Holder',fuse:'Fuse',cable_gland:'Cable Gland',earthing:'Earth',busbar:'Busbar',indicator:'Indicator',extras:'Accessory'} as any)[k]||k

export default function SlotMapping(){
 const stageRef=useRef<HTMLDivElement|null>(null)
 const dragRef=useRef<any>(null)
 const [templates,setTemplates]=useState<any[]>([]),[enclosures,setEnclosures]=useState<any[]>([]),[components,setComponents]=useState<any[]>([]),[slots,setSlots]=useState<any[]>([]),[templateId,setTemplateId]=useState(''),[enclosureId,setEnclosureId]=useState(''),[form,setForm]=useState<any>(blank),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[savingId,setSavingId]=useState('')
 useEffect(()=>{Promise.all([supabase.from('configurator_templates').select('id,name,slug,type').order('name'),supabase.from('enclosures').select('id,name,inside_image_url,image_url,dimensions_mm').order('name'),supabase.from('components').select('id,name,category,image_url,model,sku,brands(name)').eq('is_active',true).order('category').order('name')]).then(([t,e,c])=>{setTemplates(t.data||[]);setEnclosures(e.data||[]);setComponents(c.data||[]);if(t.data?.[0])setTemplateId(t.data[0].id);if(e.data?.[0])setEnclosureId(e.data[0].id)})},[])
 useEffect(()=>{if(templateId&&enclosureId)loadSlots()},[templateId,enclosureId])
 async function loadSlots(){const {data}=await supabase.from('configurator_visual_slots').select('*').eq('template_id',templateId).eq('enclosure_id',enclosureId).order('z_index').order('slot_index');setSlots((data||[]).map((x:any)=>({...x,settings:x.settings||{}})))}
 const tpl=templates.find(x=>x.id===templateId);const enc=enclosures.find(e=>e.id===enclosureId)
 const optionKeys=useMemo(()=>tpl?.type==='acdb'?['protection','spd','terminal','wire','cable_gland','busbar','indicator','extras']:['dc_mcb','spd','fuse_holder','fuse','terminal','solar_cable','cable_gland','earthing','extras'],[tpl])
 const categories=useMemo(()=>Array.from(new Set(components.map(x=>x.category))).filter(Boolean).sort(),[components])
 const filteredComponents=useMemo(()=>components.filter(c=>(cat==='all'||c.category===cat)&&`${c.name} ${c.model||''} ${c.sku||''} ${c.brands?.name||''}`.toLowerCase().includes(q.toLowerCase())),[components,cat,q])
 function edit(s:any){setForm({...s,settings:s.settings||{}})}
 async function persistSlot(s:any){setSavingId(s.id||'new');const p={template_id:templateId,enclosure_id:enclosureId,slot_key:s.slot_key,option_key:s.option_key,slot_index:Number(s.slot_index||1),component_category:s.component_category||null,x_pct:Number(s.x_pct),y_pct:Number(s.y_pct),width_pct:Number(s.width_pct),height_pct:Number(s.height_pct),rotation_deg:Number(s.rotation_deg||0),z_index:Number(s.z_index||10),is_active:!!s.is_active,settings:s.settings||{}};let r:any;if(s.id){r=await supabase.from('configurator_visual_slots').update(p).eq('id',s.id).select('*').single()}else{r=await supabase.from('configurator_visual_slots').insert(p).select('*').single()}setSavingId('');if(r.error){setMsg(r.error.message);return null}return {...r.data,settings:r.data.settings||{}}}
 async function save(e:FormEvent){e.preventDefault();const saved=await persistSlot(form);if(!saved)return;setMsg('Slot saved. Percentage coordinates automatically stay responsive on buyer preview.');setForm({...blank,option_key:optionKeys[0]||'component'});loadSlots()}
 async function remove(id:string){await supabase.from('configurator_visual_slots').delete().eq('id',id);setForm({...blank,option_key:optionKeys[0]||'component'});loadSlots()}
 function stagePct(clientX:number,clientY:number){const r=stageRef.current?.getBoundingClientRect();if(!r)return{x:0,y:0};return{x:clamp(((clientX-r.left)/r.width)*100,0,100),y:clamp(((clientY-r.top)/r.height)*100,0,100)}}
 function startMove(e:PointerEvent,s:any,mode:'move'|'resize'){e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);dragRef.current={id:s.id,mode,start:stagePct(e.clientX,e.clientY),orig:{x:num(s.x_pct),y:num(s.y_pct),w:num(s.width_pct),h:num(s.height_pct)}};edit(s)}
 function movePointer(e:PointerEvent){const d=dragRef.current;if(!d)return;const p=stagePct(e.clientX,e.clientY),dx=p.x-d.start.x,dy=p.y-d.start.y;setSlots(old=>old.map(s=>{if(s.id!==d.id)return s;if(d.mode==='move'){const x=clamp(d.orig.x+dx,0,100-d.orig.w),y=clamp(d.orig.y+dy,0,100-d.orig.h);const next={...s,x_pct:+x.toFixed(2),y_pct:+y.toFixed(2)};setForm((f:any)=>f.id===s.id?{...f,x_pct:next.x_pct,y_pct:next.y_pct}:f);return next}const w=clamp(d.orig.w+dx,4,100-d.orig.x),h=clamp(d.orig.h+dy,4,100-d.orig.y);const next={...s,width_pct:+w.toFixed(2),height_pct:+h.toFixed(2)};setForm((f:any)=>f.id===s.id?{...f,width_pct:next.width_pct,height_pct:next.height_pct}:f);return next}})}
 async function endPointer(){const d=dragRef.current;if(!d)return;dragRef.current=null;const s=slots.find(x=>x.id===d.id);if(s){const fresh=(form.id===s.id?form:s);await persistSlot(fresh);setMsg('Position saved automatically. Buyer preview is responsive because placement is stored as percentages.');loadSlots()}}
 function dragComponent(e:DragEvent,component:any){e.dataTransfer.setData('application/x-config-component',JSON.stringify({id:component.id,name:component.name,category:component.category,image_url:component.image_url}));e.dataTransfer.effectAllowed='copy'}
 async function dropComponent(e:DragEvent){e.preventDefault();const raw=e.dataTransfer.getData('application/x-config-component');if(!raw)return;const c=JSON.parse(raw);const p=stagePct(e.clientX,e.clientY);const option=componentOption(c.category,tpl?.type||'dcdb');const same=slots.filter(s=>s.option_key===option);const w=option==='terminal'?14:option.includes('cable')||option==='wire'?42:22;const h=option==='terminal'?22:option.includes('cable')||option==='wire'?20:38;const next={...blank,slot_key:`${option}_${same.length+1}`,option_key:option,slot_index:same.length+1,component_category:c.category,x_pct:+clamp(p.x-w/2,0,100-w).toFixed(2),y_pct:+clamp(p.y-h/2,0,100-h).toFixed(2),width_pct:w,height_pct:h,z_index:option.includes('cable')||option==='wire'?30:20+same.length,settings:{preview_component_id:c.id,preview_image_url:c.image_url,preview_name:c.name}};const saved=await persistSlot(next);if(saved){setSlots(old=>[...old,saved]);setForm(saved);setMsg(`${c.name} dropped into ${optionLabel(option)} slot. Drag to position and resize.`)}}
 function allowDrop(e:DragEvent){e.preventDefault();e.dataTransfer.dropEffect='copy'}
 async function resetPreviewAssets(){for(const s of slots){if(s.settings?.preview_component_id){await supabase.from('configurator_visual_slots').update({settings:{...s.settings,preview_component_id:null,preview_image_url:null,preview_name:null}}).eq('id',s.id)}}setMsg('Preview component thumbnails cleared. Slot positions are unchanged.');loadSlots()}
 return <div className="cfgAdmin cfgVisualEditor"><div className="adminPageHead"><div><span className="adminEyebrow">DRAG & DROP VISUAL POSITION ENGINE</span><h1>Preview Layout Editor</h1><p>Choose an enclosure, drag components from a category onto the box, move and resize them visually. Coordinates are saved as percentages so the buyer preview scales automatically on desktop, tablet and mobile.</p></div></div>{msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}<div className="cfgSelectors"><label>Builder<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Preview Enclosure<select value={enclosureId} onChange={e=>setEnclosureId(e.target.value)}>{enclosures.map(x=><option key={x.id} value={x.id}>{x.name} {x.dimensions_mm?`• ${x.dimensions_mm}`:''}</option>)}</select></label><button className="adminBtn" onClick={()=>setForm({...blank,option_key:optionKeys[0]||'component'})}><Plus size={15}/>New Empty Slot</button></div>
 <div className="cfgDndLayout"><aside className="cfgComponentPalette"><div className="cfgPaletteHead"><div><Grid2X2/><b>Component Library</b></div><small>Drag any component onto the preview.</small></div><label className="cfgPaletteSearch"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search brand / model..."/></label><div className="cfgCatChips"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="cfgPaletteItems">{filteredComponents.map(c=><article draggable onDragStart={e=>dragComponent(e,c)} key={c.id} title="Drag onto preview"><div>{c.image_url?<img src={c.image_url} alt={c.name}/>:<ImageIcon/>}</div><section><span>{c.category}</span><b>{c.name}</b><small>{[c.brands?.name,c.model].filter(Boolean).join(' • ')||'Component'}</small></section><MousePointer2/></article>)}</div></aside>
 <section className="cfgSlotCanvas"><div className="cfgCanvasHead"><div><b>{enc?.name||'Preview'}</b><span>{enc?.dimensions_mm||'Percentage-based responsive canvas'}</span></div><button onClick={resetPreviewAssets}><RotateCcw size={14}/>Clear preview parts</button></div><div ref={stageRef} className="cfgSlotStage cfgDropStage" onDragOver={allowDrop} onDrop={dropComponent} onPointerMove={movePointer} onPointerUp={endPointer} onPointerCancel={endPointer}>{enc?.inside_image_url||enc?.image_url?<img className="cfgEnclosureBase" src={enc.inside_image_url||enc.image_url} alt={enc.name}/>:<div className="cfgNoAsset"><Layers3/><b>{enc?.name||'Choose enclosure'}</b><span>Upload inside-view PNG first.</span></div>}{slots.map(s=>{const preview=s.settings?.preview_image_url;return <div key={s.id} className={`cfgVisualSlot ${form.id===s.id?'active':''}`} onPointerDown={e=>startMove(e,s,'move')} style={{left:`${s.x_pct}%`,top:`${s.y_pct}%`,width:`${s.width_pct}%`,height:`${s.height_pct}%`,zIndex:s.z_index,transform:`rotate(${s.rotation_deg||0}deg)`}}>{preview?<img src={preview} alt={s.settings?.preview_name||s.option_key}/>:<div className="cfgSlotGhost"><span>{optionLabel(s.option_key)}</span><small>#{s.slot_index}</small></div>}<button type="button" className="cfgResizeHandle" aria-label="Resize component" onPointerDown={e=>startMove(e,s,'resize')}/><em>{s.settings?.preview_name||optionLabel(s.option_key)}</em></div>})}</div><div className="cfgCanvasTips"><span><MousePointer2/> Drag component to add</span><span>Drag placed item to move</span><span>Use bottom-right handle to resize</span><span>All values save in %</span></div></section>
 <form className="cfgSlotForm" onSubmit={save}><h2>{form.id?'Selected Layer':'Layer Settings'}</h2><label><span>Slot Key</span><input value={form.slot_key} onChange={e=>setForm({...form,slot_key:e.target.value})}/></label><label><span>Category / Option</span><select value={form.option_key} onChange={e=>setForm({...form,option_key:e.target.value})}>{optionKeys.map(x=><option key={x} value={x}>{optionLabel(x)}</option>)}</select></label><div className="cfgSlotNumbers"><label><span>Index</span><input type="number" value={form.slot_index} onChange={e=>setForm({...form,slot_index:e.target.value})}/></label><label><span>Layer Z</span><input type="number" value={form.z_index} onChange={e=>setForm({...form,z_index:e.target.value})}/></label><label><span>X %</span><input type="number" step="0.1" value={form.x_pct} onChange={e=>setForm({...form,x_pct:e.target.value})}/></label><label><span>Y %</span><input type="number" step="0.1" value={form.y_pct} onChange={e=>setForm({...form,y_pct:e.target.value})}/></label><label><span>Width %</span><input type="number" step="0.1" value={form.width_pct} onChange={e=>setForm({...form,width_pct:e.target.value})}/></label><label><span>Height %</span><input type="number" step="0.1" value={form.height_pct} onChange={e=>setForm({...form,height_pct:e.target.value})}/></label><label><span>Rotation °</span><input type="number" step="0.1" value={form.rotation_deg} onChange={e=>setForm({...form,rotation_deg:e.target.value})}/></label></div><label><span>Component Category</span><input value={form.component_category||''} onChange={e=>setForm({...form,component_category:e.target.value})}/></label>{form.settings?.preview_name&&<div className="cfgSelectedPreview"><span>Admin preview asset</span><b>{form.settings.preview_name}</b></div>}<label className="cfgCheck"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active on buyer preview</label><button className="adminBtn" disabled={!!savingId}><Save size={15}/>{savingId?'Saving…':'Save Layer'}</button>{form.id&&<button type="button" className="cfgDanger" onClick={()=>remove(form.id)}><Trash2 size={14}/>Delete Layer</button>}</form></div></div>
}
