'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {supabase} from '../../../lib/supabase'
import {canAdmin} from '../../../lib/adminAccess'
import type {AdminAccess} from '../../../lib/adminAccess'
import {catalogueProducts,emptyCatalogue,readCatalogueRows,validateCatalogue} from '../../../lib/pdf-catalogues'
import type {PdfCatalogue} from '../../../lib/pdf-catalogues'
import type {Product,Category} from '../../../lib/catalogue'
import CatalogueDownload from '../../../components/CatalogueDownload'
import '../../catalogues.css'
export default function CatalogueAdmin(){
 const [rows,setRows]=useState<PdfCatalogue[]>([]),[products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[access,setAccess]=useState<AdminAccess|null>(null),[draft,setDraft]=useState<PdfCatalogue|null>(null),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false)
 async function load(){setBusy(true);setMessage('');try{const signal=AbortSignal.timeout(60000);const [r,p,c,a]=await Promise.all([readCatalogueRows(supabase,'product_catalogues',signal),readCatalogueRows(supabase,'products',signal),readCatalogueRows(supabase,'categories',signal),supabase.rpc('get_my_admin_access')]);if(a.error)throw a.error;setRows(r.sort((a,b)=>a.sort_order-b.sort_order));setProducts(p);setCategories(c);setAccess(a.data);setLoaded(true)}catch(e){setMessage(e instanceof Error?e.message:'Unable to load catalogue manager.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 const matches=useMemo(()=>draft?catalogueProducts(draft,products,categories):[],[draft,products,categories])
 const allowed=(action:'create'|'edit'|'delete'|'export')=>canAdmin(access,'content',action)
 function edit(c:PdfCatalogue){setDraft({...c,category_ids:[...c.category_ids],product_ids:[...c.product_ids]});setQuery('');setMessage('')}
 async function save(){if(!draft)return;const invalid=validateCatalogue(draft);if(invalid){setMessage(invalid);return}if(draft.is_published&&!matches.length){setMessage('Select at least one available published product before publishing.');return}setBusy(true);setMessage('');try{const {id,...payload}=draft;const result=id?await supabase.from('product_catalogues').update(payload).eq('id',id).select('id').single():await supabase.from('product_catalogues').insert(payload).select('id').single();if(result.error)throw result.error;setDraft(null);await load();setMessage('Catalogue saved. Published catalogues are available on Downloads.')}catch(e){setMessage((e as Error).message||'Save failed.')}finally{setBusy(false)}}
 async function remove(c:PdfCatalogue){if(!confirm(`Delete catalogue “${c.title}”? Products and images will be kept.`))return;setBusy(true);try{const {error}=await supabase.from('product_catalogues').delete().eq('id',c.id!).select('id').single();if(error)throw error;await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 function toggle(field:'category_ids'|'product_ids',id:string){setDraft(d=>d?{...d,[field]:d[field].includes(id)?d[field].filter(x=>x!==id):[...d[field],id]}:d)}
 return <div className="catManager"><header className="catHero"><div><small>PRODUCT CATALOGUES</small><h1>Build your PDF catalogues</h1><p>One complete catalogue, separate categories, or a hand-picked product selection. Downloads use the latest published product details.</p></div><Link href="/downloads">View buyer downloads →</Link></header>
 <div className="catActions"><button className="catButton" disabled={busy||!allowed('create')} onClick={()=>edit(emptyCatalogue())}>New catalogue</button><button className="catButton secondary" disabled={busy} onClick={load}>Refresh</button></div>
 {message&&<p role="status" className="catNotice">{message}</p>}{!loaded&&<p>{busy?'Loading products and catalogues…':'Catalogue manager unavailable. Use Refresh to retry.'}</p>}
 {draft?<section className="catEditor"><h2>{draft.id?'Edit catalogue':'New catalogue'}</h2><label>Catalogue title<input maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Introduction<textarea maxLength={1000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Include<select value={draft.scope} onChange={e=>setDraft({...draft,scope:e.target.value as PdfCatalogue['scope']})}><option value="all">All published products — updates automatically</option><option value="categories">Selected categories and their subcategories</option><option value="products">Selected products</option></select></label>
 {draft.scope!=='all'&&<><label>Search {draft.scope}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="catSelections">{draft.scope==='categories'?categories.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=><label key={c.id}><input type="checkbox" checked={draft.category_ids.includes(c.id)} onChange={()=>toggle('category_ids',c.id)}/>{c.name}</label>):products.filter(p=>`${p.name} ${p.product_variants.map(v=>v.sku).join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p=><label key={p.id}><input type="checkbox" checked={draft.product_ids.includes(p.id)} onChange={()=>toggle('product_ids',p.id)}/>{p.name} <small>{p.product_variants.map(v=>v.sku).join(', ')}</small></label>)}</div></>}
 <label className="catCheck"><input type="checkbox" checked={draft.show_prices} onChange={e=>setDraft({...draft,show_prices:e.target.checked})}/>Include current selling prices and GST</label><label className="catCheck"><input type="checkbox" checked={draft.is_published} onChange={e=>setDraft({...draft,is_published:e.target.checked})}/>Publish on buyer Downloads page</label><label>Display order<input type="number" min={0} max={9999} value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Math.max(0,Math.min(9999,Number(e.target.value)||0))})}/></label>
 <p><b>{matches.length} published products</b> currently match. Unpublished products and inactive variants are excluded. Category catalogues include new products added to those categories.</p><details><summary>Review included products</summary><ul>{matches.map(p=><li key={p.id}>{p.name}</li>)}</ul></details><div className="catActions"><button className="catButton" disabled={busy||!allowed(draft.id?'edit':'create')} onClick={save}>Save catalogue</button><button className="catButton secondary" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button>{allowed('export')&&!validateCatalogue(draft)&&matches.length>0&&<CatalogueDownload catalogue={draft} preview/>}</div></section>:<div className="catGrid">{rows.map(c=><article key={c.id} className="catCard"><small>{c.is_published?'PUBLISHED':'DRAFT'} · {c.scope.toUpperCase()}</small><h2>{c.title}</h2><p>{c.description}</p><p>{catalogueProducts(c,products,categories).length} products · {c.show_prices?'With prices':'Without prices'}</p><div className="catActions"><button className="catButton secondary" disabled={busy||!allowed('edit')} onClick={()=>edit(c)}>Edit</button><button className="catButton secondary" disabled={busy||!allowed('delete')} onClick={()=>remove(c)}>Delete</button></div>{allowed('export')&&<CatalogueDownload catalogue={c} preview/>}</article>)}{loaded&&!rows.length&&<p>No catalogues yet. Create your first full-range or category catalogue.</p>}</div>}
 </div>
}
