'use client'

import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,CheckCircle2,CreditCard,Mail,MessageCircle,PackageCheck,RefreshCw,Repeat2,Save,Send,Smartphone,Truck} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import './transactions-v2.css'

type Tab='rules'|'templates'|'queue'|'shipments'
type Rule={id:string;event_key:string;channel:string;template_key:string;audience:string;is_active:boolean;delay_minutes:number;max_attempts:number;sort_order:number;communication_templates?:{name:string}|null}
type Template={template_key:string;channel:string;name:string;subject_template:string|null;body_template:string;provider_template_name:string|null;provider_template_language:string|null;is_active:boolean}
type Outbox={id:string;event_key:string;channel:string;template_key:string;reference_type:string;reference_id:string|null;recipient:string|null;status:string;attempts:number;max_attempts:number;provider_message_id:string|null;last_error:string|null;created_at:string;sent_at:string|null}
type Shipment={id:string;order_id:string;provider:string;provider_order_id:string|null;shipment_id:string|null;awb_code:string|null;courier_name:string|null;status:string;tracking_url:string|null;weight_kg:number|null;created_at:string}
type Order={id:string;order_number:string;status:string;payment_status:string;grand_total:number;customer_snapshot:any;created_at:string}

const fmt=(v:string|null)=>v?new Date(v).toLocaleString('en-IN'):'—'
const eventLabel=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function TransactionsPage(){
 const [tab,setTab]=useState<Tab>('rules'),[rules,setRules]=useState<Rule[]>([]),[templates,setTemplates]=useState<Template[]>([]),[outbox,setOutbox]=useState<Outbox[]>([]),[shipments,setShipments]=useState<Shipment[]>([]),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[editTemplate,setEditTemplate]=useState<Template|null>(null),[shipOpen,setShipOpen]=useState(false)
 const [shipForm,setShipForm]=useState({order_id:'',weight_kg:'',length_cm:'',breadth_cm:'',height_cm:'',payment_mode:'Prepaid',auto_assign_awb:true})
 useEffect(()=>{load()},[])
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||''}
 async function load(){setLoading(true);setMsg('');const [r,t,o,s,ord]=await Promise.all([
  supabase.from('communication_rules').select('*,communication_templates(name)').order('sort_order'),
  supabase.from('communication_templates').select('*').order('channel').order('name'),
  supabase.from('communication_outbox').select('*').order('created_at',{ascending:false}).limit(150),
  supabase.from('shipment_records').select('*').order('created_at',{ascending:false}).limit(100),
  supabase.from('orders').select('id,order_number,status,payment_status,grand_total,customer_snapshot,created_at').in('status',['confirmed','processing','ready_to_ship','shipped']).order('created_at',{ascending:false}).limit(100)
 ]);setRules((r.data||[]) as Rule[]);setTemplates((t.data||[]) as Template[]);setOutbox((o.data||[]) as Outbox[]);setShipments((s.data||[]) as Shipment[]);setOrders((ord.data||[]) as Order[]);const err=r.error||t.error||o.error||s.error||ord.error;if(err)setMsg(err.message);setLoading(false)}
 async function toggleRule(rule:Rule){setBusy(rule.id);const {error}=await supabase.from('communication_rules').update({is_active:!rule.is_active,updated_at:new Date().toISOString()}).eq('id',rule.id);setBusy('');setMsg(error?error.message:`${eventLabel(rule.event_key)} · ${rule.channel} ${rule.is_active?'disabled':'enabled'}.`);if(!error)await load()}
 async function saveTemplate(){if(!editTemplate)return;setBusy('template');const {error}=await supabase.from('communication_templates').update({name:editTemplate.name,subject_template:editTemplate.subject_template||null,body_template:editTemplate.body_template,provider_template_name:editTemplate.provider_template_name||null,provider_template_language:editTemplate.provider_template_language||'en',is_active:editTemplate.is_active,updated_at:new Date().toISOString()}).eq('template_key',editTemplate.template_key);setBusy('');setMsg(error?error.message:'Communication template saved.');if(!error){setEditTemplate(null);await load()}}
 async function enqueueReminders(){setBusy('reminders');const {data,error}=await supabase.rpc('transaction_enqueue_payment_reminders');setBusy('');setMsg(error?error.message:`${Number(data||0)} payment reminder message(s) added to the queue.`);if(!error)await load()}
 async function processQueue(){setBusy('process');const t=await token();const r=await fetch('/api/admin/transactions/process',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({limit:20})});const j=await r.json().catch(()=>({}));setBusy('');setMsg(r.ok?`${j.processed||0} queued communication(s) processed.`:j.error||'Queue processing failed.');await load()}
 async function retry(id:string){setBusy(id);const {error}=await supabase.rpc('transaction_retry_outbox',{p_id:id});setBusy('');setMsg(error?error.message:'Message returned to queue.');if(!error)await load()}
 async function createShipment(){if(!shipForm.order_id)return setMsg('Select an order first.');setBusy('shipment');const t=await token();const r=await fetch('/api/admin/transactions/shipment',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({action:'create',...shipForm,weight_kg:Number(shipForm.weight_kg),length_cm:Number(shipForm.length_cm),breadth_cm:Number(shipForm.breadth_cm),height_cm:Number(shipForm.height_cm)})});const j=await r.json().catch(()=>({}));setBusy('');setMsg(r.ok?`Shipment created${j.shipment?.awb_code?` · AWB ${j.shipment.awb_code}`:''}.`:j.error||'Shipment creation failed.');if(r.ok){setShipOpen(false);setShipForm({order_id:'',weight_kg:'',length_cm:'',breadth_cm:'',height_cm:'',payment_mode:'Prepaid',auto_assign_awb:true});await load()}}
 async function trackShipment(row:Shipment){setBusy(row.id);const t=await token();const r=await fetch('/api/admin/transactions/shipment',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({action:'track',order_id:row.order_id,awb_code:row.awb_code})});const j=await r.json().catch(()=>({}));setBusy('');setMsg(r.ok?`Tracking refreshed: ${j.status||'updated'}.`:j.error||'Tracking refresh failed.');if(r.ok)await load()}
 const kpi=useMemo(()=>({activeRules:rules.filter(x=>x.is_active).length,queued:outbox.filter(x=>x.status==='queued'||x.status==='processing').length,failed:outbox.filter(x=>x.status==='failed'||x.status==='blocked').length,shipments:shipments.length}),[rules,outbox,shipments])
 if(loading)return <div className="txEmpty">Loading transaction automation…</div>
 return <div className="txPage">
  <div className="txHead"><div><span className="txEyebrow"><Repeat2 size={15}/> CONTROL CENTER · STEP 21</span><h1>Transaction & Communication Automation</h1><p>Customer messages, payment reminders, shipment creation and transaction-event delivery from one queue.</p></div><div className="txActions"><button className="txBtn" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="txBtn" onClick={enqueueReminders} disabled={busy==='reminders'}><CreditCard size={16}/> Run Payment Reminders</button><button className="txBtn primary" onClick={processQueue} disabled={busy==='process'}><Send size={16}/> Process Queue</button></div></div>
  {msg&&<div className={`txMsg ${/saved|enabled|disabled|added|processed|created|refreshed|returned/i.test(msg)?'ok':''}`}>{/saved|enabled|disabled|added|processed|created|refreshed|returned/i.test(msg)?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}<span>{msg}</span></div>}
  <div className="txKpis"><article><span><Activity/></span><small>Active Rules</small><b>{kpi.activeRules}</b><em>{rules.length} total automation rules</em></article><article><span><Send/></span><small>Queued Messages</small><b>{kpi.queued}</b><em>Ready/retrying outbound items</em></article><article><span><AlertTriangle/></span><small>Failed / Blocked</small><b>{kpi.failed}</b><em>Needs configuration or retry</em></article><article><span><Truck/></span><small>Shipment Records</small><b>{kpi.shipments}</b><em>Shiprocket-linked orders</em></article></div>
  <div className="txTabs">{([['rules','Automation Rules',Repeat2],['templates','Message Templates',Mail],['queue','Outbound Queue',Send],['shipments','Shipments',Truck]] as const).map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={16}/>{l}</button>)}</div>

  {tab==='rules'&&<section className="txPanel"><div className="txPanelHead"><div><h2>Event → Communication Rules</h2><p>Rules are OFF by default. Enable only after the matching provider is configured and tested.</p></div></div><div className="txGrid">{rules.map(r=><article className="txRule" key={r.id}><div className="txRuleTop"><div><h3>{eventLabel(r.event_key)}</h3><p>{r.communication_templates?.name||r.template_key}</p></div><label className="txSwitch"><input type="checkbox" checked={r.is_active} disabled={busy===r.id} onChange={()=>toggleRule(r)}/>{r.is_active?'ON':'OFF'}</label></div><div className="txRuleMeta"><span className={`txPill ${r.channel}`}>{r.channel}</span><span className="txPill">Delay {r.delay_minutes}m</span><span className="txPill">Retries {r.max_attempts}</span><span className="txPill">{r.audience}</span></div></article>)}</div></section>}

  {tab==='templates'&&<section className="txPanel"><div className="txPanelHead"><div><h2>Customer Message Templates</h2><p>Use placeholders such as {'{{order_number}}'}, {'{{customer_name}}'}, {'{{invoice_number}}'} and {'{{balance_due}}'}.</p></div></div>{templates.map(t=><div className="txTemplate" key={t.template_key}><div className="txTemplateHead"><div><b>{t.name}</b><small>{t.channel} · {t.template_key}</small></div><button className="txBtn" onClick={()=>setEditTemplate({...t})}>Edit</button></div><div className="txRuleMeta"><span className={`txPill ${t.channel}`}>{t.channel}</span>{t.provider_template_name&&<span className="txPill">Provider template: {t.provider_template_name}</span>}</div><p style={{margin:0,color:'#667085',fontSize:13,whiteSpace:'pre-wrap'}}>{t.subject_template&&<><b>{t.subject_template}</b><br/></>}{t.body_template}</p></div>)}</section>}

  {tab==='queue'&&<section className="txPanel"><div className="txPanelHead"><div><h2>Outbound Queue</h2><p>Automatic event messages are queued first, then sent by the secure server processor.</p></div><button className="txBtn primary" onClick={processQueue} disabled={busy==='process'}><Send size={16}/> Process 20</button></div>{outbox.length?<div className="txTableWrap"><table><thead><tr><th>Created</th><th>Event</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Attempts</th><th>Provider ID / Error</th><th>Action</th></tr></thead><tbody>{outbox.map(x=><tr key={x.id}><td>{fmt(x.created_at)}</td><td><b>{eventLabel(x.event_key)}</b><br/><small>{x.reference_type}</small></td><td><span className={`txPill ${x.channel}`}>{x.channel}</span></td><td>{x.recipient||'—'}</td><td><span className={`txStatus ${x.status}`}>{x.status}</span></td><td>{x.attempts}/{x.max_attempts}</td><td>{x.provider_message_id||x.last_error||'—'}</td><td>{(x.status==='failed'||x.status==='blocked')&&<button className="txBtn" disabled={busy===x.id} onClick={()=>retry(x.id)}>Retry</button>}</td></tr>)}</tbody></table></div>:<div className="txEmpty"><Send/><b>No outbound messages</b><p>Messages appear when active rules receive matching order/payment/invoice events.</p></div>}</section>}

  {tab==='shipments'&&<section className="txPanel"><div className="txPanelHead"><div><h2>Shipment Automation</h2><p>Create Shiprocket orders from ERP orders and refresh tracking by AWB.</p></div><button className="txBtn primary" onClick={()=>setShipOpen(true)}><Truck size={16}/> Create Shipment</button></div>{shipments.length?<div className="txShipCards">{shipments.map(s=><article className="txShip" key={s.id}><h3>{orders.find(o=>o.id===s.order_id)?.order_number||s.order_id.slice(0,8)}</h3><p><b>Status:</b> {s.status}</p><p><b>Shipment:</b> {s.shipment_id||'—'} · <b>AWB:</b> {s.awb_code||'Pending'}</p><p><b>Courier:</b> {s.courier_name||'Not assigned'} · <b>Weight:</b> {s.weight_kg||'—'} kg</p><div className="txActions">{s.awb_code&&<button className="txBtn" disabled={busy===s.id} onClick={()=>trackShipment(s)}>Refresh Tracking</button>}{s.tracking_url&&<a className="txBtn" href={s.tracking_url} target="_blank" rel="noreferrer">Open Tracking</a>}</div></article>)}</div>:<div className="txEmpty"><Truck/><b>No shipments created yet</b><p>Connect and enable Shiprocket first, then create the first shipment from a confirmed/ready order.</p></div>}</section>}

  {editTemplate&&<div className="txModalBack" onMouseDown={()=>setEditTemplate(null)}><div className="txModal" onMouseDown={e=>e.stopPropagation()}><div className="txModalHead"><div><h2>Edit Message Template</h2><p>{editTemplate.channel} · {editTemplate.template_key}</p></div><button onClick={()=>setEditTemplate(null)}>×</button></div><div className="txForm"><label>Name<input value={editTemplate.name} onChange={e=>setEditTemplate({...editTemplate,name:e.target.value})}/></label><label>Provider Template / Flow ID<input value={editTemplate.provider_template_name||''} onChange={e=>setEditTemplate({...editTemplate,provider_template_name:e.target.value})} placeholder="Required for WhatsApp/SMS production templates"/></label>{editTemplate.channel==='email'&&<label className="full">Subject<input value={editTemplate.subject_template||''} onChange={e=>setEditTemplate({...editTemplate,subject_template:e.target.value})}/></label>}<label className="full">Body<textarea style={{minHeight:150}} value={editTemplate.body_template} onChange={e=>setEditTemplate({...editTemplate,body_template:e.target.value})}/></label><label>Provider Language<input value={editTemplate.provider_template_language||'en'} onChange={e=>setEditTemplate({...editTemplate,provider_template_language:e.target.value})}/></label><label className="txSwitch"><input type="checkbox" checked={editTemplate.is_active} onChange={e=>setEditTemplate({...editTemplate,is_active:e.target.checked})}/> Template active</label></div><div className="txModalFoot"><button className="txBtn" onClick={()=>setEditTemplate(null)}>Cancel</button><button className="txBtn primary" disabled={busy==='template'} onClick={saveTemplate}><Save size={16}/> Save Template</button></div></div></div>}

  {shipOpen&&<div className="txModalBack" onMouseDown={()=>setShipOpen(false)}><div className="txModal" onMouseDown={e=>e.stopPropagation()}><div className="txModalHead"><div><h2>Create Shiprocket Shipment</h2><p>Package dimensions are required so we never invent logistics data.</p></div><button onClick={()=>setShipOpen(false)}>×</button></div><div className="txForm"><label className="full">Order<select value={shipForm.order_id} onChange={e=>setShipForm({...shipForm,order_id:e.target.value})}><option value="">Select order</option>{orders.map(o=><option key={o.id} value={o.id}>{o.order_number} · ₹{Number(o.grand_total||0).toLocaleString('en-IN')} · {o.status}</option>)}</select></label><label>Weight (kg)<input type="number" step="0.001" value={shipForm.weight_kg} onChange={e=>setShipForm({...shipForm,weight_kg:e.target.value})}/></label><label>Payment Mode<select value={shipForm.payment_mode} onChange={e=>setShipForm({...shipForm,payment_mode:e.target.value})}><option>Prepaid</option><option>COD</option></select></label><label>Length (cm)<input type="number" step="0.01" value={shipForm.length_cm} onChange={e=>setShipForm({...shipForm,length_cm:e.target.value})}/></label><label>Breadth (cm)<input type="number" step="0.01" value={shipForm.breadth_cm} onChange={e=>setShipForm({...shipForm,breadth_cm:e.target.value})}/></label><label>Height (cm)<input type="number" step="0.01" value={shipForm.height_cm} onChange={e=>setShipForm({...shipForm,height_cm:e.target.value})}/></label><label className="txSwitch"><input type="checkbox" checked={shipForm.auto_assign_awb} onChange={e=>setShipForm({...shipForm,auto_assign_awb:e.target.checked})}/> Auto-assign AWB</label></div><div className="txModalFoot"><button className="txBtn" onClick={()=>setShipOpen(false)}>Cancel</button><button className="txBtn primary" onClick={createShipment} disabled={busy==='shipment'}><PackageCheck size={16}/> {busy==='shipment'?'Creating…':'Create Shipment'}</button></div></div></div>}
 </div>
}
