'use client'
import {FormEvent,Suspense,useEffect,useState} from 'react'
import Link from 'next/link'
import {useRouter,useSearchParams} from 'next/navigation'
import {LockKeyhole, Loader2, ShieldCheck, UserPlus} from 'lucide-react'
import {supabase} from '../../lib/supabase'
import PhoneOtp from '../../components/PhoneOtp'
import {safeNext} from '../../lib/buyer-account'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'

function LoginContent(){
  const router=useRouter(); const search=useSearchParams();
  const [method,setMethod]=useState<'email'|'phone'>('email'); const [mode,setMode]=useState<'login'|'signup'>('login'); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('')
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user)router.replace(safeNext(search.get('next')))})},[router,search])
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const email=String(f.get('email')||'');const password=String(f.get('password')||'');const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:String(f.get('name')||'')}}});setBusy(false);if(result.error){setMsg(result.error.message);return}if(mode==='signup'&&!result.data.session){setMsg('Account created. Please verify your email, then sign in.');setMode('login');return}router.replace(safeNext(search.get('next')));router.refresh()}
  return <><StoreHeader/><main className="loginPage"><div className="container loginGrid"><section className="loginPitch"><span className="nisKicker"><i/>NEW INDIA SOLAR ACCOUNT</span><h1>One account for products, custom builds and orders.</h1><p>Use your account to place secure orders, keep purchases linked to your business and review order history.</p><div className="loginBenefits"><div><ShieldCheck size={18}/><span><b>Secure checkout</b><small>Orders tied to your authenticated account</small></span></div><div><LockKeyhole size={18}/><span><b>Server-verified pricing</b><small>Prices validated against the live product master</small></span></div></div></section><section className="authCard premiumAuth"><div className="authIcon">{mode==='login'?<LockKeyhole/>:<UserPlus/>}</div><span className="eyebrow darkEye">{mode==='login'?'WELCOME BACK':'CREATE YOUR ACCOUNT'}</span><h1>{mode==='login'?'Sign in':'Create account'}</h1><p>{mode==='login'?'Access your account and continue ordering.':'Create an account for secure ordering and tracking.'}</p><div className="buyerActions"><button type="button" aria-pressed={method==='email'} onClick={()=>setMethod('email')}>Email</button><button type="button" aria-pressed={method==='phone'} onClick={()=>setMethod('phone')}>Mobile OTP</button></div>{method==='phone'?<PhoneOtp onSuccess={()=>{router.replace(safeNext(search.get('next')));router.refresh()}}/>:<form className="authForm" onSubmit={submit}>{mode==='signup'&&<label>Full Name<input name="name" autoComplete="name" required placeholder="Your full name"/></label>}<label>Email<input name="email" type="email" autoComplete="email" required placeholder="name@company.com"/></label><label>Password<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={6} required placeholder="Minimum 6 characters"/></label><button className="nisPrimaryBtn authSubmit" disabled={busy}>{busy?<><Loader2 className="spin" size={17}/> Please wait…</>:mode==='login'?'Sign In':'Create Account'}</button></form>}{msg&&<p className="formMessage">{msg}</p>}<button className="textButton" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'New customer? Create account':'Already registered? Sign in'}</button><Link className="bulkLink center" href="/shop">← Back to products</Link></section></div></main><StoreFooter/></>
}

export default function Login(){return <Suspense fallback={<main className="container formPage"><div className="authCard"><p>Loading account…</p></div></main>}><LoginContent/></Suspense>}
