'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {useParams} from 'next/navigation'
import {CheckCircle2, Minus, Plus, ShieldCheck, ShoppingCart, Truck} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import {useCart} from '../../../components/CartProvider'
import StoreHeader from '../../../components/StoreHeader'
import StoreFooter from '../../../components/StoreFooter'

export default function Product(){
  const {slug}=useParams<{slug:string}>();const [p,setP]=useState<any>(null);const [variantId,setVariantId]=useState('');const [qty,setQty]=useState(1);const [loading,setLoading]=useState(true);const {add}=useCart()
  useEffect(()=>{supabase.from('products').select('*,categories(name,slug),product_images(*),product_variants(*)').eq('slug',slug).single().then(({data})=>{setP(data);setVariantId(data?.product_variants?.[0]?.id||'');setLoading(false)})},[slug])
  const variants=p?.product_variants||[];const v=variants.find((x:any)=>x.id===variantId)||variants[0];const price=Number(v?.selling_price||0);const mrp=Number(v?.mrp||0);const stock=Number(v?.stock_qty||0);const attrs=v?.attributes||{};const discount=mrp>price&&price>0?Math.round((1-price/mrp)*100):0
  if(loading)return <><StoreHeader/><main className="container productLoading"><div/><div/></main></>
  if(!p)return <><StoreHeader/><main className="container emptyCatalogue"><h1>Product not found.</h1><Link className="btn btnPrimary" href="/shop">Back to Products</Link></main></>
  function addToCart(){if(!v||price<=0||stock<=0)return;add({id:v.id,kind:'standard',productVariantId:v.id,name:p.name,variant:v.title||v.sku,price,qty:Math.min(qty,stock)})}
  return <><StoreHeader/><main className="container productDetail"><section className="detailImage"><div className="productHeroBox"><div className="miniBox big"/><span>NEW INDIA SOLAR</span></div><div className="detailImageBadges"><span><ShieldCheck size={14}/> Solar BOS</span><span><Truck size={14}/> Pan-India dispatch</span></div></section><section className="productBuyPanel"><Link className="productBreadcrumb" href="/shop">Products / {p.categories?.name||'Solar Component'}</Link><span className="eyebrow darkEye">{p.categories?.name||'Solar Component'}</span><h1>{p.name}</h1><p>{p.short_description||p.description||'New India Solar component for solar installation projects.'}</p><div className="productMetaRow"><span className={stock>0?'stockLine in':'stockLine'}>{stock>0?<><CheckCircle2 size={14}/> In demo stock: {stock} {v?.unit||'pcs'}</>:<>Available on request</>}</span><span>GST {p.gst_rate||18}%</span>{p.warranty_months?<span>{p.warranty_months} month warranty</span>:null}</div><div className="notice">Demo/reference market price for system testing — not the final New India Solar commercial rate.</div>{variants.length>1&&<div className="variantBlock"><label>Choose Variant</label><div className="variantChips">{variants.map((x:any)=><button key={x.id} className={x.id===v?.id?'active':''} onClick={()=>{setVariantId(x.id);setQty(1)}}><b>{x.title||x.sku}</b><span>₹{Number(x.selling_price||0).toLocaleString('en-IN')}</span></button>)}</div></div>}<div className="priceBlock"><div><span>Demo selling price</span><strong>{price>0?`₹${price.toLocaleString('en-IN')}`:'Price on request'}</strong></div>{mrp>price&&price>0?<div className="mrpBlock"><del>₹{mrp.toLocaleString('en-IN')}</del><b>{discount}% off</b></div>:null}</div>{price>0&&stock>0?<div className="buyRow"><div className="qtyPicker"><button aria-label="Decrease quantity" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={16}/></button><span>{qty}</span><button aria-label="Increase quantity" onClick={()=>setQty(Math.min(stock,qty+1))}><Plus size={16}/></button></div><button className="nisPrimaryBtn productAddBtn" onClick={addToCart}><ShoppingCart size={18}/> Add to Cart</button></div>:<Link className="nisPrimaryBtn productAddBtn" href="/bulk-order">Request Price <ShoppingCart size={18}/></Link>}<div className="productServiceGrid"><div><CheckCircle2/><b>GST-ready order</b><span>Business checkout supported</span></div><div><ShieldCheck/><b>Project supply</b><span>Bulk RFQ available</span></div><div><Truck/><b>Dispatch support</b><span>Shipping confirmed at order stage</span></div></div>{Object.keys(attrs).length>0&&<div className="specTable"><h3>Variant Specifications</h3>{Object.entries(attrs).map(([k,val]:any)=><div key={k}><span>{k.replaceAll('_',' ')}</span><b>{String(val)}</b></div>)}</div>}<div className="productActionsBottom"><Link className="btn" href="/bulk-order">Need bulk quantity? Get project price →</Link></div></section></main><StoreFooter/></>
}
