'use client'

import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {CheckCircle2, Search, SlidersHorizontal, ShoppingCart} from 'lucide-react'
import {supabase} from '../../lib/supabase'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'
import {useCart} from '../../components/CartProvider'

export default function Shop(){
  const [products,setProducts]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[sort,setSort]=useState('featured'),[loading,setLoading]=useState(true)
  const {add}=useCart()
  useEffect(()=>{if(typeof window!=='undefined'){setQ(new URLSearchParams(window.location.search).get('q')||'')}Promise.all([supabase.from('products').select('id,name,slug,short_description,product_type,status,featured,categories(name,slug),product_variants(id,sku,title,selling_price,mrp,stock_qty,unit)').eq('status','active').limit(100),supabase.from('categories').select('id,name,slug').eq('is_active',true).order('sort_order')]).then(([p,c])=>{setProducts(p.data||[]);setCats(c.data||[]);setLoading(false)})},[])
  const filtered=useMemo(()=>{let list=products.filter((p:any)=>(cat==='all'||p.categories?.slug===cat)&&(`${p.name} ${p.short_description||''} ${p.categories?.name||''}`.toLowerCase().includes(q.toLowerCase())));if(sort==='low')list=[...list].sort((a,b)=>Number(a.product_variants?.[0]?.selling_price||0)-Number(b.product_variants?.[0]?.selling_price||0));if(sort==='high')list=[...list].sort((a,b)=>Number(b.product_variants?.[0]?.selling_price||0)-Number(a.product_variants?.[0]?.selling_price||0));if(sort==='name')list=[...list].sort((a,b)=>a.name.localeCompare(b.name));return list},[products,cat,q,sort])
  return <><StoreHeader/><main className="container shopPage"><div className="shopHead"><div><span className="eyebrow darkEye">SOLAR COMPONENT STORE</span><h1>Products for reliable solar installations.</h1><p>Browse ready products, protection devices, cable, connectors and BOS accessories.</p></div><div className="searchBox"><Search size={17}/><input placeholder="Search ACDB, SPD, cable..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="notice">Demo/reference prices are enabled for website testing. Replace with approved New India Solar commercial rates before launch.</div><div className="shopToolbar"><div className="filterTabs"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{cats.map(c=><button key={c.id} className={cat===c.slug?'active':''} onClick={()=>setCat(c.slug)}>{c.name}</button>)}</div><label className="shopSort"><SlidersHorizontal size={15}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="name">Name A-Z</option></select></label></div>{loading?<div className="catalogueLoading"><div/><div/><div/><div/></div>:!filtered.length?<div className="emptyCatalogue"><h2>No matching products.</h2><p>Try another category or search term.</p><button className="btn btnPrimary" onClick={()=>{setQ('');setCat('all')}}>Clear Filters</button></div>:<><div className="catalogueCount">Showing {filtered.length} product{filtered.length!==1?'s':''}</div><div className="productGrid">{filtered.map(p=>{const v=p.product_variants?.[0];const price=Number(v?.selling_price||0);const mrp=Number(v?.mrp||0);const stock=Number(v?.stock_qty||0);return <article className="productCard" key={p.id}><Link href={`/product/${p.slug}`} className="productImg"><div className="miniBox"/><span className="productBadge">{p.featured?'Featured':'Solar Component'}</span></Link><small>{p.categories?.name||'Solar Component'}</small><h3>{p.name}</h3><p>{p.short_description||'New India Solar component for solar installation projects.'}</p><div className="amount">{price>0?`₹${price.toLocaleString('en-IN')}`:'Price on request'}{mrp>price&&price>0?<del>₹{mrp.toLocaleString('en-IN')}</del>:null}</div><div className={stock>0?'stockLine in':'stockLine'}>{stock>0?<><CheckCircle2 size={13}/> In demo stock: {stock} {v?.unit||'pcs'}</>:<>Available on request</>}</div><div className="productCardActions"><Link className="btn" href={`/product/${p.slug}`}>Details</Link>{v&&price>0&&stock>0?<button className="btn btnPrimary" onClick={()=>add({id:v.id,kind:'standard',productVariantId:v.id,name:p.name,variant:v.title||v.sku,price,qty:1})}><ShoppingCart size={15}/> Add</button>:<Link className="btn btnPrimary" href="/bulk-order">Enquire</Link>}</div></article>})}</div></>}</main><StoreFooter/></>
}
