'use client'
import {useEffect,useMemo,useState} from 'react'
import {CheckCircle2,Copy,KeyRound,Plus,RefreshCw,RotateCcw,Save,Search,ShieldCheck,Sparkles,Trash2,X} from 'lucide-react'
import {supabase} from '../../lib/supabase'

type UserRow={id:string;email:string|null;phone:string|null;full_name:string|null;role:string;admin_role:string|null;staff_status:string;job_title:string|null;email_confirmed:boolean;last_sign_in_at:string|null;created_at:string;banned:boolean;must_change_password:boolean;password_changed_at:string|null;mfa_required:boolean;mfa_enrolled:boolean;session_count:number;last_session_at:string|null;access_reviewed_at:string|null}
type EditUser={full_name:string;email:string;phone:string;role:string;admin_role:string;staff_status:string;job_title:string;must_change_password:boolean;mfa_required:boolean}
type RoleDef={role_key:string;name:string;is_system:boolean}
type ModuleRow={module_key:string;label:string;description:string|null;sort_order:number}
type RolePermission={role_key:string;module_key:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_delete:boolean;can_approve:boolean;can_export:boolean}
type UserOverride={user_id:string;module_key:string;action_key:string;allowed:boolean;expires_at:string|null;reason:string|null}
type Metrics={must_change_password:number;mfa_required:number;mfa_enrolled:number;active_sessions:number;unreviewed_team:number}
const actions=[['view','View'],['create','Create'],['edit','Edit'],['delete','Delete'],['approve','Approve'],['export','Export']] as const
const emptyMetrics={must_change_password:0,mfa_required:0,mfa_enrolled:0,active_sessions:0,unreviewed_team:0}
function fmt(value:string|null){return value?new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Never'}
function initials(user:UserRow){return (user.full_name||user.email||'U').trim().slice(0,1).toUpperCase()}
function generatedPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789',symbols='!@#$%&*',bytes=crypto.getRandomValues(new Uint8Array(18)),pieces=['A','a','7','#'];for(let i=0;i<11;i++)pieces.push(chars[bytes[i]%chars.length]);pieces.push(symbols[bytes[11]%symbols.length]);for(let i=pieces.length-1;i>0;i--){const j=bytes[(i+2)%bytes.length]%(i+1);[pieces[i],pieces[j]]=[pieces[j],pieces[i]]}return pieces.join('')}

export default function AdminUsersPanel(){
 const [users,setUsers]=useState<UserRow[]>([]),[roles,setRoles]=useState<RoleDef[]>([]),[modules,setModules]=useState<ModuleRow[]>([]),[rolePermissions,setRolePermissions]=useState<RolePermission[]>([]),[overrides,setOverrides]=useState<UserOverride[]>([]),[draftOverrides,setDraftOverrides]=useState<UserOverride[]>([])
 const [metrics,setMetrics]=useState<Metrics>(emptyMetrics),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all')
 const [selected,setSelected]=useState<UserRow|null>(null),[edit,setEdit]=useState<EditUser|null>(null),[password,setPassword]=useState(''),[showCredential,setShowCredential]=useState(false),[overrideDirty,setOverrideDirty]=useState(false),[overrideModule,setOverrideModule]=useState('dashboard'),[overrideAction,setOverrideAction]=useState('view'),[overrideAllowed,setOverrideAllowed]=useState(true),[overrideExpiry,setOverrideExpiry]=useState(''),[overrideReason,setOverrideReason]=useState('')
 const roleName=(key:string|null)=>roles.find(role=>role.role_key===(key||'general'))?.name||key||'Team User'
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||''}
 async function load(clear=true){setLoading(true);if(clear)setMessage('');const t=await token();const [r,moduleRes,roleRes,permissionRes,overrideRes]=await Promise.all([fetch('/api/admin/team-users',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),supabase.from('admin_modules').select('module_key,label,description,sort_order').order('sort_order'),supabase.from('admin_role_definitions').select('role_key,name,is_system').order('sort_order'),supabase.from('admin_role_permissions').select('role_key,module_key,can_view,can_create,can_edit,can_delete,can_approve,can_export'),supabase.from('admin_user_permissions').select('user_id,module_key,action_key,allowed,expires_at,reason')]);const body=await r.json().catch(()=>({}));setLoading(false);const error=moduleRes.error||roleRes.error||permissionRes.error||overrideRes.error;if(!r.ok||error){setMessage(body.error||error?.message||'Could not load users.');return}setUsers(body.users||[]);setMetrics(body.security||emptyMetrics);setModules((moduleRes.data||[]) as ModuleRow[]);setRoles((roleRes.data||[]) as RoleDef[]);setRolePermissions((permissionRes.data||[]) as RolePermission[]);setOverrides((overrideRes.data||[]) as UserOverride[])}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return users.filter(user=>(filter==='all'||(filter==='team'?['admin','staff'].includes(user.role):filter==='customers'?user.role==='customer':filter==='attention'?(user.banned||user.staff_status!=='active'||user.must_change_password||(user.mfa_required&&!user.mfa_enrolled)):true))&&(!q||`${user.full_name||''} ${user.email||''} ${user.phone||''} ${user.job_title||''}`.toLowerCase().includes(q)))},[users,search,filter])
 function open(user:UserRow){setSelected(user);setEdit({full_name:user.full_name||'',email:user.email||'',phone:user.phone||'',role:user.role,admin_role:user.admin_role||'general',staff_status:user.banned?'suspended':user.staff_status||'active',job_title:user.job_title||'',must_change_password:user.must_change_password,mfa_required:user.mfa_required});setDraftOverrides(overrides.filter(row=>row.user_id===user.id));setOverrideDirty(false);setPassword('');setShowCredential(false);setMessage('')}
 async function request(body:Record<string,unknown>){setBusy(true);setMessage('');const t=await token();const r=await fetch('/api/admin/team-users',{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMessage(result.error||'User update failed.');return false}await load(false);setMessage(result.message||'User updated.');return true}
 async function save(){if(!selected||!edit)return;const ok=await request({action:'update_user',user_id:selected.id,...edit});if(ok)setSelected(null)}
 async function resetPassword(){if(!selected||!password)return;const ok=await request({action:'reset_password',user_id:selected.id,temporary_password:password});if(ok){setShowCredential(true);setEdit(v=>v&&({...v,must_change_password:true}))}}
 async function resetMfa(){
  if(!selected||!password)return
  const reason=window.prompt('Recovery reason: how did you verify this employee’s identity? (10–500 characters)')
  if(!reason||!window.confirm('I verified this employee’s identity outside this login. Reset their password, remove their authenticators, and require a new password and 2FA setup?'))return
  const ok=await request({action:'reset_mfa',user_id:selected.id,temporary_password:password,reason,identity_confirmed:true})
  if(ok){setShowCredential(true);setEdit(v=>v&&({...v,must_change_password:true,mfa_required:true}));setSelected(v=>v&&({...v,mfa_enrolled:false,mfa_required:true,must_change_password:true}))}
 }
 function roleAllows(moduleKey:string,actionKey:string){const row=rolePermissions.find(item=>item.role_key===edit?.admin_role&&item.module_key===moduleKey);return Boolean(row?.[`can_${actionKey}` as keyof RolePermission])}
 function effectiveAllows(moduleKey:string,actionKey:string){const override=draftOverrides.find(row=>row.module_key===moduleKey&&row.action_key===actionKey&&(!row.expires_at||new Date(row.expires_at).getTime()>Date.now()));return override?override.allowed:roleAllows(moduleKey,actionKey)}
 function addOverride(){if(!selected)return;const expires=overrideExpiry?new Date(overrideExpiry).toISOString():null,next:UserOverride={user_id:selected.id,module_key:overrideModule,action_key:overrideAction,allowed:overrideAllowed,expires_at:expires,reason:overrideReason.trim()||null};setDraftOverrides(rows=>[...rows.filter(row=>!(row.module_key===next.module_key&&row.action_key===next.action_key)),next]);setOverrideDirty(true);setOverrideReason('')}
 async function saveOverrides(){if(!selected)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {error:removeError}=await supabase.from('admin_user_permissions').delete().eq('user_id',selected.id);if(removeError){setBusy(false);setMessage(removeError.message);return}const result=draftOverrides.length?await supabase.from('admin_user_permissions').insert(draftOverrides.map(row=>({...row,updated_by:user?.id||null,updated_at:new Date().toISOString()}))):{error:null};setBusy(false);if(result.error){setMessage(`${result.error.message} Role defaults remain active.`);await load(false);return}await load(false);setOverrideDirty(false);setMessage('Individual access rules saved.')}
 const effectiveSummary=useMemo(()=>modules.filter(m=>m.module_key!=='staff_directory').map(module=>({module,allowed:actions.filter(([key])=>effectiveAllows(module.module_key,key)).map(([,label])=>label)})).filter(row=>row.allowed.length),[modules,rolePermissions,draftOverrides,edit])
 return <section className="accessPanel usersWorkspace">
  <span className="srOnly">Additional Access Overrides · Save Additional Access</span>
  <div className="accessPanelHead"><div><h2>All Users & Security</h2><p>Manage every Auth account, effective access, temporary grants, MFA readiness and login recovery.</p></div><button onClick={()=>load()} disabled={loading}><RefreshCw size={15}/> Refresh</button></div>
  <div className="roleMetricCards"><article><small>Active Sessions</small><b>{metrics.active_sessions}</b></article><article><small>Password Change Due</small><b>{metrics.must_change_password}</b></article><article><small>MFA Enrolled</small><b>{metrics.mfa_enrolled}/{metrics.mfa_required}</b></article><article><small>Access Review Due</small><b>{metrics.unreviewed_team}</b></article></div>
  {message&&<div className="accessMessage" role="status"><ShieldCheck size={16}/>{message}</div>}
  <div className="usersToolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, mobile or title"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All users</option><option value="team">Team users</option><option value="customers">Customers</option><option value="attention">Security attention</option></select><b>{filtered.length} of {users.length}</b></div>
  {loading?<div className="accessLoading">Loading all users…</div>:<div className="usersTableWrap"><table className="usersTable"><thead><tr><th>User</th><th>Account</th><th>Security</th><th>Last sign-in</th><th/></tr></thead><tbody>{filtered.map(user=><tr key={user.id}><td><div className="userIdentity"><span>{initials(user)}</span><div><b>{user.full_name||'Unnamed user'}</b><small>{user.email||'No email'}{user.phone?` · ${user.phone}`:''}</small></div></div></td><td><strong>{user.role==='admin'?'Owner Admin':user.role==='staff'?roleName(user.admin_role):'Customer'}</strong><small>{user.job_title||user.role}</small></td><td><span className={`userStatus ${user.banned||user.staff_status!=='active'?'blocked':'active'}`}>{user.banned||user.staff_status!=='active'?'Blocked':'Active'}</span><small>{user.must_change_password?'Password change due':user.mfa_required?(user.mfa_enrolled?'MFA ready':'MFA setup due'):`${user.session_count} session${user.session_count===1?'':'s'}`}</small></td><td>{fmt(user.last_sign_in_at)}<small>Reviewed {fmt(user.access_reviewed_at)}</small></td><td><button onClick={()=>open(user)}><Save size={15}/> {user.role==='admin'?'View':'Manage'}</button></td></tr>)}</tbody></table></div>}
  {selected&&edit&&<div className="userModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="userModal" role="dialog" aria-modal="true"><button className="userModalClose" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><span className="adminEyebrow">USER MANAGEMENT</span><h2>{selected.full_name||selected.email}</h2><p>{selected.session_count} active session{selected.session_count===1?'':'s'} · last session {fmt(selected.last_session_at)}</p>{selected.role==='admin'?<div className="accessSecurityNote"><ShieldCheck size={17}/><span>Owner Admin identity and access are protected. Personal MFA and device controls are available in Account Security.</span></div>:<>
   <div className="userEditGrid"><label>Full Name<input value={edit.full_name} onChange={e=>setEdit(v=>v&&({...v,full_name:e.target.value}))}/></label><label>Email<input type="email" value={edit.email} onChange={e=>setEdit(v=>v&&({...v,email:e.target.value}))}/></label><label>Mobile<input value={edit.phone} onChange={e=>setEdit(v=>v&&({...v,phone:e.target.value}))}/></label><label>Account Type<select value={edit.role} onChange={e=>setEdit(v=>v&&({...v,role:e.target.value}))}><option value="customer">Customer</option><option value="staff">Team User</option></select></label>{edit.role==='staff'&&<><label>Department Role<select value={edit.admin_role} onChange={e=>setEdit(v=>v&&({...v,admin_role:e.target.value}))}>{roles.filter(r=>r.role_key!=='admin').map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select></label><label>Job Title<input value={edit.job_title} onChange={e=>setEdit(v=>v&&({...v,job_title:e.target.value}))}/></label></>}<label>Login Status<select value={edit.staff_status} onChange={e=>setEdit(v=>v&&({...v,staff_status:e.target.value}))}><option value="active">Active</option><option value="suspended">Suspended</option><option value="inactive">Inactive</option></select></label>{edit.role==='staff'&&<><label><input type="checkbox" checked={edit.must_change_password} onChange={e=>setEdit(v=>v&&({...v,must_change_password:e.target.checked}))}/> Require password change</label><label><input type="checkbox" checked={edit.mfa_required} onChange={e=>setEdit(v=>v&&({...v,mfa_required:e.target.checked}))}/> Require MFA {selected.mfa_enrolled?'(enrolled)':'(not enrolled)'}</label></>}</div><button className="accessPrimary" onClick={save} disabled={busy}><Save size={15}/> Save User & Security</button>
   {edit.role==='staff'&&<section className="userOverrides"><div className="userOverridesHead"><div><ShieldCheck size={18}/><div><h3>Temporary & Individual Access</h3><p>Set an optional expiry. Expired rules stop affecting authorization automatically.</p></div></div><b>{draftOverrides.length} rules</b></div><div className="overrideBuilder"><label>Module<select value={overrideModule} onChange={e=>setOverrideModule(e.target.value)}>{modules.filter(m=>m.module_key!=='staff_directory').map(m=><option key={m.module_key} value={m.module_key}>{m.label}</option>)}</select></label><label>Action<select value={overrideAction} onChange={e=>setOverrideAction(e.target.value)}>{actions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Rule<select value={overrideAllowed?'allow':'deny'} onChange={e=>setOverrideAllowed(e.target.value==='allow')}><option value="allow">Allow</option><option value="deny">Block</option></select></label><label>Expires<input type="datetime-local" value={overrideExpiry} onChange={e=>setOverrideExpiry(e.target.value)}/></label><label>Reason<input value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Project or approval reference"/></label><button type="button" onClick={addOverride}><Plus size={15}/> Add Rule</button></div><div className="overrideRows">{draftOverrides.map(row=><div key={`${row.module_key}-${row.action_key}`}><span><b>{modules.find(m=>m.module_key===row.module_key)?.label}</b><small>{row.action_key} · default {roleAllows(row.module_key,row.action_key)?'allowed':'blocked'} · expires {fmt(row.expires_at)}{row.reason?` · ${row.reason}`:''}</small></span><em className={row.allowed?'allow':'deny'}>{row.allowed?'ALLOW':'BLOCK'}</em><button onClick={()=>{setDraftOverrides(v=>v.filter(x=>x!==row));setOverrideDirty(true)}}><Trash2 size={14}/></button></div>)}</div><div className="overrideActions"><span className={overrideDirty?'dirty':'saved'}>{overrideDirty?'Unsaved changes':'Rules saved'}</span><button onClick={()=>{setDraftOverrides(overrides.filter(r=>r.user_id===selected.id));setOverrideDirty(false)}} disabled={!overrideDirty}><RotateCcw size={14}/> Discard</button><button className="accessPrimary" onClick={saveOverrides} disabled={!overrideDirty||busy}><Save size={14}/> Save Access</button></div><h3>Effective Access Preview</h3><div className="overrideRows">{effectiveSummary.map(row=><div key={row.module.module_key}><span><b>{row.module.label}</b><small>{row.allowed.join(', ')}</small></span><em className="allow">{row.allowed.length} ACTIONS</em></div>)}</div></section>}
   {selected.role==='staff'&&<div className="userPasswordReset"><h3>Lost authenticator recovery</h3><p>Verify the employee’s identity first and enter a new temporary password below. Recovery requires your own 2FA verification and forces the employee to activate 2FA again.</p><button className="accessPrimary" disabled={busy||!password} onClick={resetMfa}>Recover staff authenticator</button></div>}<div className="userPasswordReset"><div><KeyRound size={18}/><div><h3>Reset Login Password</h3><p>The temporary password will force a private password change at next login.</p></div></div><div className="accessPasswordRow"><input value={password} onChange={e=>{setPassword(e.target.value);setShowCredential(false)}} placeholder="12+ characters"/><button onClick={()=>setPassword(generatedPassword())}><Sparkles size={14}/> Generate</button></div><button className="accessPrimary" onClick={resetPassword} disabled={busy||!password}><KeyRound size={15}/> Set Temporary Password</button>{showCredential&&<div className="accessCredential"><strong>Password updated</strong><code>{password}</code><button onClick={()=>navigator.clipboard.writeText(`New India Solar admin login\nEmail: ${edit.email}\nTemporary password: ${password}\nLogin: ${location.origin}/admin/login`)}><Copy size={14}/> Copy details</button><span><CheckCircle2 size={13}/> User must replace it after login.</span></div>}</div></>}
  </div></div>}
 </section>
}
