'use client'

import {useEffect,useMemo,useState} from 'react'
import {Activity,AlertTriangle,CheckCircle2,Clock,CreditCard,KeyRound,Link2,Mail,MessageCircle,RefreshCw,Save,Server,Settings,ShieldCheck,Smartphone,Truck} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import './integrations-v2.css'

type Tab='connections'|'events'|'webhooks'|'setup'
type Integration={integration_key:string;channel:string;provider:string;display_name:string;description:string|null;is_enabled:boolean;environment:'sandbox'|'live';public_config:Record<string,any>;required_env_keys:string[];last_test_status:string;last_tested_at:string|null;last_test_message:string|null;updated_at:string}
type Readiness={key:string;configured:boolean;required:string[];missing:string[];configured_count:number;total_required:number}
type EventLog={id:string;integration_key:string;direction:string;event_type:string;status:string;external_id:string|null;reference_type:string|null;error_message:string|null;created_at:string}
type WebhookLog={id:string;integration_key:string;provider_event_id:string|null;event_type:string|null;signature_valid:boolean|null;processing_status:string;payload_hash:string;error_message:string|null;received_at:string}

const iconMap:Record<string,any>={whatsapp:MessageCircle,email:Mail,sms:Smartphone,payment:CreditCard,shipping:Truck,webhook:Link2}
const providerLabel:Record<string,string>={meta_cloud:'Meta Cloud API',resend:'Resend',msg91:'MSG91',razorpay:'Razorpay',shiprocket:'Shiprocket',custom_hmac:'Signed Webhook'}
const fmt=(v:string|null)=>v?new Date(v).toLocaleString('en-IN'):'Never'

export default function IntegrationsPage(){
 const [tab,setTab]=useState<Tab>('connections'),[items,setItems]=useState<Integration[]>([]),[readiness,setReadiness]=useState<Readiness[]>([]),[logs,setLogs]=useState<EventLog[]>([]),[webhooks,setWebhooks]=useState<WebhookLog[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[edit,setEdit]=useState<Integration|null>(null)
 useEffect(()=>{load()},[])
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||''}
 async function load(){
  setLoading(true);setMsg('')
  const [s,l,w]=await Promise.all([
   supabase.from('integration_settings').select('*').order('channel'),
   supabase.from('integration_event_logs').select('id,integration_key,direction,event_type,status,external_id,reference_type,error_message,created_at').order('created_at',{ascending:false}).limit(100),
   supabase.from('integration_webhook_events').select('id,integration_key,provider_event_id,event_type,signature_valid,processing_status,payload_hash,error_message,received_at').order('received_at',{ascending:false}).limit(100)
  ])
  setItems((s.data||[]) as Integration[]);setLogs((l.data||[]) as EventLog[]);setWebhooks((w.data||[]) as WebhookLog[])
  const t=await token();if(t){const r=await fetch('/api/admin/integrations/status',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setReadiness(j.status||[]);else setMsg(j.error||'Could not read server integration status.')}
  const err=s.error||l.error||w.error;if(err)setMsg(err.message);setLoading(false)
 }
 const readyFor=(key:string)=>readiness.find(x=>x.key===key)
 async function saveConnection(){if(!edit)return;setBusy(`save-${edit.integration_key}`);setMsg('');const ready=readyFor(edit.integration_key);if(edit.is_enabled&&ready&&!ready.configured){setBusy('');setMsg(`Cannot enable ${edit.display_name}: ${ready.missing.join(', ')} are missing from the server environment.`);return}const {error}=await supabase.from('integration_settings').update({is_enabled:edit.is_enabled,environment:edit.environment,public_config:edit.public_config,updated_at:new Date().toISOString()}).eq('integration_key',edit.integration_key);setBusy('');setMsg(error?error.message:`${edit.display_name} settings saved.`);if(!error){setEdit(null);await load()}}
 async function testConnection(key:string){setBusy(`test-${key}`);setMsg('');const t=await token();const r=await fetch('/api/admin/integrations/test',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({key})});const j=await r.json().catch(()=>({}));setBusy('');setMsg(j.message||j.error||(r.ok?'Connection test passed.':'Connection test failed.'));await load()}
 async function toggleEnabled(item:Integration){const ready=readyFor(item.integration_key);if(!item.is_enabled&&ready&&!ready.configured){setMsg(`Add the missing server secrets before enabling ${item.display_name}: ${ready.missing.join(', ')}`);return}setBusy(`toggle-${item.integration_key}`);const {error}=await supabase.from('integration_settings').update({is_enabled:!item.is_enabled,updated_at:new Date().toISOString()}).eq('integration_key',item.integration_key);setBusy('');setMsg(error?error.message:`${item.display_name} ${item.is_enabled?'disabled':'enabled'}.`);if(!error)await load()}
 function configField(item:Integration,key:string,value:any){setEdit({...item,public_config:{...(item.public_config||{}),[key]:value}})}
 const kpis=useMemo(()=>({ready:readiness.filter(x=>x.configured).length,enabled:items.filter(x=>x.is_enabled).length,failed:items.filter(x=>x.last_test_status==='failed').length,events:logs.length}),[readiness,items,logs])
 if(loading)return <div className="intLoading">Loading secure integrations…</div>
 return <div className="intPage">
  <div className="intHead"><div><span className="intEyebrow"><ShieldCheck size={15}/> CONTROL CENTER · STEP 20</span><h1>Integrations & Communication Center</h1><p>Server-side provider connections, credential readiness, signed webhooks and operational event logs.</p></div><button className="intBtn ghost" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
  {msg&&<div className={`intMsg ${/saved|enabled|disabled|connected|passed|present|verified/i.test(msg)?'ok':''}`}><span>{/saved|enabled|disabled|connected|passed|present|verified/i.test(msg)?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}</span>{msg}</div>}
  <div className="intKpis"><article><span><Server/></span><small>Credentials Ready</small><b>{kpis.ready}/{items.length}</b><em>Server-only environment checks</em></article><article><span><CheckCircle2/></span><small>Enabled Connections</small><b>{kpis.enabled}</b><em>Explicitly active integrations</em></article><article><span><AlertTriangle/></span><small>Failed Tests</small><b>{kpis.failed}</b><em>Requires attention</em></article><article><span><Activity/></span><small>Recent Events</small><b>{kpis.events}</b><em>Latest 100 integration events</em></article></div>
  <div className="intTabs">{([['connections','Connections',Settings],['events','Event Log',Activity],['webhooks','Webhooks',Link2],['setup','Secure Setup',KeyRound]] as const).map(([k,label,I])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={16}/>{label}</button>)}</div>

  {tab==='connections'&&<div className="intConnections">{items.map(item=>{const I=iconMap[item.integration_key]||Settings,ready=readyFor(item.integration_key);return <article className={`intCard ${item.is_enabled?'enabled':''}`} key={item.integration_key}><div className="intCardTop"><span className="intIcon"><I size={22}/></span><div><h3>{item.display_name}</h3><p>{providerLabel[item.provider]||item.provider}</p></div><span className={`intState ${item.is_enabled?'on':'off'}`}>{item.is_enabled?'Enabled':'Disabled'}</span></div><p className="intDesc">{item.description}</p><div className="intReadiness"><div><span>Credential readiness</span><b>{ready?`${ready.configured_count}/${ready.total_required}`:'—'}</b></div><div className="intProgress"><i style={{width:ready?`${Math.round(ready.configured_count/Math.max(ready.total_required,1)*100)}%`:'0%'}}/></div>{ready&&!ready.configured&&<small>Missing: {ready.missing.join(', ')}</small>}{ready?.configured&&<small className="good">All required server secrets are present.</small>}</div><div className="intTest"><span className={`testDot ${item.last_test_status}`}/><div><b>{item.last_test_status==='never'?'Not tested':item.last_test_status.replace('_',' ')}</b><small>{item.last_test_message||`Last test: ${fmt(item.last_tested_at)}`}</small></div></div><div className="intCardActions"><button className="intBtn ghost" disabled={busy===`test-${item.integration_key}`} onClick={()=>testConnection(item.integration_key)}>{busy===`test-${item.integration_key}`?'Testing…':'Test Connection'}</button><button className="intBtn ghost" onClick={()=>setEdit({...item,public_config:{...(item.public_config||{})}})}>Configure</button><button className={`intBtn ${item.is_enabled?'danger':'primary'}`} disabled={busy===`toggle-${item.integration_key}`} onClick={()=>toggleEnabled(item)}>{item.is_enabled?'Disable':'Enable'}</button></div></article>})}</div>}

  {tab==='events'&&<section className="intPanel"><div className="intPanelHead"><div><h2>Integration Event Log</h2><p>Connection tests and provider activity without storing secret credentials.</p></div></div>{logs.length?<div className="intTableWrap"><table><thead><tr><th>Time</th><th>Integration</th><th>Direction</th><th>Event</th><th>Status</th><th>External Ref</th><th>Result</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{fmt(x.created_at)}</td><td><b>{x.integration_key}</b></td><td>{x.direction}</td><td>{x.event_type}</td><td><span className={`logStatus ${x.status}`}>{x.status}</span></td><td>{x.external_id||x.reference_type||'—'}</td><td className={x.error_message?'badText':''}>{x.error_message||'OK'}</td></tr>)}</tbody></table></div>:<div className="intEmpty"><Activity/><b>No integration events yet</b><p>Tests and signed webhook events will appear here.</p></div>}</section>}

  {tab==='webhooks'&&<section className="intPanel"><div className="intPanelHead"><div><h2>Signed Webhook Events</h2><p>Inbound events are accepted only through server-side signature verification.</p></div></div>{webhooks.length?<div className="intTableWrap"><table><thead><tr><th>Received</th><th>Integration</th><th>Event</th><th>Signature</th><th>Status</th><th>Provider ID</th><th>Payload Hash</th></tr></thead><tbody>{webhooks.map(x=><tr key={x.id}><td>{fmt(x.received_at)}</td><td><b>{x.integration_key}</b></td><td>{x.event_type||'—'}</td><td><span className={`signature ${x.signature_valid?'valid':'invalid'}`}>{x.signature_valid?'Valid':'Invalid'}</span></td><td>{x.processing_status}</td><td>{x.provider_event_id||'—'}</td><td><code>{x.payload_hash.slice(0,12)}…</code></td></tr>)}</tbody></table></div>:<div className="intEmpty"><Link2/><b>No webhook events yet</b><p>Webhook payload bodies are not displayed here; only safe metadata and hashes are retained.</p></div>}</section>}

  {tab==='setup'&&<section className="intPanel"><div className="intPanelHead"><div><h2>Secure Server Setup</h2><p>Secret values belong in Vercel/Hostinger server environment variables — never in Supabase public config or browser code.</p></div></div><div className="intSecurity"><ShieldCheck/><div><b>Secrets are intentionally not editable on this page.</b><p>This dashboard can only report whether required environment variables exist. It never returns their values to the browser.</p></div></div><div className="intSetupGrid">{items.map(item=>{const ready=readyFor(item.integration_key),I=iconMap[item.integration_key]||Settings;return <article key={item.integration_key}><div className="setupTitle"><I size={19}/><div><b>{item.display_name}</b><small>{providerLabel[item.provider]||item.provider}</small></div><span className={ready?.configured?'ready':'pending'}>{ready?.configured?'Ready':'Pending'}</span></div><div className="envList">{(ready?.required||item.required_env_keys||[]).map(k=><code key={k}>{k}<i>{ready?.missing.includes(k)?'Missing':'Present'}</i></code>)}</div></article>})}</div><div className="intWebhookUrls"><h3>Webhook endpoints</h3><p>Configure these URLs only after the matching server signing secret is present.</p><code>{typeof window!=='undefined'?window.location.origin:''}/api/webhooks/whatsapp</code><code>{typeof window!=='undefined'?window.location.origin:''}/api/webhooks/razorpay</code><code>{typeof window!=='undefined'?window.location.origin:''}/api/webhooks/custom</code></div></section>}

  {edit&&<div className="intModalBack" onMouseDown={()=>setEdit(null)}><div className="intModal" onMouseDown={e=>e.stopPropagation()}><div className="intModalHead"><div><h2>Configure {edit.display_name}</h2><p>Only non-secret operational settings are stored here.</p></div><button onClick={()=>setEdit(null)}>×</button></div><div className="intForm"><label>Environment<select value={edit.environment} onChange={e=>setEdit({...edit,environment:e.target.value as any})}><option value="sandbox">Sandbox / Test</option><option value="live">Live</option></select></label>{edit.integration_key==='whatsapp'&&<label>Sender Label<input value={edit.public_config?.sender_name||''} onChange={e=>configField(edit,'sender_name',e.target.value)} placeholder="New India Solar"/></label>}{edit.integration_key==='email'&&<><label>From Name<input value={edit.public_config?.from_name||''} onChange={e=>configField(edit,'from_name',e.target.value)}/></label><label>From Email<input type="email" value={edit.public_config?.from_email||''} onChange={e=>configField(edit,'from_email',e.target.value)} placeholder="support@newindiasolar.com"/></label><label>Reply-to Email<input type="email" value={edit.public_config?.reply_to||''} onChange={e=>configField(edit,'reply_to',e.target.value)}/></label></>}{edit.integration_key==='sms'&&<label>Sender ID<input value={edit.public_config?.sender_id||''} onChange={e=>configField(edit,'sender_id',e.target.value.toUpperCase())} placeholder="NISOLAR"/></label>}{edit.integration_key==='payment'&&<label>Capture Mode<select value={edit.public_config?.capture_mode||'automatic'} onChange={e=>configField(edit,'capture_mode',e.target.value)}><option value="automatic">Automatic Capture</option><option value="manual">Manual Capture</option></select></label>}{edit.integration_key==='shipping'&&<label>Shiprocket Pickup Location<input value={edit.public_config?.pickup_location||''} onChange={e=>configField(edit,'pickup_location',e.target.value)} placeholder="Exact Shiprocket pickup nickname"/></label>}{edit.integration_key==='webhook'&&<label>Outbound Webhook URL<input type="url" value={edit.public_config?.outbound_url||''} onChange={e=>configField(edit,'outbound_url',e.target.value)} placeholder="https://..."/></label>}<label className="intSwitch"><input type="checkbox" checked={edit.is_enabled} onChange={e=>setEdit({...edit,is_enabled:e.target.checked})}/><span><b>Enable integration</b><small>Requires all mandatory server secrets before activation.</small></span></label></div><div className="intModalFoot"><button className="intBtn ghost" onClick={()=>setEdit(null)}>Cancel</button><button className="intBtn primary" onClick={saveConnection} disabled={busy===`save-${edit.integration_key}`}><Save size={16}/>{busy===`save-${edit.integration_key}`?'Saving…':'Save Connection'}</button></div></div></div>}
 </div>
}
