import type {Metadata} from 'next'
import Link from 'next/link'
import {notFound} from 'next/navigation'
import {ArrowRight,FileCheck2,ShieldCheck} from 'lucide-react'
import StoreHeader from '../../../components/StoreHeader'
import StoreFooter from '../../../components/StoreFooter'
import {COMPANY,COMPANY_ADDRESS} from '../../../lib/company'

type Section={title:string;body:string[]}
const policies:Record<string,{title:string;summary:string;updated:string;sections:Section[]}>= {
 privacy:{title:'Privacy Policy',summary:'How we collect, use and protect information when you browse, create an account, request a quotation or place an order.',updated:'17 September 2026',sections:[
  {title:'Information we collect',body:['We may collect contact, business, GST, delivery and billing details that you provide through your account, checkout and quotation forms. We also process order, product-selection and support information needed to serve your request.','Basic technical data such as browser type, device information and site activity may be processed for security, reliability and performance.']},
  {title:'How information is used',body:['We use information to authenticate buyers, prepare quotations, process and support orders, save requested account details, generate documents, prevent misuse and improve the buying experience.','We may use service providers for hosting, authentication, messaging, analytics, fulfilment and other operations. They receive information only as needed to provide those services.']},
  {title:'Retention and your choices',body:['Records are retained for business, tax, security and legal purposes as applicable. You may request correction of profile information through your account or send a request through the Project RFQ/contact flow.','Do not submit confidential payment credentials, passwords or unnecessary personal data in free-text fields.']},
 ]},
 terms:{title:'Terms of Use & Sale',summary:'The conditions for using this website, requesting quotations and purchasing published products.',updated:'17 September 2026',sections:[
  {title:'Website information',body:['Published specifications, images and descriptions support product selection. Buyers must verify suitability, ratings and installation requirements before ordering or using a product. Product imagery may be representative where stated.','Prices, GST, stock and minimum quantities are rechecked during the ordering flow. A cart or enquiry does not reserve inventory.']},
  {title:'Orders and quotations',body:['An order is subject to successful validation, availability and acceptance. Project, bulk and custom requirements may require a separate quotation, approved BOM and production confirmation.','Custom-builder previews are requirement visualisations and are not electrical drawings, engineering approvals or confirmed prices.']},
  {title:'Safe installation',body:['Electrical and solar protection products must be selected and installed by appropriately qualified professionals in accordance with applicable standards, manufacturer instructions and site conditions.']},
 ]},
 shipping:{title:'Shipping & Delivery Policy',summary:'How dispatch, delivery details and project shipments are handled.',updated:'17 September 2026',sections:[
  {title:'Delivery coverage',body:['We support delivery requirements across India, subject to serviceability, product type, quantity and carrier availability. Enter a complete and accurate delivery address and GST details where required.']},
  {title:'Dispatch and delivery estimates',body:['Availability and dispatch timing depend on current stock, order verification and payment or commercial approval. Custom-built, bulk and project orders follow the lead time confirmed in their quotation or order communication.','Delivery estimates are indicative and may change because of carrier, weather, access, regulatory or other circumstances outside direct control.']},
  {title:'Receiving an order',body:['Inspect outer packaging and item count on arrival. Record visible damage or shortage with photographs and the carrier acknowledgement, then report it promptly through your account or the Project RFQ/contact flow with the order reference.']},
 ]},
 returns:{title:'Returns & Cancellation Policy',summary:'A clear process for reporting damaged, incorrect or potentially returnable products.',updated:'17 September 2026',sections:[
  {title:'Before requesting a return',body:['Open the relevant order in your account and retain the original packaging, invoice and product labels. Provide the order reference, affected quantity, reason and clear photographs where applicable.','Products must not be installed, energised, altered or damaged after delivery if a return assessment is requested.']},
  {title:'Eligibility review',body:['Eligibility depends on product condition, order terms, the nature of the issue and applicable law. Incorrect or transit-damaged items should be reported promptly so the case can be reviewed.','Custom-built, configured, made-to-order, cut-length and specially procured items may have different cancellation or return conditions disclosed before approval.']},
  {title:'Resolution',body:['After inspection and approval, the available resolution may include replacement, correction, credit or refund as applicable to the case and original commercial terms. Do not send items back without return instructions.']},
 ]},
 warranty:{title:'Warranty & Product Support',summary:'How to obtain support for a product issue and what information is needed for assessment.',updated:'17 September 2026',sections:[
  {title:'Coverage',body:['Warranty terms depend on the product, manufacturer and confirmed order or quotation. Product-specific documentation or the accepted commercial offer governs where provided.']},
  {title:'Support request',body:['Keep the invoice, product label and serial or batch details where available. Submit the order reference, installation date, site conditions, issue description and supporting photographs through your account or Project RFQ/contact flow.']},
  {title:'Assessment',body:['Support may require remote checks, return inspection or manufacturer review. Damage caused by incorrect selection, installation, wiring, ratings, misuse, modification, external events or normal wear may fall outside product warranty terms.']},
 ]},
}
export function generateStaticParams(){return Object.keys(policies).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params,p=policies[slug];return p?{title:`${p.title} | New India Solar`,description:p.summary,alternates:{canonical:`/policies/${slug}`}}:{title:'Policy | New India Solar'}}
export default async function PolicyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params,p=policies[slug];if(!p)notFound();return <><StoreHeader/><main id="main-content" className="policyPage"><section className="policyHero"><div className="container"><span><FileCheck2 size={17}/> BUYER INFORMATION</span><h1>{p.title}</h1><p>{p.summary}</p><small>Last updated: {p.updated}</small></div></section><div className="container policyLayout"><aside><b>POLICIES</b>{Object.entries(policies).map(([key,value])=><Link className={key===slug?'active':''} aria-current={key===slug?'page':undefined} href={`/policies/${key}`} key={key}>{value.title}<ArrowRight size={14}/></Link>)}</aside><article><div className="policyIdentity"><ShieldCheck/><div><b>{COMPANY.legalName}</b><span>GSTIN {COMPANY.gstin}</span><p>{COMPANY_ADDRESS}</p></div></div>{p.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.body.map(body=><p key={body}>{body}</p>)}</section>)}<section><h2>Questions about this policy</h2><p>Use the Project RFQ/contact form and include your order or quotation reference when applicable. This helps the team route your request to the correct record.</p><Link className="nisBtn nisBtnPrimary" href="/bulk-order">Contact the team <ArrowRight size={16}/></Link></section></article></div></main><StoreFooter/></>}
