'use client'

import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {Building2,CalendarDays,Check,ChevronRight,Download,IndianRupee,Mail,MapPin,MessageSquarePlus,Phone,Plus,RefreshCw,Save,Search,ShieldAlert,Tags,UserRound,Users,X} from 'lucide-react'
import {supabase} from '../../../lib/supabase'

const types=['Retail','Installer','Dealer','Distributor','EPC','Industrial','Corporate']
const statuses=['active','on_hold','blocked','inactive']
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`
const fmtDate=(v:any)=>v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
const fmtDateTime=(v:any)=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'
const statusLabel=(s:string)=>({active:'Active',on_hold:'On Hold',blocked:'Blocked',inactive:'Inactive'} as any)[s]||s

export default function Customers(){
 const [rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([])
 const [selected,setSelected]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[rfqs,setRfqs]=useState<any[]>([]),[addresses,setAddresses]=useState<any[]>([]),[notes,setNotes]=useState<any[]>([])
 const [q,setQ]=useState(''),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[owner,setOwner]=useState('all'),[tab,setTab]=useState('overview')
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[note,setNote]=useState(''),[isNew,setIsNew]=useState(false)
 const [addressDraft,setAddressDraft]=useState<any>(null)

 async function load(){
  setLoading(true)
  const [a,s,st]=await Promise.all([
   supabase.from('customer_accounts').select('*').order('created_at',{ascending:false}).limit(1000),
   supabase.rpc('get_customer_admin_summary'),
   supabase.from('profiles').select('id,full_name,company_name,role').in('role',['admin','staff']).order('full_name')
  ])
  setRows(a.data||[]);setSummary(s.data||[]);setStaff(st.data||[]);setLoading(false)
 }
 useEffect(()=>{load()},[])

 const smap=useMemo(()=>Object.fromEntries(summary.map((x:any)=>[x.customer_account_id,x])),[summary])
 const filtered=useMemo(()=>rows.filter(r=>{
  const text=`${r.full_name||''} ${r.company_name||''} ${r.email||''} ${r.phone||''} ${r.gstin||''} ${(r.tags||[]).join(' ')}`.toLowerCase()
  return text.includes(q.toLowerCase())&&(type==='all'||r.customer_type===type)&&(status==='all'||r.account_status===status)&&(owner==='all'||(owner==='unassigned'?!r.sales_owner:r.sales_owner===owner))
 }),[rows,q,type,status,owner])
 const totalOutstanding=summary.reduce((a:any,x:any)=>a+Number(x.outstanding_amount||0),0)
 const totalLtv=summary.reduce((a:any,x:any)=>a+Number(x.lifetime_value||0),0)
 const b2b=rows.filter(r=>r.customer_type!=='Retail').length
 const creditRisk=rows.filter(r=>Number(r.credit_limit||0)>0&&Number(smap[r.id]?.outstanding_amount||0)>Number(r.credit_limit||0)).length

 async function openCustomer(r:any){
  setSelected({...r,tags:Array.isArray(r.tags)?r.tags:[]});setIsNew(false);setTab('overview');setNote('');setAddressDraft(null);setMsg('')
  const [o,f,a,n]=await Promise.all([
   supabase.from('orders').select('id,order_number,status,payment_status,grand_total,order_source,created_at,shipping_address').eq('customer_account_id',r.id).order('created_at',{ascending:false}).limit(100),
   supabase.from('bulk_rfqs').select('id,status,product_interest,project_name,quoted_amount,estimated_value,next_follow_up_at,created_at').eq('customer_account_id',r.id).order('created_at',{ascending:false}).limit(100),
   supabase.from('customer_addresses').select('*').eq('customer_account_id',r.id).order('is_default_shipping',{ascending:false}).order('created_at'),
   supabase.from('customer_notes').select('*,profiles:created_by(full_name)').eq('customer_account_id',r.id).order('created_at',{ascending:false}).limit(100)
  ])
  setOrders(o.data||[]);setRfqs(f.data||[]);setAddresses(a.data||[]);setNotes(n.data||[])
 }
 function newCustomer(){setIsNew(true);setSelected({full_name:'',email:'',phone:'',company_name:'',gstin:'',customer_type:'Retail',tags:[],account_status:'active',sales_owner:null,credit_limit:0,credit_days:0,payment_terms:'prepaid',internal_notes:'',last_contacted_at:null});setOrders([]);setRfqs([]);setAddresses([]);setNotes([]);setTab('overview');setMsg('')}
 async function save(){
  if(!selected)return;setSaving(true);setMsg('')
  const payload={full_name:selected.full_name||null,email:selected.email||null,phone:selected.phone||null,company_name:selected.company_name||null,gstin:selected.gstin||null,customer_type:selected.customer_type||'Retail',tags:Array.isArray(selected.tags)?selected.tags:[],account_status:selected.account_status||'active',sales_owner:selected.sales_owner||null,credit_limit:Number(selected.credit_limit||0),credit_days:Number(selected.credit_days||0),payment_terms:selected.payment_terms||'prepaid',internal_notes:selected.internal_notes||null,last_contacted_at:selected.last_contacted_at||null}
  let id=selected.id
  if(isNew){const {data,error}=await supabase.from('customer_accounts').insert(payload).select('*').single();if(error){setSaving(false);setMsg(error.message);return}id=data.id;setIsNew(false);setSelected(data)}
  else {const {error}=await supabase.from('customer_accounts').update(payload).eq('id',selected.id);if(error){setSaving(false);setMsg(error.message);return}
   if(selected.profile_id) await supabase.from('profiles').update({full_name:payload.full_name,email:payload.email,phone:payload.phone,company_name:payload.company_name,gstin:payload.gstin,customer_type:payload.customer_type,customer_tags:payload.tags,account_status:payload.account_status,sales_owner:payload.sales_owner,credit_limit:payload.credit_limit,credit_days:payload.credit_days,payment_terms:payload.payment_terms,internal_notes:payload.internal_notes,last_contacted_at:payload.last_contacted_at}).eq('id',selected.profile_id)
  }
  setSaving(false);setMsg('Customer saved.');await load();if(id){const {data}=await supabase.from('customer_accounts').select('*').eq('id',id).single();if(data)await openCustomer(data)}
 }
 async function addNote(){if(!selected?.id||!note.trim())return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('customer_notes').insert({customer_account_id:selected.id,note:note.trim(),created_by:user?.id||null});if(error){setMsg(error.message);return}setNote('');const {data}=await supabase.from('customer_notes').select('*,profiles:created_by(full_name)').eq('customer_account_id',selected.id).order('created_at',{ascending:false}).limit(100);setNotes(data||[])}
 async function markContacted(){if(!selected?.id)return;const now=new Date().toISOString();setSelected((x:any)=>({...x,last_contacted_at:now}));await supabase.from('customer_accounts').update({last_contacted_at:now}).eq('id',selected.id);if(selected.profile_id)await supabase.from('profiles').update({last_contacted_at:now}).eq('id',selected.profile_id);setMsg('Last contact updated.')}
 async function addAddress(){if(!selected?.id||!addressDraft?.address_line1)return;const payload={customer_account_id:selected.id,label:addressDraft.label||'Office',contact_name:addressDraft.contact_name||selected.full_name||null,phone:addressDraft.phone||selected.phone||null,address_line1:addressDraft.address_line1,address_line2:addressDraft.address_line2||null,city:addressDraft.city||null,state:addressDraft.state||null,postal_code:addressDraft.postal_code||null,country:'India',is_default_shipping:!!addressDraft.is_default_shipping,is_default_billing:!!addressDraft.is_default_billing};const {error}=await supabase.from('customer_addresses').insert(payload);if(error){setMsg(error.message);return}setAddressDraft(null);const {data}=await supabase.from('customer_addresses').select('*').eq('customer_account_id',selected.id).order('created_at');setAddresses(data||[])}
 function exportCsv(){const head=['Name','Company','Type','Phone','Email','GSTIN','Status','Paid Sales','Outstanding','Orders','Open RFQs','Owner','Credit Limit','Terms','Tags'];const body=filtered.map(r=>{const s=smap[r.id]||{};return [r.full_name,r.company_name,r.customer_type,r.phone,r.email,r.gstin,r.account_status,s.lifetime_value,s.outstanding_amount,s.order_count,s.open_rfq_count,staff.find(x=>x.id===r.sales_owner)?.full_name||'',r.credit_limit,r.payment_terms,(r.tags||[]).join('|')]});const csv=[head,...body].map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='new-india-solar-customers.csv';a.click()}

 const s=selected?.id?smap[selected.id]||{}:{}
 const activity=useMemo(()=>[
  ...notes.map(n=>({kind:'note',date:n.created_at,title:n.note,meta:`Note by ${n.profiles?.full_name||'staff'}`})),
  ...orders.map(o=>({kind:'order',date:o.created_at,title:`Order ${o.order_number}`,meta:`${o.status} • ${money(o.grand_total)}`,href:`/admin/orders/${o.id}`})),
  ...rfqs.map(r=>({kind:'rfq',date:r.created_at,title:r.project_name||r.product_interest||'RFQ',meta:`${r.status} • ${money(r.quoted_amount||r.estimated_value||0)}`}))
 ].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()),[notes,orders,rfqs])

 return <div className="customersV2">
  <div className="customerHero"><div><span className="adminEyebrow">CUSTOMER 360 / B2B CRM</span><h1>Customers</h1><p>One operational view of EPCs, dealers, installers, distributors and retail buyers across sales, RFQs, credit and service history.</p></div><div className="customerHeroActions"><button className="adminBtn ghost" onClick={load}><RefreshCw size={16}/>Refresh</button><button className="adminBtn ghost" onClick={exportCsv}><Download size={16}/>Export</button><button className="adminBtn" onClick={newCustomer}><Plus size={16}/>Add Customer</button></div></div>
  <div className="customerStats"><div><Users size={19}/><span>Total Customers</span><b>{rows.length}</b><small>{b2b} B2B accounts</small></div><div><IndianRupee size={19}/><span>Paid Lifetime Sales</span><b>{money(totalLtv)}</b><small>Across linked customer orders</small></div><div><CalendarDays size={19}/><span>Outstanding</span><b>{money(totalOutstanding)}</b><small>Unpaid linked order value</small></div><div><ShieldAlert size={19}/><span>Credit Risk</span><b>{creditRisk}</b><small>Above approved credit limit</small></div></div>
  <section className="customerToolbar"><div className="customerSearch"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, company, phone, email, GSTIN or tag…"/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All customer types</option>{types.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All owners</option><option value="unassigned">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.company_name||'Staff'}</option>)}</select></section>
  <section className="adminPanel customerTablePanel"><div className="adminTableWrap"><table className="adminTable customerTable"><thead><tr><th>Customer</th><th>Segment</th><th>Sales</th><th>Outstanding</th><th>Orders / RFQs</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="emptyCell">Loading customers…</td></tr>:filtered.length?filtered.map(r=>{const x=smap[r.id]||{};return <tr key={r.id}><td><button className="customerNameCell" onClick={()=>openCustomer(r)}><b>{r.company_name||r.full_name||'Unnamed customer'}</b><span>{r.full_name||'—'} • {r.phone||r.email||'No contact'}</span>{r.gstin&&<small>{r.gstin}</small>}</button></td><td><span className="customerTypePill">{r.customer_type||'Retail'}</span>{(r.tags||[]).slice(0,2).map((t:string)=><small className="customerTag" key={t}>{t}</small>)}</td><td><b>{money(x.lifetime_value)}</b><span className="tableSub">Paid lifetime</span></td><td><b className={Number(x.outstanding_amount||0)>Number(r.credit_limit||0)&&Number(r.credit_limit||0)>0?'creditDanger':''}>{money(x.outstanding_amount)}</b><span className="tableSub">Limit {money(r.credit_limit)}</span></td><td><b>{x.order_count||0} orders</b><span className="tableSub">{x.open_rfq_count||0} open RFQ</span></td><td>{staff.find(a=>a.id===r.sales_owner)?.full_name||<span className="muted">Unassigned</span>}</td><td><span className={`customerStatus ${r.account_status}`}>{statusLabel(r.account_status)}</span></td><td><button className="iconBtn" onClick={()=>openCustomer(r)}><ChevronRight size={17}/></button></td></tr>}):<tr><td colSpan={8} className="emptyCell">No customers match these filters.</td></tr>}</tbody></table></div></section>

  {selected&&<div className="adminDrawerBackdrop" onClick={()=>setSelected(null)}><aside className="customerDrawer" onClick={e=>e.stopPropagation()}>
   <div className="customerDrawerHead"><div><span className="adminEyebrow">{isNew?'NEW CRM ACCOUNT':'CUSTOMER 360'}</span><h2>{selected.company_name||selected.full_name||'New Customer'}</h2><p>{selected.customer_type||'Retail'} {selected.gstin?`• ${selected.gstin}`:''}</p></div><button className="iconBtn" onClick={()=>setSelected(null)}><X size={19}/></button></div>
   {msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}
   {!isNew&&<div className="customerDrawerKpis"><div><span>Paid sales</span><b>{money(s.lifetime_value)}</b></div><div><span>Outstanding</span><b>{money(s.outstanding_amount)}</b></div><div><span>Orders</span><b>{s.order_count||0}</b></div><div><span>Open RFQs</span><b>{s.open_rfq_count||0}</b></div></div>}
   <div className="customerDrawerActions"><button className="adminBtn" onClick={save} disabled={saving}><Save size={16}/>{saving?'Saving…':'Save Customer'}</button>{!isNew&&<button className="adminBtn ghost" onClick={markContacted}><CalendarDays size={16}/>Mark Contacted</button>}{selected.phone&&<a className="adminBtn ghost" href={`tel:${selected.phone}`}><Phone size={16}/>Call</a>}{selected.email&&<a className="adminBtn ghost" href={`mailto:${selected.email}`}><Mail size={16}/>Email</a>}</div>
   {!isNew&&<div className="customerTabs">{['overview','orders','rfqs','addresses','activity'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='rfqs'?'RFQs':x[0].toUpperCase()+x.slice(1)}</button>)}</div>}

   {(isNew||tab==='overview')&&<div className="customerSections">
    <section><h3><UserRound size={16}/>Account Profile</h3><div className="customerFormGrid"><label><span>Contact Name</span><input value={selected.full_name||''} onChange={e=>setSelected((x:any)=>({...x,full_name:e.target.value}))}/></label><label><span>Company</span><input value={selected.company_name||''} onChange={e=>setSelected((x:any)=>({...x,company_name:e.target.value}))}/></label><label><span>Phone</span><input value={selected.phone||''} onChange={e=>setSelected((x:any)=>({...x,phone:e.target.value}))}/></label><label><span>Email</span><input type="email" value={selected.email||''} onChange={e=>setSelected((x:any)=>({...x,email:e.target.value}))}/></label><label><span>GSTIN</span><input value={selected.gstin||''} onChange={e=>setSelected((x:any)=>({...x,gstin:e.target.value.toUpperCase()}))}/></label><label><span>Customer Type</span><select value={selected.customer_type||'Retail'} onChange={e=>setSelected((x:any)=>({...x,customer_type:e.target.value}))}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Account Status</span><select value={selected.account_status||'active'} onChange={e=>setSelected((x:any)=>({...x,account_status:e.target.value}))}>{statuses.map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label><label><span>Sales Owner</span><select value={selected.sales_owner||''} onChange={e=>setSelected((x:any)=>({...x,sales_owner:e.target.value||null}))}><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.company_name||'Staff'}</option>)}</select></label></div></section>
    <section><h3><IndianRupee size={16}/>Commercial Terms</h3><div className="customerFormGrid"><label><span>Credit Limit</span><input type="number" min="0" value={selected.credit_limit||0} onChange={e=>setSelected((x:any)=>({...x,credit_limit:e.target.value}))}/></label><label><span>Credit Days</span><input type="number" min="0" value={selected.credit_days||0} onChange={e=>setSelected((x:any)=>({...x,credit_days:e.target.value}))}/></label><label><span>Payment Terms</span><select value={selected.payment_terms||'prepaid'} onChange={e=>setSelected((x:any)=>({...x,payment_terms:e.target.value}))}><option value="prepaid">Prepaid</option><option value="cod">COD</option><option value="advance_balance">Advance + Balance</option><option value="7_days">7 Days</option><option value="15_days">15 Days</option><option value="30_days">30 Days</option><option value="45_days">45 Days</option></select></label><label><span>Last Contacted</span><input type="datetime-local" value={selected.last_contacted_at?new Date(selected.last_contacted_at).toISOString().slice(0,16):''} onChange={e=>setSelected((x:any)=>({...x,last_contacted_at:e.target.value?new Date(e.target.value).toISOString():null}))}/></label></div>{!isNew&&Number(selected.credit_limit||0)>0&&<div className="creditMeter"><div><span>Credit utilisation</span><b>{Math.min(999,Math.round(Number(s.outstanding_amount||0)/Number(selected.credit_limit||1)*100))}%</b></div><progress max={Number(selected.credit_limit||1)} value={Number(s.outstanding_amount||0)}/><small>{money(s.outstanding_amount)} outstanding of {money(selected.credit_limit)} approved limit</small></div>}</section>
    <section><h3><Tags size={16}/>Tags & Internal Notes</h3><label className="customerFullField"><span>Tags — comma separated</span><input value={(selected.tags||[]).join(', ')} onChange={e=>setSelected((x:any)=>({...x,tags:e.target.value.split(',').map((v:string)=>v.trim()).filter(Boolean)}))} placeholder="High Value, Repeat Buyer, Project Buyer"/></label><label className="customerFullField"><span>Internal Account Notes</span><textarea rows={4} value={selected.internal_notes||''} onChange={e=>setSelected((x:any)=>({...x,internal_notes:e.target.value}))} placeholder="Commercial preferences, approval notes, service context…"/></label></section>
   </div>}

   {!isNew&&tab==='orders'&&<section className="customerTabPanel"><h3>Order History</h3>{orders.length?orders.map(o=><Link href={`/admin/orders/${o.id}`} className="customerHistoryRow" key={o.id}><div><b>{o.order_number}</b><span>{fmtDate(o.created_at)} • {o.order_source}</span></div><div><b>{money(o.grand_total)}</b><span>{o.status} • {o.payment_status}</span></div></Link>):<div className="customerEmpty">No linked orders yet.</div>}</section>}
   {!isNew&&tab==='rfqs'&&<section className="customerTabPanel"><div className="customerSectionHead"><h3>RFQ History</h3><Link href="/admin/rfqs" className="adminBtn ghost">Open Pipeline</Link></div>{rfqs.length?rfqs.map(r=><div className="customerHistoryRow" key={r.id}><div><b>{r.project_name||r.product_interest||'RFQ'}</b><span>{fmtDate(r.created_at)} • Follow-up {fmtDateTime(r.next_follow_up_at)}</span></div><div><b>{money(r.quoted_amount||r.estimated_value||0)}</b><span>{r.status}</span></div></div>):<div className="customerEmpty">No linked RFQs yet.</div>}</section>}
   {!isNew&&tab==='addresses'&&<section className="customerTabPanel"><div className="customerSectionHead"><h3>Addresses</h3><button className="adminBtn ghost" onClick={()=>setAddressDraft(addressDraft?null:{label:'Office',address_line1:'',city:'',state:'',postal_code:''})}><Plus size={15}/>Add Address</button></div>{addressDraft&&<div className="addressEditor"><input placeholder="Label" value={addressDraft.label||''} onChange={e=>setAddressDraft((x:any)=>({...x,label:e.target.value}))}/><input className="wide" placeholder="Address line 1" value={addressDraft.address_line1||''} onChange={e=>setAddressDraft((x:any)=>({...x,address_line1:e.target.value}))}/><input placeholder="City" value={addressDraft.city||''} onChange={e=>setAddressDraft((x:any)=>({...x,city:e.target.value}))}/><input placeholder="State" value={addressDraft.state||''} onChange={e=>setAddressDraft((x:any)=>({...x,state:e.target.value}))}/><input placeholder="PIN code" value={addressDraft.postal_code||''} onChange={e=>setAddressDraft((x:any)=>({...x,postal_code:e.target.value}))}/><label><input type="checkbox" checked={!!addressDraft.is_default_shipping} onChange={e=>setAddressDraft((x:any)=>({...x,is_default_shipping:e.target.checked}))}/> Default shipping</label><button className="adminBtn" onClick={addAddress}>Save Address</button></div>}{addresses.length?<div className="addressCards">{addresses.map(a=><div key={a.id}><MapPin size={17}/><b>{a.label||'Address'}</b><p>{[a.address_line1,a.address_line2,a.city,a.state,a.postal_code].filter(Boolean).join(', ')}</p><span>{a.is_default_shipping?'Default shipping ':''}{a.is_default_billing?'• Default billing':''}</span></div>)}</div>:<div className="customerEmpty">No saved CRM addresses yet.</div>}</section>}
   {!isNew&&tab==='activity'&&<section className="customerTabPanel"><div className="customerSectionHead"><h3>Activity & Notes</h3></div><div className="customerNoteComposer"><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add sales, service or account note…"/><button className="adminBtn" onClick={addNote}><MessageSquarePlus size={16}/>Add Note</button></div>{activity.length?<div className="customerTimeline">{activity.map((a:any,i)=><div className={`customerActivity ${a.kind}`} key={`${a.kind}-${a.date}-${i}`}><i></i><div>{a.href?<Link href={a.href}><b>{a.title}</b></Link>:<b>{a.title}</b>}<span>{a.meta}</span><small>{fmtDateTime(a.date)}</small></div></div>)}</div>:<div className="customerEmpty">No customer activity yet.</div>}</section>}
  </aside></div>}
 </div>
}
