-- New India Solar internal-account MFA enforcement.
-- Filename generated by Supabase CLI 2.117.0 in GitHub Actions.
-- Apply once with the named Supabase migration "complete_admin_mfa_flow".
-- No account is enrolled, unenrolled, or made MFA-required by this migration.
create schema if not exists nis_security;
revoke all on schema nis_security from public,anon,authenticated;
grant usage on schema nis_security to authenticated;

create or replace function nis_security.admin_mfa_satisfied()
returns boolean language sql stable security definer set search_path=''
as $$
  select case when p.role::text not in ('admin','staff') then true
    when p.mfa_required or exists(select 1 from auth.mfa_factors f where f.user_id=p.id and f.status::text='verified')
    then coalesce(auth.jwt()->>'aal','aal1')='aal2'
      and exists(select 1 from auth.mfa_factors f where f.user_id=p.id and f.status::text='verified')
    else true end
  from public.profiles p where p.id=auth.uid();
$$;

create or replace function nis_security.admin_session_ready()
returns boolean language sql stable security definer set search_path=''
as $$
  select coalesce((select case when p.role::text not in ('admin','staff') then true else
    p.staff_status='active' and not p.must_change_password
    and nis_security.admin_mfa_satisfied()
    and exists(select 1 from auth.sessions s where s.user_id=p.id and s.id=nullif(auth.jwt()->>'session_id','')::uuid)
    end from public.profiles p where p.id=auth.uid()),false);
$$;
revoke all on function nis_security.admin_mfa_satisfied(),nis_security.admin_session_ready() from public,anon,authenticated;
grant execute on function nis_security.admin_session_ready() to authenticated;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=''
as $$
  select nis_security.admin_session_ready() and exists(
    select 1 from public.profiles p where p.id=auth.uid() and p.role::text='admin' and p.staff_status='active');
$$;
create or replace function public.is_staff_or_admin()
returns boolean language sql stable security definer set search_path=''
as $$
  select nis_security.admin_session_ready() and exists(
    select 1 from public.profiles p where p.id=auth.uid() and p.role::text in ('admin','staff') and p.staff_status='active');
$$;
create or replace function public.has_admin_permission(p_module text,p_action text default 'view')
returns boolean language plpgsql stable security definer set search_path=''
as $$
declare v_role text; v_admin_role text; v_status text; v_override boolean; v_result boolean:=false;
begin
  if not nis_security.admin_session_ready() then return false; end if;
  select role::text,admin_role,staff_status into v_role,v_admin_role,v_status from public.profiles where id=auth.uid();
  if v_status is distinct from 'active' then return false; end if;
  if v_role='admin' then return true; end if;
  if v_role is distinct from 'staff' then return false; end if;
  select allowed into v_override from public.admin_user_permissions
  where user_id=auth.uid() and module_key=p_module and action_key=p_action
    and (expires_at is null or expires_at>now());
  if found then return v_override; end if;
  select case p_action when 'view' then can_view when 'create' then can_create
    when 'edit' then can_edit when 'delete' then can_delete when 'approve' then can_approve
    when 'export' then can_export else false end into v_result
  from public.admin_role_permissions where role_key=coalesce(v_admin_role,'general') and module_key=p_module;
  return coalesce(v_result,false);
end;
$$;

-- Restrictive policies also cover legacy permissive policies and direct reads.
-- The user's own profile remains readable to bootstrap password/MFA screens.
do $$
declare t record;
begin
  for t in select n.nspname,c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where c.relkind='r' and c.relrowsecurity and
      (n.nspname='public' or (n.nspname='storage' and c.relname='objects'))
  loop
    execute format('drop policy if exists nis_internal_session_gate on %I.%I',t.nspname,t.relname);
    if t.nspname='public' and t.relname='profiles' then
      execute 'create policy nis_internal_session_gate on public.profiles as restrictive for all to authenticated using (id=(select auth.uid()) or (select nis_security.admin_session_ready())) with check (id=(select auth.uid()) or (select nis_security.admin_session_ready()))';
    else
      execute format('create policy nis_internal_session_gate on %I.%I as restrictive for all to authenticated using ((select nis_security.admin_session_ready())) with check ((select nis_security.admin_session_ready()))',t.nspname,t.relname);
    end if;
  end loop;
end;
$$;

-- Keep only a private fingerprint while a required password change is pending.
-- The old password itself and its Auth hash never leave the Auth schema.
create table if not exists nis_security.password_change_baselines(
  user_id uuid primary key references auth.users(id) on delete cascade,
  fingerprint bytea not null
);
alter table nis_security.password_change_baselines enable row level security;
revoke all on nis_security.password_change_baselines from public,anon,authenticated;

insert into nis_security.password_change_baselines(user_id,fingerprint)
select p.id,sha256(convert_to(coalesce(u.encrypted_password,''),'UTF8'))
from public.profiles p join auth.users u on u.id=p.id where p.must_change_password
on conflict(user_id) do nothing;

create or replace function public.protect_profile_access_fields()
returns trigger language plpgsql security definer set search_path=''
as $$
declare privileged boolean; changed_password boolean:=false;
begin
  privileged:=coalesce(auth.jwt()->>'role','')='service_role' or public.is_admin();
  if tg_op='INSERT' then
    if not privileged then
      new.role='customer';new.admin_role=null;new.staff_status='active';new.job_title=null;
      new.mfa_required=false;new.must_change_password=false;new.password_changed_at=null;
    end if;
    return new;
  end if;
  if not privileged and (
    new.role is distinct from old.role or new.admin_role is distinct from old.admin_role or
    new.staff_status is distinct from old.staff_status or new.job_title is distinct from old.job_title or
    new.mfa_required is distinct from old.mfa_required
  ) then raise exception 'Only a verified administrator can change staff access fields'; end if;
  if not privileged and (
    new.must_change_password is distinct from old.must_change_password or
    new.password_changed_at is distinct from old.password_changed_at
  ) then
    select exists(select 1 from nis_security.password_change_baselines b join auth.users u on u.id=b.user_id
      where b.user_id=auth.uid() and b.fingerprint<>sha256(convert_to(coalesce(u.encrypted_password,''),'UTF8')))
      into changed_password;
    if not (new.id=auth.uid() and old.must_change_password and not new.must_change_password
      and changed_password and new.password_changed_at=now()
      and (not exists(select 1 from auth.mfa_factors where user_id=auth.uid() and status::text='verified') or coalesce(auth.jwt()->>'aal','aal1')='aal2'))
    then raise exception 'Complete a verified password change before clearing the requirement'; end if;
  end if;
  return new;
end;
$$;

create or replace function nis_security.track_password_requirement()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if new.must_change_password then
    if tg_op='INSERT' or not old.must_change_password or coalesce(auth.jwt()->>'role','')='service_role' or public.is_admin() then
      insert into nis_security.password_change_baselines(user_id,fingerprint)
      select id,sha256(convert_to(coalesce(encrypted_password,''),'UTF8')) from auth.users where id=new.id
      on conflict(user_id) do update set fingerprint=excluded.fingerprint;
    end if;
  else delete from nis_security.password_change_baselines where user_id=new.id;
  end if;
  return new;
end;
$$;
revoke all on function nis_security.track_password_requirement() from public,anon,authenticated;
drop trigger if exists nis_track_password_requirement on public.profiles;
create trigger nis_track_password_requirement after insert or update on public.profiles
for each row execute function nis_security.track_password_requirement();

create or replace function public.complete_initial_password_change()
returns void language plpgsql security definer set search_path=''
as $$
declare p public.profiles%rowtype;
begin
  select * into p from public.profiles where id=auth.uid();
  if p.id is null or p.role::text not in ('admin','staff') or p.staff_status<>'active' then raise exception 'Active internal account required'; end if;
  -- Mandatory enrollment may follow a first password change; existing factors
  -- must already be verified before the Auth password update can succeed.
  if exists(select 1 from auth.mfa_factors where user_id=p.id and status::text='verified')
    and coalesce(auth.jwt()->>'aal','aal1')<>'aal2' then raise exception 'Authenticator verification required'; end if;
  if not p.must_change_password then return; end if;
  if not exists(select 1 from nis_security.password_change_baselines b join auth.users u on u.id=b.user_id
    where b.user_id=p.id and b.fingerprint<>sha256(convert_to(coalesce(u.encrypted_password,''),'UTF8')))
    then raise exception 'Change your password before completing first login'; end if;
  update public.profiles set must_change_password=false,password_changed_at=now(),updated_at=now() where id=p.id;
end;
$$;

-- Legacy settings RPC checked the role directly and therefore bypassed MFA.
create or replace function public.save_pricing_settings(p_min_margin numeric,p_warning_margin numeric,p_dealer numeric,p_epc numeric,p_distributor numeric,p_project numeric,p_enforce boolean,p_allow_override boolean)
returns public.pricing_settings language plpgsql security definer set search_path=''
as $$
declare v_row public.pricing_settings;
begin
  if not public.is_admin() then raise exception 'Verified administrator access required'; end if;
  update public.pricing_settings set min_margin_percent=p_min_margin,warning_margin_percent=p_warning_margin,dealer_discount_percent=p_dealer,epc_discount_percent=p_epc,distributor_discount_percent=p_distributor,project_discount_percent=p_project,enforce_min_margin=p_enforce,allow_admin_override=p_allow_override,updated_by=auth.uid(),updated_at=now() where id='default' returning * into v_row;
  return v_row;
end;
$$;
revoke execute on function public.complete_initial_password_change() from public,anon;
grant execute on function public.complete_initial_password_change() to authenticated;

create or replace function public.get_my_admin_access()
returns jsonb language plpgsql stable security definer set search_path=''
as $$
declare p public.profiles%rowtype; perms jsonb;
begin
  select * into p from public.profiles where id=auth.uid();
  if not found or p.role::text not in ('admin','staff') or p.staff_status<>'active' then return null; end if;
  select coalesce(jsonb_object_agg(m.module_key,jsonb_build_object(
    'view',public.has_admin_permission(m.module_key,'view'),'create',public.has_admin_permission(m.module_key,'create'),
    'edit',public.has_admin_permission(m.module_key,'edit'),'delete',public.has_admin_permission(m.module_key,'delete'),
    'approve',public.has_admin_permission(m.module_key,'approve'),'export',public.has_admin_permission(m.module_key,'export')
  )),'{}'::jsonb) into perms from public.admin_modules m;
  return jsonb_build_object('user_id',p.id,'role',p.role::text,
    'admin_role',coalesce(p.admin_role,case when p.role::text='admin' then 'admin' else 'general' end),
    'staff_status',p.staff_status,'job_title',p.job_title,'permissions',perms,
    'must_change_password',p.must_change_password,'mfa_required',p.mfa_required,
    'aal',coalesce(auth.jwt()->>'aal','aal1'),'session_ready',nis_security.admin_session_ready());
end;
$$;
notify pgrst,'reload schema';
