'use client'

import Link from 'next/link'
import {FormEvent,useState} from 'react'
import {Building2, CheckCircle2, FileText, Loader2, PackageSearch} from 'lucide-react'
import {supabase} from '../../lib/supabase'
import StoreHeader from '../../components/StoreHeader'
import StoreFooter from '../../components/StoreFooter'

export default function Bulk(){
  const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const row={name:f.get('name'),company_name:f.get('company'),mobile:f.get('mobile'),gst_number:f.get('gst'),city:f.get('city'),state:f.get('state'),product_interest:f.get('product'),quantity:Number(f.get('qty'))||null,expected_purchase:f.get('when'),additional_requirement:f.get('note')};const {error}=await supabase.from('bulk_rfqs').insert(row);setBusy(false);if(error){setError(error.message);return}setDone(true)}
  return <><StoreHeader/><main className="container formPage bulkPage"><div className="bulkPageGrid"><section><div className="formIntro"><span className="eyebrow darkEye">EPC • DEALER • INSTALLER • PROJECT</span><h1>Request project or bulk pricing.</h1><p>Tell us what you need, how much you need and when you plan to buy. Your enquiry is stored directly in the New India Solar RFQ pipeline.</p></div>{done?<div className="successBox premiumSuccess"><CheckCircle2 size={34}/><h2>Requirement received.</h2><p>Your RFQ is now saved in the New India Solar admin pipeline for follow-up.</p><div className="btnRow"><Link className="btn btnPrimary" href="/">Back to Home</Link><Link className="btn" href="/shop">Browse Products</Link></div></div>:<form className="rfqForm" onSubmit={submit}><label>Name<input name="name" placeholder="Your full name" required/></label><label>Company<input name="company" placeholder="Company / firm name"/></label><label>Mobile<input name="mobile" inputMode="tel" placeholder="10-digit mobile number" required/></label><label>GST Number<input name="gst" placeholder="Optional GSTIN"/></label><label>City<input name="city" placeholder="Dispatch / project city"/></label><label>State<input name="state" defaultValue="Gujarat"/></label><label>Product / Requirement<select name="product"><option>ACDB</option><option>DCDB</option><option>MCB / MCCB</option><option>SPD</option><option>Solar Cable</option><option>Earthing Kit</option><option>MC4</option><option>Complete BOS Requirement</option></select></label><label>Quantity<input name="qty" type="number" min="1" placeholder="Total quantity"/></label><label>Expected Purchase<select name="when"><option>Immediately</option><option>Within 7 Days</option><option>Within 30 Days</option></select></label><label className="full">Additional Requirement<textarea name="note" rows={6} placeholder="Mention ratings, preferred brands, box type, BOM details, delivery location or any technical requirement…"/></label>{error&&<div className="formError full">{error}</div>}<button className="btn btnPrimary fullBtn" disabled={busy}>{busy?<><Loader2 className="spin" size={17}/> Submitting…</>:<>Submit Bulk Requirement</>}</button></form>}</section><aside className="bulkAssist"><span>WHAT TO SHARE</span><h3>Faster quotation with complete project details.</h3><div><i><FileText size={19}/></i><section><b>Product & rating</b><p>Example: 2-in-2-out DCDB, 1000V, 32A.</p></section></div><div><i><PackageSearch size={19}/></i><section><b>Quantity & timeline</b><p>Approximate quantity and expected purchase date.</p></section></div><div><i><Building2 size={19}/></i><section><b>Project location</b><p>City/state helps plan dispatch and commercial terms.</p></section></div><div className="bulkAssistNote">For larger BOMs, mention that you have a file ready. File-upload workflow can be enabled once storage rules are finalized.</div></aside></div></main><StoreFooter/></>
}
