'use client'

import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {ArrowRight,Building2,CalendarClock,Check,Download,ExternalLink,FileText,Filter,IndianRupee,KanbanSquare,MessageSquarePlus,Phone,RefreshCw,Save,Search,Table2,Upload,UserRound,Users,X} from 'lucide-react'
import {supabase} from '../../../lib/supabase'

const stages=['new','qualified','contacted','quote_preparing','quoted','negotiation','won','lost','closed']
const openStages=new Set(['new','qualified','contacted','quote_preparing','quoted','negotiation'])
const stageLabel=(s:string)=>({new:'New',qualified:'Qualified',contacted:'Contacted',quote_preparing:'Quote Preparing',quoted:'Quoted',negotiation:'Negotiation',won:'Won',lost:'Lost',closed:'Closed'} as any)[s]||s
const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`
const safeFile=(f:File)=>f.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-').replace(/-+/g,'-')
const dateTimeLocal=(v:any)=>v?new Date(v).toISOString().slice(0,16):''
const fmt=(v:any)=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'

export default function RFQs(){
 const [rows,setRows]=useState<any[]>([]),[staff,setStaff]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[activities,setActivities]=useState<any[]>([])
 const [q,setQ]=useState(''),[stage,setStage]=useState('all'),[owner,setOwner]=useState('all'),[priority,setPriority]=useState('all'),[view,setView]=useState<'table'|'board'>('table')
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[msg,setMsg]=useState(''),[note,setNote]=useState('')

 async function load(){
  setLoading(true)
  const [r,s]=await Promise.all([
   supabase.from('bulk_rfqs').select('*').order('created_at',{ascending:false}).limit(500),
   supabase.from('profiles').select('id,full_name,company_name,role').in('role',['admin','staff']).order('full_name')
  ])
  setRows(r.data||[]);setStaff(s.data||[]);setLoading(false)
 }
 useEffect(()=>{load()},[])

 const filtered=useMemo(()=>rows.filter(r=>{
  const text=`${r.name||''} ${r.company_name||''} ${r.phone||''} ${r.email||''} ${r.gstin||''} ${r.product_interest||''} ${r.project_name||''} ${r.city||''}`.toLowerCase()
  return text.includes(q.toLowerCase())&&(stage==='all'||r.status===stage)&&(owner==='all'||(owner==='unassigned'?!r.assigned_to:r.assigned_to===owner))&&(priority==='all'||r.priority===priority)
 }),[rows,q,stage,owner,priority])
 const open=rows.filter(r=>openStages.has(r.status))
 const followups=open.filter(r=>r.next_follow_up_at&&new Date(r.next_follow_up_at)<new Date())
 const pipeline=open.reduce((a,r)=>a+Number(r.quoted_amount||r.estimated_value||0),0)
 const won=rows.filter(r=>r.status==='won')

 async function openRfq(r:any){setSelected({...r});setNote('');const {data}=await supabase.from('rfq_activities').select('*').eq('rfq_id',r.id).order('created_at',{ascending:false}).limit(100);setActivities(data||[])}
 async function save(){if(!selected)return;setSaving(true);setMsg('');const payload={status:selected.status,priority:selected.priority||'normal',lead_source:selected.lead_source||'website',customer_type:selected.customer_type||null,project_name:selected.project_name||null,estimated_value:selected.estimated_value?Number(selected.estimated_value):null,assigned_to:selected.assigned_to||null,quoted_amount:selected.quoted_amount?Number(selected.quoted_amount):null,next_follow_up_at:selected.next_follow_up_at||null,last_contacted_at:selected.last_contacted_at||null,quote_number:selected.quote_number||null,quote_file_url:selected.quote_file_url||null,loss_reason:selected.loss_reason||null,internal_notes:selected.internal_notes||null};const {error}=await supabase.from('bulk_rfqs').update(payload).eq('id',selected.id);setSaving(false);if(error){setMsg(error.message);return}setMsg('RFQ updated.');await load();await openRfq({...selected,...payload})}
 async function quickStage(id:string,s:string){const {error}=await supabase.from('bulk_rfqs').update({status:s}).eq('id',id);if(error)setMsg(error.message);else await load()}
 async function addNote(){if(!selected||!note.trim())return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('rfq_activities').insert({rfq_id:selected.id,activity_type:'note',message:note.trim(),created_by:user?.id||null});if(error){setMsg(error.message);return}setNote('');await openRfq(selected)}
 async function uploadQuote(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file||!selected)return;setUploading(true);const path=`quotes/${selected.id}/${Date.now()}-${safeFile(file)}`;const up=await supabase.storage.from('rfq-assets').upload(path,file,{upsert:false});if(up.error){setUploading(false);setMsg(up.error.message);return}const {data}=supabase.storage.from('rfq-assets').getPublicUrl(path);setSelected((x:any)=>({...x,quote_file_url:data.publicUrl}));setUploading(false);setMsg('Quotation uploaded. Click Save RFQ to attach it.')}
 async function convertOrder(){if(!selected)return;if(!confirm('Create a manual pending order from this RFQ and mark the RFQ as Won?'))return;setSaving(true);const {data,error}=await supabase.rpc('convert_rfq_to_order',{p_rfq_id:selected.id});setSaving(false);if(error){setMsg(error.message);return}setMsg('RFQ converted to a manual order.');await load();await openRfq({...selected,status:'won',converted_order_id:data})}
 function exportCsv(){const head=['Company','Contact','Phone','Email','Product','Quantity','Stage','Owner','Priority','Estimated Value','Quoted Amount','Next Follow-up','Created'];const body=filtered.map(r=>[r.company_name||r.name,r.name,r.phone,r.email,r.product_interest,r.quantity_text,r.status,staff.find(s=>s.id===r.assigned_to)?.full_name||'',r.priority,r.estimated_value,r.quoted_amount,r.next_follow_up_at,r.created_at]);const csv=[head,...body].map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='new-india-solar-rfqs.csv';a.click()}

 return <div className="rfqV2">
  <div className="rfqHero"><div><span className="adminEyebrow">B2B SALES CONTROL</span><h1>RFQ & Sales Pipeline</h1><p>Qualify EPC, dealer and project enquiries, prepare quotations, schedule follow-ups and convert won opportunities to orders.</p></div><div className="rfqHeroActions"><button className="adminBtn ghost" onClick={load}><RefreshCw size={16}/>Refresh</button><button className="adminBtn ghost" onClick={exportCsv}><Download size={16}/>Export</button></div></div>
  {msg&&<div className="themeMessage"><Check size={16}/>{msg}</div>}
  <div className="rfqStats">
   <div><span>Open Pipeline</span><b>{open.length}</b><small>{money(pipeline)} potential value</small></div>
   <div><span>Follow-ups Due</span><b>{followups.length}</b><small>Needs sales attention</small></div>
   <div><span>Quotes Sent</span><b>{rows.filter(r=>['quoted','negotiation','won'].includes(r.status)).length}</b><small>{money(rows.reduce((a,r)=>a+Number(r.quoted_amount||0),0))} quoted</small></div>
   <div><span>Won RFQs</span><b>{won.length}</b><small>{money(won.reduce((a,r)=>a+Number(r.quoted_amount||r.estimated_value||0),0))} won value</small></div>
  </div>
  <section className="rfqToolbar">
   <div className="rfqSearch"><Search size={17}/><input placeholder="Search company, contact, phone, GSTIN, product…" value={q} onChange={e=>setQ(e.target.value)}/></div>
   <select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{stages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select>
   <select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All owners</option><option value="unassigned">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.full_name||s.company_name||'Staff'}</option>)}</select>
   <select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select>
   <div className="rfqViewToggle"><button className={view==='table'?'active':''} onClick={()=>setView('table')}><Table2 size={16}/></button><button className={view==='board'?'active':''} onClick={()=>setView('board')}><KanbanSquare size={16}/></button></div>
  </section>

  {view==='table'?<section className="adminPanel rfqTablePanel"><div className="adminTableWrap"><table className="adminTable rfqTable"><thead><tr><th>Opportunity</th><th>Requirement</th><th>Value</th><th>Owner</th><th>Follow-up</th><th>Stage</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="emptyCell">Loading RFQs…</td></tr>:filtered.length?filtered.map(r=>{const due=r.next_follow_up_at&&new Date(r.next_follow_up_at)<new Date()&&openStages.has(r.status);return <tr key={r.id}><td><button className="rfqOpportunity" onClick={()=>openRfq(r)}><b>{r.company_name||r.name||'Unnamed lead'}</b><span>{r.name||'—'} • {r.phone||'No phone'}</span><em className={`priorityTag ${r.priority||'normal'}`}>{r.priority||'normal'}</em></button></td><td><b>{r.product_interest||'General requirement'}</b><span className="tableSub">{r.quantity_text||'Qty not specified'} • {r.purchase_timeline||'Timeline open'}</span></td><td><b>{r.quoted_amount?money(r.quoted_amount):r.estimated_value?money(r.estimated_value):'—'}</b><span className="tableSub">{r.quoted_amount?'Quoted':'Estimated'}</span></td><td>{staff.find(s=>s.id===r.assigned_to)?.full_name||<span className="muted">Unassigned</span>}</td><td><span className={due?'followDue':''}>{fmt(r.next_follow_up_at)}</span></td><td><select className={`stageSelect stage-${r.status}`} value={r.status} onChange={e=>quickStage(r.id,e.target.value)}>{stages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select></td><td><button className="iconBtn" onClick={()=>openRfq(r)}><ArrowRight size={17}/></button></td></tr>}):<tr><td colSpan={7} className="emptyCell">No RFQs match these filters.</td></tr>}</tbody></table></div></section>:
  <div className="rfqBoard">{stages.filter(s=>s!=='closed').map(s=><section className="rfqColumn" key={s}><header><b>{stageLabel(s)}</b><span>{filtered.filter(r=>r.status===s).length}</span></header><div>{filtered.filter(r=>r.status===s).map(r=><button className="rfqCard" key={r.id} onClick={()=>openRfq(r)}><div><em className={`priorityTag ${r.priority||'normal'}`}>{r.priority||'normal'}</em><small>{r.company_name||r.name}</small></div><b>{r.product_interest||'General requirement'}</b><span>{r.quantity_text||'Qty open'} • {r.city||r.state||'Location open'}</span><strong>{r.quoted_amount?money(r.quoted_amount):r.estimated_value?money(r.estimated_value):'Value open'}</strong>{r.next_follow_up_at&&<i className={new Date(r.next_follow_up_at)<new Date()&&openStages.has(r.status)?'followDue':''}><CalendarClock size={13}/>{fmt(r.next_follow_up_at)}</i>}</button>)}</div></section>)}</div>}

  {selected&&<div className="adminDrawerBackdrop" onClick={()=>setSelected(null)}><aside className="rfqDrawer" onClick={e=>e.stopPropagation()}>
   <div className="rfqDrawerHead"><div><span className="adminEyebrow">SALES OPPORTUNITY</span><h2>{selected.company_name||selected.name}</h2><p>{selected.product_interest||'General requirement'} • {selected.quantity_text||'Quantity open'}</p></div><button className="iconBtn" onClick={()=>setSelected(null)}><X size={19}/></button></div>
   <div className="rfqDrawerActions"><button className="adminBtn" onClick={save} disabled={saving}><Save size={16}/>{saving?'Saving…':'Save RFQ'}</button>{selected.converted_order_id?<Link className="adminBtn ghost" href={`/admin/orders/${selected.converted_order_id}`}><ExternalLink size={16}/>Open Order</Link>:<button className="adminBtn ghost" onClick={convertOrder} disabled={saving}><ArrowRight size={16}/>Convert to Order</button>}</div>
   <div className="rfqDrawerGrid">
    <section className="rfqDrawerSection"><h3><Filter size={16}/>Pipeline</h3><div className="rfqFormGrid"><label><span>Stage</span><select value={selected.status||'new'} onChange={e=>setSelected((x:any)=>({...x,status:e.target.value}))}>{stages.map(s=><option key={s} value={s}>{stageLabel(s)}</option>)}</select></label><label><span>Priority</span><select value={selected.priority||'normal'} onChange={e=>setSelected((x:any)=>({...x,priority:e.target.value}))}><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></label><label><span>Sales Owner</span><select value={selected.assigned_to||''} onChange={e=>setSelected((x:any)=>({...x,assigned_to:e.target.value||null}))}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.full_name||s.company_name||'Staff'}</option>)}</select></label><label><span>Customer Type</span><select value={selected.customer_type||''} onChange={e=>setSelected((x:any)=>({...x,customer_type:e.target.value}))}><option value="">Not set</option><option>EPC</option><option>Dealer</option><option>Distributor</option><option>Installer</option><option>Industrial</option><option>Corporate</option><option>Retail</option></select></label><label><span>Lead Source</span><input value={selected.lead_source||''} onChange={e=>setSelected((x:any)=>({...x,lead_source:e.target.value}))}/></label><label><span>Next Follow-up</span><input type="datetime-local" value={dateTimeLocal(selected.next_follow_up_at)} onChange={e=>setSelected((x:any)=>({...x,next_follow_up_at:e.target.value?new Date(e.target.value).toISOString():null}))}/></label></div></section>
    <section className="rfqDrawerSection"><h3><Building2 size={16}/>Customer & Project</h3><div className="rfqContactCards"><div><UserRound size={17}/><b>{selected.name||'—'}</b><span>{selected.phone||'No phone'}</span><span>{selected.email||'No email'}</span></div><div><Building2 size={17}/><b>{selected.company_name||'No company'}</b><span>{selected.gstin||'No GSTIN'}</span><span>{[selected.city,selected.state].filter(Boolean).join(', ')||'Location not provided'}</span></div></div><label className="rfqWideLabel"><span>Project Name</span><input value={selected.project_name||''} onChange={e=>setSelected((x:any)=>({...x,project_name:e.target.value}))}/></label><label className="rfqWideLabel"><span>Requirement</span><textarea rows={4} value={selected.requirement||''} readOnly/></label>{selected.bom_file_url&&<a className="rfqFileLink" href={selected.bom_file_url} target="_blank"><FileText size={16}/>Open customer BOM / attachment<ExternalLink size={14}/></a>}</section>
    <section className="rfqDrawerSection"><h3><IndianRupee size={16}/>Commercial</h3><div className="rfqFormGrid"><label><span>Estimated Value</span><input type="number" value={selected.estimated_value||''} onChange={e=>setSelected((x:any)=>({...x,estimated_value:e.target.value}))}/></label><label><span>Quoted Amount</span><input type="number" value={selected.quoted_amount||''} onChange={e=>setSelected((x:any)=>({...x,quoted_amount:e.target.value}))}/></label><label><span>Quote Number</span><input value={selected.quote_number||''} onChange={e=>setSelected((x:any)=>({...x,quote_number:e.target.value}))}/></label><label><span>Purchase Timeline</span><input value={selected.purchase_timeline||''} readOnly/></label></div><div className="rfqQuoteUpload"><label className="adminBtn ghost"><Upload size={16}/>{uploading?'Uploading…':'Upload Quotation'}<input hidden type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,image/*" onChange={uploadQuote}/></label>{selected.quote_file_url&&<a href={selected.quote_file_url} target="_blank"><FileText size={16}/>View quotation</a>}</div>{selected.status==='lost'&&<label className="rfqWideLabel"><span>Loss Reason</span><textarea rows={3} value={selected.loss_reason||''} onChange={e=>setSelected((x:any)=>({...x,loss_reason:e.target.value}))}/></label>}</section>
    <section className="rfqDrawerSection"><h3><MessageSquarePlus size={16}/>Notes & Activity</h3><label className="rfqWideLabel"><span>Internal Sales Notes</span><textarea rows={4} value={selected.internal_notes||''} onChange={e=>setSelected((x:any)=>({...x,internal_notes:e.target.value}))}/></label><div className="rfqAddNote"><input placeholder="Add call note, negotiation update, next action…" value={note} onChange={e=>setNote(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addNote()}}}/><button onClick={addNote}>Add</button></div><div className="rfqTimeline">{activities.length?activities.map(a=><div key={a.id}><span></span><section><b>{String(a.activity_type||'activity').replaceAll('_',' ')}</b><p>{a.message}</p><small>{fmt(a.created_at)}</small></section></div>):<p className="muted">No activity recorded yet.</p>}</div></section>
   </div>
  </aside></div>}
 </div>
}
