'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,CheckCircle2,Clock3,GitBranch,History,IndianRupee,Play,Plus,RefreshCw,Search,ShieldCheck,XCircle} from 'lucide-react'
import {supabase} from '../../../lib/supabase'
import {AdminAccess,canAdmin} from '../../../lib/adminAccess'

type Rule={id:string;name:string;description:string|null;module_key:string;trigger_key:string;action_key:'notification'|'task'|'approval';threshold_amount:number|null;sla_minutes:number;target_role:string|null;condition_config:any;action_config:any;is_active:boolean;sort_order:number;updated_at:string}
type Approval={id:string;rule_id:string|null;module_key:string;source_type:string;source_id:string|null;title:string;description:string|null;amount:number|null;status:'pending'|'approved'|'rejected'|'cancelled'|'expired';approval_chain:string[];current_step:number;requested_by:string|null;assigned_to:string|null;due_at:string|null;href:string|null;metadata:any;decided_at:string|null;created_at:string;updated_at:string}
type Decision={id:string;approval_id:string;step_no:number;approver_id:string|null;decision:'approved'|'rejected';note:string|null;created_at:string}
type Run={id:string;rule_id:string|null;event_key:string;source_type:string;source_id:string|null;fingerprint:string;status:string;message:string|null;metadata:any;created_at:string}
type PriceItem={id:string;type:'variant'|'component'|'enclosure';label:string;sku:string;cost:number;selling:number;mrp:number|null;gst:number}

const roleOptions=['admin','sales','finance','production','inventory','general']
const modules=['dashboard','orders','rfqs','customers','products','components','inventory','purchasing','pricing','finance','configurator','production','content','notifications']
const triggerOptions=[
 ['purchase_order_saved','Purchase order saved / recalculated'],['purchase_order_overdue','Purchase order overdue'],['rfq_created','RFQ created'],['rfq_updated','RFQ updated'],['rfq_followup_due','RFQ follow-up overdue'],['invoice_changed','Invoice changed'],['invoice_overdue','Invoice overdue'],['production_job_changed','Production job changed'],['production_overdue','Production overdue'],['order_ready_to_ship','Order ready to dispatch'],['pricing_changed','Pricing changed'],['pricing_override_requested','Pricing override requested']
]
const actionOptions=[['notification','Create notification'],['task','Create staff task'],['approval','Request approval']]
const money=(n:any)=>n==null?'—':`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'
const overdue=(v?:string|null)=>Boolean(v&&new Date(v).getTime()<Date.now())

export default function WorkflowAutomationPage(){
 const [tab,setTab]=useState<'rules'|'approvals'|'runs'>('rules'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [access,setAccess]=useState<AdminAccess|null>(null),[rules,setRules]=useState<Rule[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[runs,setRuns]=useState<Run[]>([]),[priceItems,setPriceItems]=useState<PriceItem[]>([])
 const [search,setSearch]=useState(''),[ruleForm,setRuleForm]=useState({name:'',description:'',module_key:'dashboard',trigger_key:'rfq_followup_due',action_key:'task',threshold_amount:'',sla_minutes:'1440',target_role:'sales',approval_chain:'admin'}),[approvalForm,setApprovalForm]=useState({module_key:'finance',title:'',description:'',amount:'',chain:'finance,admin',due_at:'',href:''}),[priceForm,setPriceForm]=useState({item_type:'variant',item_id:'',cost:'',selling:'',mrp:'',gst:'18',reason:''}),[notes,setNotes]=useState<Record<string,string>>({})

 async function load(runSweep=true){
  setLoading(true);setMessage('')
  const {data:a}=await supabase.rpc('get_my_admin_access');const myAccess=(a||null) as AdminAccess|null;setAccess(myAccess)
  if(runSweep&&canAdmin(myAccess,'workflows','view'))await supabase.rpc('workflow_run_sla_sweep')
  const [rr,ar,dr,runr,vr,pr,cr,er]=await Promise.all([
   supabase.from('workflow_automation_rules').select('*').order('sort_order').order('created_at'),
   supabase.from('workflow_approval_requests').select('*').order('created_at',{ascending:false}).limit(250),
   supabase.from('workflow_approval_decisions').select('*').order('created_at',{ascending:false}).limit(500),
   supabase.from('workflow_automation_runs').select('*').order('created_at',{ascending:false}).limit(250),
   supabase.from('product_variants').select('id,product_id,sku,title,cost_price,selling_price,mrp,is_active'),
   supabase.from('products').select('id,name,gst_rate'),
   supabase.from('components').select('id,name,sku,cost_price,selling_price,gst_rate,is_active'),
   supabase.from('enclosures').select('id,name,sku,cost_price,selling_price,gst_rate,is_active')
  ])
  const err=rr.error||ar.error||dr.error||runr.error;if(err)setMessage(err.message)
  setRules((rr.data||[]) as Rule[]);setApprovals((ar.data||[]) as Approval[]);setDecisions((dr.data||[]) as Decision[]);setRuns((runr.data||[]) as Run[])
  const pmap=new Map((pr.data||[]).map((p:any)=>[p.id,p]));setPriceItems([
   ...(vr.data||[]).filter((x:any)=>x.is_active).map((v:any)=>{const p:any=pmap.get(v.product_id);return{id:v.id,type:'variant' as const,label:`${p?.name||'Product'} — ${v.title||v.sku||'Variant'}`,sku:v.sku||'',cost:Number(v.cost_price||0),selling:Number(v.selling_price||0),mrp:v.mrp==null?null:Number(v.mrp),gst:Number(p?.gst_rate||18)}}),
   ...(cr.data||[]).filter((x:any)=>x.is_active).map((c:any)=>({id:c.id,type:'component' as const,label:c.name||'Component',sku:c.sku||'',cost:Number(c.cost_price||0),selling:Number(c.selling_price||0),mrp:null,gst:Number(c.gst_rate||18)})),
   ...(er.data||[]).filter((x:any)=>x.is_active).map((e:any)=>({id:e.id,type:'enclosure' as const,label:e.name||'Enclosure',sku:e.sku||'',cost:Number(e.cost_price||0),selling:Number(e.selling_price||0),mrp:null,gst:Number(e.gst_rate||18)}))
  ]);setLoading(false)
 }
 useEffect(()=>{load(true)},[])

 const activeRules=rules.filter(r=>r.is_active).length,pending=approvals.filter(a=>a.status==='pending').length,overdueApprovals=approvals.filter(a=>a.status==='pending'&&overdue(a.due_at)).length,failedRuns=runs.filter(r=>r.status==='failed').length
 const filteredRules=useMemo(()=>{const q=search.toLowerCase();return rules.filter(r=>`${r.name} ${r.description||''} ${r.module_key} ${r.trigger_key} ${r.action_key}`.toLowerCase().includes(q))},[rules,search])
 const filteredApprovals=useMemo(()=>{const q=search.toLowerCase();return approvals.filter(a=>`${a.title} ${a.description||''} ${a.module_key} ${a.source_type} ${a.status}`.toLowerCase().includes(q))},[approvals,search])
 const filteredRuns=useMemo(()=>{const q=search.toLowerCase();return runs.filter(r=>`${r.event_key} ${r.source_type} ${r.status} ${r.message||''}`.toLowerCase().includes(q))},[runs,search])
 const selectedPriceItems=priceItems.filter(i=>i.type===priceForm.item_type)
 const pricingRuleActive=rules.some(r=>r.is_active&&r.trigger_key==='pricing_override_requested'&&r.action_key==='approval')

 async function updateRule(id:string,patch:Partial<Rule>){setBusy(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('workflow_automation_rules').update({...patch,updated_by:user?.id||null,updated_at:new Date().toISOString()}).eq('id',id);setBusy(false);if(error){setMessage(error.message);return}setMessage('Automation rule updated.');await load(false)}
 async function createRule(){if(!ruleForm.name.trim())return;setBusy(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();const chain=ruleForm.approval_chain.split(',').map(x=>x.trim()).filter(Boolean);const payload:any={name:ruleForm.name.trim(),description:ruleForm.description.trim()||null,module_key:ruleForm.module_key,trigger_key:ruleForm.trigger_key,action_key:ruleForm.action_key,threshold_amount:ruleForm.threshold_amount===''?null:Number(ruleForm.threshold_amount),sla_minutes:Number(ruleForm.sla_minutes||0),target_role:ruleForm.target_role||null,is_active:false,created_by:user?.id||null,updated_by:user?.id||null,action_config:{title:ruleForm.name.trim(),approval_chain:chain.length?chain:undefined}};const {error}=await supabase.from('workflow_automation_rules').insert(payload);setBusy(false);if(error){setMessage(error.message);return}setRuleForm({name:'',description:'',module_key:'dashboard',trigger_key:'rfq_followup_due',action_key:'task',threshold_amount:'',sla_minutes:'1440',target_role:'sales',approval_chain:'admin'});setMessage('Rule created in OFF state. Review it before activation.');await load(false)}
 async function runAutomations(){setBusy(true);setMessage('');const {data,error}=await supabase.rpc('workflow_run_sla_sweep');setBusy(false);if(error){setMessage(error.message);return}setMessage(`Automation sweep complete. ${Number(data||0)} rule execution(s) evaluated.`);await load(false)}
 async function createApproval(){if(!approvalForm.title.trim())return;setBusy(true);setMessage('');const chain=approvalForm.chain.split(',').map(x=>x.trim()).filter(Boolean);const {error}=await supabase.rpc('workflow_create_approval',{p_module_key:approvalForm.module_key,p_source_type:'manual',p_source_id:null,p_title:approvalForm.title.trim(),p_description:approvalForm.description.trim()||null,p_amount:approvalForm.amount===''?null:Number(approvalForm.amount),p_chain:chain.length?chain:['admin'],p_due_at:approvalForm.due_at?new Date(approvalForm.due_at).toISOString():null,p_href:approvalForm.href.trim()||'/admin/workflows',p_metadata:{manual:true},p_rule_id:null});setBusy(false);if(error){setMessage(error.message);return}setApprovalForm({module_key:'finance',title:'',description:'',amount:'',chain:'finance,admin',due_at:'',href:''});setMessage('Approval request created.');await load(false)}
 async function requestPricing(){if(!priceForm.item_id||!priceForm.reason.trim())return;setBusy(true);setMessage('');const {error}=await supabase.rpc('workflow_request_pricing_override',{p_item_type:priceForm.item_type,p_item_id:priceForm.item_id,p_cost:priceForm.cost===''?null:Number(priceForm.cost),p_selling:priceForm.selling===''?null:Number(priceForm.selling),p_mrp:priceForm.mrp===''?null:Number(priceForm.mrp),p_gst:priceForm.gst===''?null:Number(priceForm.gst),p_reason:priceForm.reason.trim()});setBusy(false);if(error){setMessage(error.message);return}setMessage('Pricing override submitted for approval. The price has not changed yet.');setPriceForm({item_type:'variant',item_id:'',cost:'',selling:'',mrp:'',gst:'18',reason:''});await load(false)}
 function selectPriceItem(id:string){const item=priceItems.find(i=>i.id===id&&i.type===priceForm.item_type);setPriceForm(v=>({...v,item_id:id,cost:item?String(item.cost):'',selling:item?String(item.selling):'',mrp:item?.mrp==null?'':String(item.mrp),gst:item?String(item.gst):'18'}))}
 async function decide(id:string,decision:'approved'|'rejected'){setBusy(true);setMessage('');const {data,error}=await supabase.rpc('workflow_decide_approval',{p_request_id:id,p_decision:decision,p_note:notes[id]?.trim()||null});setBusy(false);if(error){setMessage(error.message);return}setMessage(`Approval ${decision}. ${data?.next_step?`Moved to step ${data.next_step}.`:''}`);await load(false)}

 if(loading)return <div className="flowV2"><div className="flowLoading">Loading workflow engine…</div></div>
 return <div className="flowV2">
  <div className="flowHead"><div><span className="adminEyebrow">AUTOMATION & APPROVALS</span><h1>Workflow Automation</h1><p>Configure event → action rules, SLA escalation, task routing and multi-step approvals without hard-coding each operating process.</p></div><div><button className="flowGhost" onClick={()=>load(true)}><RefreshCw size={16}/>Refresh</button><button className="flowPrimary" onClick={runAutomations} disabled={busy}><Play size={16}/>Run Automations</button></div></div>
  {message&&<div className="flowMessage"><GitBranch size={16}/>{message}</div>}

  <div className="flowStats"><article><span><GitBranch/></span><div><small>Active Rules</small><strong>{activeRules}</strong><p>{rules.length} configured</p></div></article><article><span><ShieldCheck/></span><div><small>Pending Approvals</small><strong>{pending}</strong><p>Across all modules</p></div></article><article><span><Clock3/></span><div><small>Approval SLA Breaches</small><strong>{overdueApprovals}</strong><p>Past approval due time</p></div></article><article><span><History/></span><div><small>Failed Runs</small><strong>{failedRuns}</strong><p>{runs.length} recent executions</p></div></article></div>

  <div className="flowTabs"><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}><GitBranch size={16}/>Rules</button><button className={tab==='approvals'?'active':''} onClick={()=>setTab('approvals')}><ShieldCheck size={16}/>Approvals <em>{pending}</em></button><button className={tab==='runs'?'active':''} onClick={()=>setTab('runs')}><History size={16}/>Run History</button></div>
  <div className="flowSearch"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab}…`}/></div>

  {tab==='rules'&&<div className="flowRuleLayout">
   {canAdmin(access,'workflows','create')&&<section className="flowPanel flowBuilder"><div className="flowPanelHead"><div><h2>Create Automation</h2><p>New rules start disabled so they cannot change operations before review.</p></div><Plus/></div><label>Rule name<input value={ruleForm.name} onChange={e=>setRuleForm(v=>({...v,name:e.target.value}))} placeholder="Overdue PO escalation"/></label><label>Description<textarea value={ruleForm.description} onChange={e=>setRuleForm(v=>({...v,description:e.target.value}))} placeholder="What this rule should do…"/></label><div className="flowTwo"><label>Module<select value={ruleForm.module_key} onChange={e=>setRuleForm(v=>({...v,module_key:e.target.value}))}>{modules.map(m=><option key={m}>{m}</option>)}</select></label><label>Trigger<select value={ruleForm.trigger_key} onChange={e=>setRuleForm(v=>({...v,trigger_key:e.target.value}))}>{triggerOptions.map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></label></div><div className="flowTwo"><label>Action<select value={ruleForm.action_key} onChange={e=>setRuleForm(v=>({...v,action_key:e.target.value}))}>{actionOptions.map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></label><label>Target role<select value={ruleForm.target_role} onChange={e=>setRuleForm(v=>({...v,target_role:e.target.value}))}>{roleOptions.map(r=><option key={r}>{r}</option>)}</select></label></div><div className="flowTwo"><label>Amount threshold<input type="number" value={ruleForm.threshold_amount} onChange={e=>setRuleForm(v=>({...v,threshold_amount:e.target.value}))} placeholder="Optional"/></label><label>SLA minutes<input type="number" min="0" value={ruleForm.sla_minutes} onChange={e=>setRuleForm(v=>({...v,sla_minutes:e.target.value}))}/></label></div>{ruleForm.action_key==='approval'&&<label>Approval chain<input value={ruleForm.approval_chain} onChange={e=>setRuleForm(v=>({...v,approval_chain:e.target.value}))} placeholder="inventory,admin"/><small>Comma-separated roles in approval order.</small></label>}<button className="flowPrimary" onClick={createRule} disabled={busy||!ruleForm.name.trim()}><Plus size={16}/>Create Disabled Rule</button></section>}
   <section className="flowPanel flowRules"><div className="flowPanelHead"><div><h2>Automation Rules</h2><p>Triggers run on database events. Time-based rules are evaluated by the SLA sweep.</p></div></div><div className="flowRuleRows">{filteredRules.length?filteredRules.map(r=><article key={r.id} className={`flowRule ${r.is_active?'live':''}`}><div className="flowRuleMain"><div className="flowRuleTop"><span className={r.is_active?'on':'off'}>{r.is_active?'ACTIVE':'OFF'}</span><span>{r.module_key}</span><span>{r.action_key}</span></div><h3>{r.name}</h3><p>{r.description||'No description'}</p><div className="flowPath"><b>WHEN</b><code>{r.trigger_key}</code><b>THEN</b><code>{r.action_key}</code>{r.target_role&&<><b>→</b><code>{r.target_role}</code></>}</div></div><div className="flowRuleControls"><label>Threshold<input type="number" value={r.threshold_amount??''} onChange={e=>setRules(xs=>xs.map(x=>x.id===r.id?{...x,threshold_amount:e.target.value===''?null:Number(e.target.value)}:x))} disabled={!canAdmin(access,'workflows','edit')}/></label><label>SLA min<input type="number" value={r.sla_minutes} onChange={e=>setRules(xs=>xs.map(x=>x.id===r.id?{...x,sla_minutes:Number(e.target.value||0)}:x))} disabled={!canAdmin(access,'workflows','edit')}/></label>{canAdmin(access,'workflows','edit')&&<><button onClick={()=>updateRule(r.id,{threshold_amount:r.threshold_amount,sla_minutes:r.sla_minutes})} disabled={busy}>Save</button><button className={r.is_active?'danger':''} onClick={()=>updateRule(r.id,{is_active:!r.is_active})} disabled={busy}>{r.is_active?'Turn Off':'Activate'}</button></>}</div></article>):<div className="flowEmpty">No rules match this search.</div>}</div></section>
  </div>}

  {tab==='approvals'&&<div className="flowApprovalLayout">
   <div className="flowSideForms">
    {canAdmin(access,'workflows','create')&&<section className="flowPanel"><div className="flowPanelHead"><div><h2>Manual Approval Request</h2><p>Use for finance, commercial or operational exceptions that are not tied to an automatic rule.</p></div><ShieldCheck/></div><label>Module<select value={approvalForm.module_key} onChange={e=>setApprovalForm(v=>({...v,module_key:e.target.value}))}>{modules.map(m=><option key={m}>{m}</option>)}</select></label><label>Title<input value={approvalForm.title} onChange={e=>setApprovalForm(v=>({...v,title:e.target.value}))} placeholder="Advance payment exception"/></label><label>Description<textarea value={approvalForm.description} onChange={e=>setApprovalForm(v=>({...v,description:e.target.value}))}/></label><div className="flowTwo"><label>Amount<input type="number" value={approvalForm.amount} onChange={e=>setApprovalForm(v=>({...v,amount:e.target.value}))}/></label><label>Due<input type="datetime-local" value={approvalForm.due_at} onChange={e=>setApprovalForm(v=>({...v,due_at:e.target.value}))}/></label></div><label>Approval chain<input value={approvalForm.chain} onChange={e=>setApprovalForm(v=>({...v,chain:e.target.value}))} placeholder="finance,admin"/></label><label>Admin link<input value={approvalForm.href} onChange={e=>setApprovalForm(v=>({...v,href:e.target.value}))} placeholder="/admin/finance"/></label><button className="flowPrimary" onClick={createApproval} disabled={busy||!approvalForm.title.trim()}><ShieldCheck size={16}/>Submit Approval</button></section>}

    {canAdmin(access,'pricing','edit')&&<section className="flowPanel"><div className="flowPanelHead"><div><h2>Pricing Override</h2><p>Submit a below-margin or exceptional commercial price without changing the live price until approval.</p></div><IndianRupee/></div>{!pricingRuleActive&&<div className="flowWarning"><AlertTriangle size={15}/>Activate “Pricing override approval” in Rules first.</div>}<label>Item type<select value={priceForm.item_type} onChange={e=>setPriceForm({item_type:e.target.value,item_id:'',cost:'',selling:'',mrp:'',gst:'18',reason:''})}><option value="variant">Finished Good</option><option value="component">Component</option><option value="enclosure">Enclosure</option></select></label><label>Item<select value={priceForm.item_id} onChange={e=>selectPriceItem(e.target.value)}><option value="">Select item</option>{selectedPriceItems.map(i=><option key={i.id} value={i.id}>{i.label} {i.sku?`(${i.sku})`:''}</option>)}</select></label><div className="flowTwo"><label>Cost<input type="number" value={priceForm.cost} onChange={e=>setPriceForm(v=>({...v,cost:e.target.value}))}/></label><label>Requested sell<input type="number" value={priceForm.selling} onChange={e=>setPriceForm(v=>({...v,selling:e.target.value}))}/></label></div><div className="flowTwo"><label>MRP<input type="number" value={priceForm.mrp} onChange={e=>setPriceForm(v=>({...v,mrp:e.target.value}))}/></label><label>GST %<input type="number" value={priceForm.gst} onChange={e=>setPriceForm(v=>({...v,gst:e.target.value}))}/></label></div><label>Reason<textarea value={priceForm.reason} onChange={e=>setPriceForm(v=>({...v,reason:e.target.value}))} placeholder="Project pricing / strategic EPC account…"/></label><button className="flowPrimary" onClick={requestPricing} disabled={busy||!pricingRuleActive||!priceForm.item_id||!priceForm.reason.trim()}><IndianRupee size={16}/>Request Override</button></section>}
   </div>

   <section className="flowPanel flowApprovals"><div className="flowPanelHead"><div><h2>Approval Queue</h2><p>Approvals move through the configured roles one step at a time. Owner Admin can act on any step.</p></div></div><div className="flowApprovalRows">{filteredApprovals.length?filteredApprovals.map(a=>{const chain=Array.isArray(a.approval_chain)?a.approval_chain:[];const role=chain[a.current_step-1]||'admin';const canDecide=a.status==='pending'&&(access?.role==='admin'||(canAdmin(access,'workflows','approve')&&access?.admin_role===role)||canAdmin(access,a.module_key,'approve')&&access?.admin_role===role);const ds=decisions.filter(d=>d.approval_id===a.id).sort((x,y)=>x.step_no-y.step_no);return <article key={a.id} className={`flowApproval ${a.status} ${a.due_at&&overdue(a.due_at)&&a.status==='pending'?'late':''}`}><div className="flowApprovalTop"><span className={`flowStatus ${a.status}`}>{a.status}</span><span>{a.module_key}</span><span>{a.source_type.replaceAll('_',' ')}</span>{a.amount!=null&&<b>{money(a.amount)}</b>}</div><h3>{a.title}</h3>{a.description&&<p>{a.description}</p>}<div className="flowChain">{chain.map((r,i)=><span key={`${r}-${i}`} className={i+1<a.current_step?'done':i+1===a.current_step&&a.status==='pending'?'current':''}>{i+1}. {r}</span>)}</div><div className="flowApprovalMeta"><span><Clock3 size={13}/>Due {fmt(a.due_at)}</span><span>Created {fmt(a.created_at)}</span>{a.href&&<Link href={a.href}>Open source →</Link>}</div>{ds.length>0&&<div className="flowDecisions">{ds.map(d=><span key={d.id}><b>Step {d.step_no} {d.decision}</b>{d.note?` — ${d.note}`:''}</span>)}</div>}{canDecide&&<div className="flowDecisionBox"><textarea value={notes[a.id]||''} onChange={e=>setNotes(v=>({...v,[a.id]:e.target.value}))} placeholder="Approval note (optional)"/><button onClick={()=>decide(a.id,'approved')} disabled={busy}><CheckCircle2 size={15}/>Approve</button><button className="danger" onClick={()=>decide(a.id,'rejected')} disabled={busy}><XCircle size={15}/>Reject</button></div>}</article>}):<div className="flowEmpty">No approvals match this search.</div>}</div></section>
  </div>}

  {tab==='runs'&&<section className="flowPanel"><div className="flowPanelHead"><div><h2>Automation Run History</h2><p>Each event/rule fingerprint executes once, preventing duplicate tasks or approvals from repeated refreshes.</p></div></div><div className="flowRunRows">{filteredRuns.length?filteredRuns.map(r=>{const rule=rules.find(x=>x.id===r.rule_id);return <article key={r.id}><span className={`flowRunStatus ${r.status}`}>{r.status}</span><div><b>{rule?.name||r.event_key}</b><small>{r.event_key} · {r.source_type}{r.source_id?` · ${r.source_id.slice(0,10)}`:''}</small></div><time>{fmt(r.created_at)}</time></article>}):<div className="flowEmpty">No automation executions yet.</div>}</div></section>}
 </div>
}
